container:
  image: devkitpro/devkitarm
task:
  generate_fake_rom_script:
    - head -c 16MB /dev/urandom > rom/fe7-jp.gba
  install_cmake_script:
    - wget https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-Linux-x86_64.tar.gz
    - tar -zxvf cmake-3.16.4-Linux-x86_64.tar.gz
  build_script:
    - export PATH=`pwd`/cmake-3.16.4-Linux-x86_64/bin:$PATH
    - ./configure
    - cd build && make