# SPDX-License-Identifier: MPL-2.0

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(NOT DEFINED DEVKITPRO_ROOT_DIR)
    set(DEVKITPRO_ROOT_DIR "$ENV{DEVKITPRO}")
endif()
if(NOT IS_DIRECTORY "${DEVKITPRO_ROOT_DIR}")
    message(FATAL_ERROR "devkitPro not found")
endif()

if(NOT DEFINED DEVKITARM_ROOT_DIR)
    set(DEVKITARM_ROOT_DIR "$ENV{DEVKITARM}")
endif()
if(NOT IS_DIRECTORY "${DEVKITARM_ROOT_DIR}")
    message(FATAL_ERROR "devkitARM not found")
endif()

set(CMAKE_PREFIX_PATH
    "${DEVKITARM_ROOT_DIR}"
    "${DEVKITPRO_ROOT_DIR}/tools")

set(TOOLCHAIN_PREFIX arm-none-eabi-)
set(CMAKE_C_COMPILER "${DEVKITARM_ROOT_DIR}/bin/${TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${DEVKITARM_ROOT_DIR}/bin/${TOOLCHAIN_PREFIX}g++")
set(CMAKE_LINKER "${DEVKITARM_ROOT_DIR}/bin/${TOOLCHAIN_PREFIX}ld")
set(CMAKE_AR "${DEVKITARM_ROOT_DIR}/bin/${TOOLCHAIN_PREFIX}ar")
set(CMAKE_OBJCOPY "${DEVKITARM_ROOT_DIR}/bin/${TOOLCHAIN_PREFIX}objcopy")

set(CMAKE_USER_MAKE_RULES_OVERRIDE "${CMAKE_CURRENT_LIST_DIR}/cmake/overrides-gcc.cmake")
