@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	fe6_seq_013_grp, native_instrument_map_bin
	.equ	fe6_seq_013_pri, 10
	.equ	fe6_seq_013_rev, 158
	.equ	fe6_seq_013_mvl, 127
	.equ	fe6_seq_013_key, 0

	.section .rodata
	.global	fe6_seq_013
	.align	2

@*********************** Track 01 ***********************@

fe6_seq_013_0:
	.byte	KEYSH , fe6_seq_013_key+0
	.byte	TEMPO , 128/2
	.byte		VOICE , 1
	.byte		VOL   , 41*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+17
	.byte		BEND  , c_v-4
	.byte	W06
	.byte		N06   , Gn3 , v104
	.byte	W18
	.byte		N03   , Gn3 , v088
	.byte	W06
	.byte		N28   , As3 , v084
	.byte	W48
	.byte		N05   , Gn3 , v100
	.byte	W18
	.byte		N03   , Gn3 , v080
	.byte	W06
	.byte		N68   , As3 , v092
	.byte	W72
	.byte		N06   , Gs3 
	.byte	W07
	.byte		        As3 , v080
	.byte	W08
	.byte		N07   , Gs3 , v084
	.byte	W03
	.byte	W06
	.byte		N88   , Gn3 , v096
	.byte	W90
	.byte		VOICE , 45
	.byte		VOL   , 66*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N32   , Cn4 , v104
	.byte	W36
	.byte		N11   , Dn4 
	.byte	W12
	.byte		N44   , En4 , v108
	.byte	W48
	.byte		N32   , Fn4 , v100
	.byte	W36
	.byte		N05   , En4 
	.byte	W06
	.byte		        Dn4 , v084
	.byte	W06
	.byte		N23   , En4 , v096
	.byte	W24
	.byte		        Cn4 , v100
	.byte	W24
	.byte		N32   , An4 , v104
	.byte	W36
	.byte		N05   , Bn4 , v096
	.byte	W06
	.byte		        Cn5 , v076
	.byte	W06
	.byte		N23   , Gn4 , v088
	.byte	W24
	.byte		        Fn4 , v096
	.byte	W24
	.byte		N44   , En4 
	.byte	W48
	.byte		        Dn4 , v112
	.byte	W48
	.byte		N32   , Cn4 , v116
	.byte	W36
	.byte		N11   , Dn4 , v108
	.byte	W12
	.byte		N44   , En4 
	.byte	W48
	.byte		N32   , Fn4 , v100
	.byte	W36
	.byte		N05   , En4 
	.byte	W06
	.byte		        Dn4 , v088
	.byte	W06
	.byte		N23   , En4 , v100
	.byte	W24
	.byte		        Cn4 
	.byte	W24
	.byte		N32   , En4 , v108
	.byte	W36
	.byte		N11   , Dn4 
	.byte	W12
	.byte		N32   , Dn4 , v116
	.byte	W36
	.byte		N11   , Cn4 , v092
	.byte	W12
	.byte		N32   , En4 , v100
	.byte	W36
	.byte		N11
	.byte	W12
	.byte		N23   , En4 , v104
	.byte	W24
	.byte		        Dn4 
	.byte	W24
	.byte		VOICE , 48
	.byte		VOL   , 71*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N92   , Gn2 , v092
	.byte	W96
	.byte		N44   , An2 
	.byte	W48
	.byte		        Bn2 , v096
	.byte	W48
	.byte		N32   , Cn4 , v120
	.byte	W36
	.byte		N11   , Dn4 
	.byte	W12
	.byte		N44   , En4 , v124
	.byte	W48
	.byte		N32   , Fn4 , v116
	.byte	W36
	.byte		N05   , En4 
	.byte	W06
	.byte		        Dn4 , v096
	.byte	W06
	.byte		N23   , En4 , v108
	.byte	W24
	.byte		        Cn4 , v112
	.byte	W24
	.byte		N32   , An4 , v120
	.byte	W36
	.byte		N05   , Bn4 , v108
	.byte	W06
	.byte		        Cn5 , v088
	.byte	W06
	.byte		N23   , Gn4 , v104
	.byte	W24
	.byte		        Fn4 , v112
	.byte	W24
	.byte		N44   , En4 
	.byte	W48
	.byte		        Dn4 , v127
	.byte	W48
	.byte		N32   , Cn4 
	.byte	W36
	.byte		N11   , Dn4 , v124
	.byte	W12
	.byte		N44   , En4 
	.byte	W48
	.byte		N32   , Fn4 , v112
	.byte	W36
	.byte		N05   , En4 
	.byte	W06
	.byte		        Dn4 , v104
	.byte	W06
	.byte		N23   , En4 , v116
	.byte	W24
	.byte		        Cn4 
	.byte	W24
	.byte		N32   , En4 , v124
	.byte	W36
	.byte		N11   , Dn4 
	.byte	W12
	.byte		N32   , Dn4 , v127
	.byte	W36
	.byte		N11   , Cn4 , v108
	.byte	W12
	.byte		N32   , En4 , v116
	.byte	W36
	.byte		N11   , En4 , v112
	.byte	W12
	.byte		N23   , En4 , v116
	.byte	W24
	.byte		        Dn4 , v120
	.byte	W24
	.byte		VOICE , 48
	.byte		VOL   , 82*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		TIE   , Cn3 , v084
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W44
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N08   , Gn1 , v104
	.byte	W12
	.byte		        Bn1 , v108
	.byte	W12
	.byte		N07   , Dn2 , v104
	.byte	W07
	.byte		        Fn2 , v096
	.byte	W08
	.byte		        An2 , v064
	.byte	W09
	.byte		TIE   , Cn3 , v092
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W23
	.byte		EOT
	.byte	W01
	.byte		N23   , Gn2 , v104
	.byte	W24
	.byte		        Cn3 , v096
	.byte	W24
	.byte		        En3 
	.byte	W24
	.byte		TIE   , Gn3 , v080
	.byte	W96
	.byte	W23
	.byte		EOT
	.byte	W01
	.byte		N05   , An1 , v100
	.byte	W06
	.byte		        Bn1 , v096
	.byte	W06
	.byte		        Cn2 , v100
	.byte	W06
	.byte		        Dn2 , v080
	.byte	W06
	.byte		        En2 , v100
	.byte	W06
	.byte		        Fn2 , v104
	.byte	W06
	.byte		        Gn2 , v088
	.byte	W06
	.byte		        An2 , v092
	.byte	W06
	.byte		N03   , Bn2 , v088
	.byte	W03
	.byte		        Cn3 
	.byte	W04
	.byte		        Dn3 
	.byte	W05
	.byte		        En3 
	.byte	W03
	.byte		        Fn3 , v100
	.byte	W04
	.byte		        Gn3 , v092
	.byte	W05
	.byte		N44   , An3 , v072
	.byte	W48
	.byte		N68   , Gn3 , v100
	.byte	W48
	.byte	W24
	.byte		N23   , Ds2 , v104
	.byte	W24
	.byte		        Gs2 , v092
	.byte	W24
	.byte		        Cn3 , v112
	.byte	W24
	.byte		N44   , Ds3 , v096
	.byte	W48
	.byte		        Dn3 , v088
	.byte	W48
	.byte		        Cn3 , v100
	.byte	W48
	.byte		N11   , Gn2 , v108
	.byte	W12
	.byte		        Cn2 , v104
	.byte	W12
	.byte		N68
	.byte	W24
	.byte	W48
	.byte		N05   , Cn2 , v096
	.byte	W06
	.byte		        Dn2 , v076
	.byte	W06
	.byte		        En2 , v100
	.byte	W06
	.byte		        Fn2 , v104
	.byte	W06
	.byte		        Gn2 , v092
	.byte	W06
	.byte		        An2 , v088
	.byte	W06
	.byte		        Bn2 , v092
	.byte	W06
	.byte		        Cn3 , v096
	.byte	W06
	.byte		N44   , Dn3 , v108
	.byte	W48
	.byte		        Ds3 , v072
	.byte	W48
	.byte		        Dn3 , v100
	.byte	W48
	.byte		        Fn3 , v092
	.byte	W48
	.byte		N92   , Gn3 , v096
	.byte	W96
	.byte		N72   , Gn2 , v092
	.byte	W96
	.byte	GOTO
	 .word	fe6_seq_013_0 + 0x34
	.byte	FINE

@*********************** Track 02 ***********************@

fe6_seq_013_1:
	.byte	KEYSH , fe6_seq_013_key+0
	.byte		VOICE , 1
	.byte		VOL   , 81*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N09   , Cn3 , v088
	.byte	W18
	.byte		N05   , Cn3 , v100
	.byte	W06
	.byte		N30   , Ds3 , v076
	.byte	W48
	.byte		N08   , Cn3 , v100
	.byte	W18
	.byte		N05
	.byte	W06
	.byte		N68   , Ds3 , v088
	.byte	W72
	.byte		N07   , Ds3 , v092
	.byte	W07
	.byte		N06   , Fn3 , v080
	.byte	W08
	.byte		        Ds3 
	.byte	W09
	.byte		N92   , Dn3 , v092
	.byte	W96
	.byte		VOICE , 45
	.byte		VOL   , 95*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N32   , Cn3 , v120
	.byte	W36
	.byte		N11   , Dn3 
	.byte	W12
	.byte		N44   , En3 , v124
	.byte	W48
	.byte		N32   , Fn3 , v116
	.byte	W36
	.byte		N05   , En3 
	.byte	W06
	.byte		        Dn3 , v096
	.byte	W06
	.byte		N23   , En3 , v108
	.byte	W24
	.byte		        Cn3 , v112
	.byte	W24
	.byte	PEND
	.byte		N32   , An3 , v120
	.byte	W36
	.byte		N05   , Bn3 , v108
	.byte	W06
	.byte		        Cn4 , v088
	.byte	W06
	.byte		N23   , Gn3 , v104
	.byte	W24
	.byte		        Fn3 , v112
	.byte	W24
	.byte	PEND
	.byte		N44   , En3 , v112
	.byte	W48
	.byte		        Dn3 , v127
	.byte	W48
	.byte	PEND
	.byte		N32   , Cn3 , v127
	.byte	W36
	.byte		N11   , Dn3 , v124
	.byte	W12
	.byte		N44   , En3 
	.byte	W48
	.byte	PEND
	.byte		N32   , Fn3 , v112
	.byte	W36
	.byte		N05   , En3 
	.byte	W06
	.byte		        Dn3 , v104
	.byte	W06
	.byte		N23   , En3 , v116
	.byte	W24
	.byte		        Cn3 
	.byte	W24
	.byte	PEND
	.byte		N32   , En3 , v124
	.byte	W36
	.byte		N11   , Dn3 
	.byte	W12
	.byte		N32   , Dn3 , v127
	.byte	W36
	.byte		N11   , Cn3 , v108
	.byte	W12
	.byte	PEND
	.byte		N32   , En3 , v116
	.byte	W36
	.byte		N11   , En3 , v112
	.byte	W12
	.byte		N23   , En3 , v116
	.byte	W24
	.byte		        Dn3 , v120
	.byte	W24
	.byte	PEND
	.byte		VOICE , 48
	.byte		VOL   , 62*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N92   , En3 , v088
	.byte	W96
	.byte		N44   , Fn3 
	.byte	W48
	.byte		N42   , Gn3 
	.byte	W48
	.byte		VOICE , 45
	.byte		VOL   , 95*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N32   , Cn3 , v120
	.byte	W36
	.byte		N11   , Dn3 
	.byte	W12
	.byte		N44   , En3 , v124
	.byte	W48
	.byte	PATT
	 .word	fe6_seq_013_1 + 0x41
	.byte	PATT
	 .word	fe6_seq_013_1 + 0x53
	.byte	PATT
	 .word	fe6_seq_013_1 + 0x66
	.byte	PATT
	 .word	fe6_seq_013_1 + 0x6E
	.byte	PATT
	 .word	fe6_seq_013_1 + 0x7A
	.byte	PATT
	 .word	fe6_seq_013_1 + 0x8B
	.byte	PATT
	 .word	fe6_seq_013_1 + 0x9B
	.byte		VOICE , 48
	.byte		VOL   , 81*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N32   , Cn3 , v092
	.byte	W36
	.byte		N11   , Dn3 , v096
	.byte	W12
	.byte		N44   , En3 
	.byte	W48
	.byte		N23   , Fn3 , v092
	.byte	W24
	.byte		        Dn3 , v096
	.byte	W24
	.byte		        En3 
	.byte	W24
	.byte		        Cn3 
	.byte	W24
	.byte		TIE   , Gn3 , v084
	.byte	W96
	.byte	W44
	.byte	W03
	.byte		EOT
	.byte	W07
	.byte		N08   , An1 , v096
	.byte	W12
	.byte		        Cn2 
	.byte	W09
	.byte		N07   , En2 , v108
	.byte	W09
	.byte		        Gn2 , v104
	.byte	W07
	.byte		N03   , Bn2 , v092
	.byte	W05
	.byte		VOICE , 60
	.byte		VOL   , 82*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+1
	.byte		BEND  , c_v-4
	.byte		N28   , Cn3 , v108
	.byte	W30
	.byte		N05   , Cn3 , v032
	.byte	W06
	.byte		N07   , Dn3 , v096
	.byte	W12
	.byte		N28   , En3 , v108
	.byte	W30
	.byte		N11   , En3 , v032
	.byte	W18
	.byte		N17   , Fn3 , v108
	.byte	W18
	.byte		N05   , Fn3 , v032
	.byte	W06
	.byte		N17   , Dn3 , v104
	.byte	W18
	.byte		N05   , Dn3 , v032
	.byte	W06
	.byte		N17   , En3 , v112
	.byte	W18
	.byte		N05   , En3 , v032
	.byte	W06
	.byte		N17   , Cn3 , v108
	.byte	W18
	.byte		N05   , Cn3 , v032
	.byte	W06
	.byte		N21   , An3 , v112
	.byte	W24
	.byte		N19   , Cn4 , v104
	.byte	W24
	.byte		N20   , Gn3 , v112
	.byte	W24
	.byte		N21   , Fn3 , v104
	.byte	W24
	.byte		N40   , En3 , v108
	.byte	W48
	.byte		        Dn3 , v116
	.byte	W48
	.byte		N28   , Cn3 , v104
	.byte	W36
	.byte		N10   , Dn3 , v096
	.byte	W12
	.byte		N36   , En3 , v108
	.byte	W48
	.byte		N21   , Fn3 , v104
	.byte	W24
	.byte		N11   , En3 , v108
	.byte	W12
	.byte		        Dn3 , v104
	.byte	W12
	.byte		N20   , En3 , v112
	.byte	W24
	.byte		        Cn3 , v100
	.byte	W24
	.byte		N32   , En3 , v112
	.byte	W36
	.byte		N11   , Dn3 , v104
	.byte	W12
	.byte		N30   , Dn3 , v108
	.byte	W36
	.byte		N10   , Cn3 , v096
	.byte	W12
	.byte		N36   , En3 , v112
	.byte	W48
	.byte		N19   , Dn3 , v104
	.byte	W24
	.byte		N17   , Gn3 
	.byte	W24
	.byte		N84   , Cn4 , v116
	.byte	W96
	.byte		N42   , As3 , v100
	.byte	W48
	.byte		        Gs3 , v088
	.byte	W48
	.byte		N18   , Gn3 , v104
	.byte	W24
	.byte		TIE   , Cn3 
	.byte	W72
	.byte	W68
	.byte		EOT
	.byte	W28
	.byte		N90   , Cn4 , v112
	.byte	W96
	.byte		N36   , As3 , v100
	.byte	W48
	.byte		N44   , Gs3 , v092
	.byte	W48
	.byte		TIE   , Cn4 , v100
	.byte	W96
	.byte	W68
	.byte	W03
	.byte		EOT
	.byte	W24
	.byte	W01
	.byte	GOTO
	 .word	fe6_seq_013_1 + 0x2E
	.byte	FINE

@*********************** Track 03 ***********************@

fe6_seq_013_2:
	.byte	KEYSH , fe6_seq_013_key+0
	.byte		VOICE , 1
	.byte		VOL   , 90*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+17
	.byte		N06   , Gn3 , v104
	.byte	W18
	.byte		N03   , Gn3 , v088
	.byte	W06
	.byte		N28   , As3 , v084
	.byte	W48
	.byte		N05   , Gn3 , v100
	.byte	W18
	.byte		N03   , Gn3 , v080
	.byte	W06
	.byte		N68   , As3 , v092
	.byte	W72
	.byte		N06   , Gs3 
	.byte	W07
	.byte		        As3 , v080
	.byte	W08
	.byte		N07   , Gs3 , v084
	.byte	W09
	.byte		N90   , Gn3 , v096
	.byte	W96
	.byte		VOICE , 60
	.byte		VOL   , 66*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v-16
	.byte		N92   , Cn3 , v092
	.byte	W96
	.byte		N44   , Gs3 
	.byte	W48
	.byte		        Gn3 
	.byte	W48
	.byte		N92   , Fn3 
	.byte	W96
	.byte		N44   , Gn3 
	.byte	W48
	.byte		        Fn3 
	.byte	W48
	.byte		        En3 
	.byte	W48
	.byte		        An3 , v080
	.byte	W48
	.byte		        Bn3 , v092
	.byte	W48
	.byte		        Cn4 
	.byte	W48
	.byte		N92   , Cn3 
	.byte	W96
	.byte		N44   , An3 
	.byte	W48
	.byte		N48   , Gn3 , v088
	.byte	W48
	.byte	W96
	.byte	W96
	.byte		VOICE , 100
	.byte		VOL   , 82*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+18
	.byte		N92   , En3 , v096
	.byte	W96
	.byte		        Cn3 , v092
	.byte	W96
	.byte		        Fn3 , v084
	.byte	W96
	.byte		N44   , Gn3 , v092
	.byte	W48
	.byte		        Fn3 , v096
	.byte	W48
	.byte		N92   , En3 , v100
	.byte	W96
	.byte		        Cn3 , v092
	.byte	W96
	.byte		        An2 , v080
	.byte	W96
	.byte		N44   , Bn2 , v100
	.byte	W48
	.byte		VOICE , 48
	.byte		VOL   , 82*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N05   , Gn2 , v116
	.byte	W06
	.byte		        An2 , v092
	.byte	W06
	.byte		        Bn2 , v112
	.byte	W06
	.byte		        Cn3 , v080
	.byte	W06
	.byte		N03   , Dn3 , v100
	.byte	W03
	.byte		        En3 , v104
	.byte	W04
	.byte		        Fn3 , v096
	.byte	W05
	.byte		        Gn3 , v092
	.byte	W03
	.byte		        An3 , v064
	.byte	W04
	.byte		        Bn3 , v092
	.byte	W05
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 60
	.byte		VOL   , 90*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+1
	.byte		N32   , Cn3 , v108
	.byte	W36
	.byte		N07   , Dn3 , v096
	.byte	W12
	.byte		N32   , En3 , v108
	.byte	W48
	.byte		N18   , Fn3 
	.byte	W24
	.byte		N20   , Dn3 , v104
	.byte	W24
	.byte		        En3 , v112
	.byte	W24
	.byte		N17   , Cn3 , v108
	.byte	W24
	.byte		N21   , An3 , v112
	.byte	W24
	.byte		N19   , Cn4 , v104
	.byte	W24
	.byte		N20   , Gn3 , v112
	.byte	W24
	.byte		N21   , Fn3 , v104
	.byte	W24
	.byte		N40   , En3 , v108
	.byte	W48
	.byte		        Dn3 , v116
	.byte	W48
	.byte		N28   , Cn3 , v104
	.byte	W36
	.byte		N10   , Dn3 , v096
	.byte	W12
	.byte		N36   , En3 , v108
	.byte	W48
	.byte		N21   , Fn3 , v104
	.byte	W24
	.byte		N11   , En3 , v108
	.byte	W12
	.byte		        Dn3 , v104
	.byte	W12
	.byte		N20   , En3 , v112
	.byte	W24
	.byte		        Cn3 , v100
	.byte	W24
	.byte		N32   , En3 , v112
	.byte	W36
	.byte		N11   , Dn3 , v104
	.byte	W12
	.byte		N30   , Dn3 , v108
	.byte	W36
	.byte		N10   , Cn3 , v096
	.byte	W12
	.byte		N36   , En3 , v112
	.byte	W48
	.byte		N19   , Dn3 , v104
	.byte	W24
	.byte		N17   , Gn3 
	.byte	W24
	.byte		N84   , Cn4 , v116
	.byte	W96
	.byte		N42   , As3 , v100
	.byte	W48
	.byte		        Gs3 , v088
	.byte	W48
	.byte		N18   , Gn3 , v104
	.byte	W24
	.byte		TIE   , Cn3 
	.byte	W72
	.byte	W68
	.byte		EOT
	.byte	W28
	.byte		N90   , Cn4 , v112
	.byte	W96
	.byte		N36   , As3 , v100
	.byte	W48
	.byte		N44   , Gs3 , v092
	.byte	W48
	.byte		TIE   , Cn4 , v100
	.byte	W96
	.byte	W68
	.byte	W03
	.byte		EOT
	.byte	W24
	.byte	W01
	.byte	GOTO
	 .word	fe6_seq_013_2 + 0x2E
	.byte	FINE

@*********************** Track 04 ***********************@

fe6_seq_013_3:
	.byte	KEYSH , fe6_seq_013_key+0
	.byte	W96
	.byte		VOICE , 90
	.byte		VOL   , 0*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v-24
	.byte		TIE   , Gn3 , v108
	.byte	W06
	.byte		VOL   , 10*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        18*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        25*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        33*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        37*fe6_seq_013_mvl/mxv
	.byte	W12
	.byte		        44*fe6_seq_013_mvl/mxv
	.byte	W12
	.byte		        52*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        56*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        63*fe6_seq_013_mvl/mxv
	.byte	W30
	.byte	W06
	.byte		        66*fe6_seq_013_mvl/mxv
	.byte	W18
	.byte		        71*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        74*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        81*fe6_seq_013_mvl/mxv
	.byte	W12
	.byte		        85*fe6_seq_013_mvl/mxv
	.byte	W18
	.byte		        89*fe6_seq_013_mvl/mxv
	.byte	W22
	.byte		EOT
	.byte	W08
	.byte		VOICE , 90
	.byte		VOL   , 57*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v-20
	.byte		N05   , Gn4 , v108
	.byte	W06
	.byte		        Gn4 , v036
	.byte	W06
	.byte		N04   , Gn4 , v084
	.byte	W05
	.byte		        Gn4 , v012
	.byte	W07
	.byte		        Gn4 , v092
	.byte	W05
	.byte		        Gn4 , v020
	.byte	W07
	.byte		N05   , Gn4 , v104
	.byte	W05
	.byte		        Gn4 , v032
	.byte	W07
	.byte		        Gn4 , v100
	.byte	W05
	.byte		        Gn4 , v024
	.byte	W07
	.byte		N04   , Gn4 , v096
	.byte	W05
	.byte		        Gn4 , v024
	.byte	W07
	.byte		N05   , Gn4 , v096
	.byte	W05
	.byte		        Gn4 , v024
	.byte	W07
	.byte		N04   , Gn4 , v104
	.byte	W05
	.byte		        Gn4 , v032
	.byte	W07
	.byte		N05   , Gs4 , v108
	.byte	W05
	.byte		        Gs4 , v036
	.byte	W07
	.byte		        Gs4 , v088
	.byte	W05
	.byte		        Gs4 , v016
	.byte	W07
	.byte		        Gs4 , v088
	.byte	W05
	.byte		        Gs4 , v016
	.byte	W07
	.byte		N04   , Gs4 , v088
	.byte	W05
	.byte		        Gs4 , v012
	.byte	W07
	.byte		N05   , Gn4 , v116
	.byte	W05
	.byte		        Gn4 , v040
	.byte	W07
	.byte		N04   , Gn4 , v096
	.byte	W05
	.byte		        Gn4 , v024
	.byte	W07
	.byte		        Gn4 , v084
	.byte	W05
	.byte		        Gn4 , v008
	.byte	W07
	.byte		        Gn4 , v096
	.byte	W05
	.byte		        Gn4 , v024
	.byte	W07
	.byte	PEND
	.byte		N05   , Fn4 , v116
	.byte	W05
	.byte		        Fn4 , v044
	.byte	W07
	.byte		        Fn4 , v100
	.byte	W05
	.byte		        Fn4 , v024
	.byte	W07
	.byte		        Fn4 , v096
	.byte	W05
	.byte		        Fn4 , v020
	.byte	W07
	.byte		        Fn4 , v092
	.byte	W05
	.byte		        Fn4 , v020
	.byte	W07
	.byte		        Gs4 , v112
	.byte	W05
	.byte		        Gs4 , v036
	.byte	W07
	.byte		        Gs4 , v096
	.byte	W05
	.byte		        Gs4 , v024
	.byte	W07
	.byte		        Gs4 , v088
	.byte	W05
	.byte		        Gs4 , v016
	.byte	W07
	.byte		N04   , Gs4 , v088
	.byte	W05
	.byte		        Gs4 , v016
	.byte	W07
	.byte	PEND
	.byte		N05   , Gn4 , v108
	.byte	W05
	.byte		        Gn4 , v036
	.byte	W07
	.byte		        Gn4 , v104
	.byte	W05
	.byte		        Gn4 , v032
	.byte	W07
	.byte		        Gn4 , v100
	.byte	W05
	.byte		        Gn4 , v028
	.byte	W07
	.byte		        Gn4 , v100
	.byte	W05
	.byte		        Gn4 , v028
	.byte	W07
	.byte		        Gn4 , v104
	.byte	W05
	.byte		        Gn4 , v032
	.byte	W07
	.byte		        Gn4 , v100
	.byte	W05
	.byte		        Gn4 , v028
	.byte	W07
	.byte		        Gn4 , v096
	.byte	W05
	.byte		        Gn4 , v024
	.byte	W07
	.byte		        Gn4 , v092
	.byte	W05
	.byte		        Gn4 , v016
	.byte	W07
	.byte	PEND
	.byte		N05   , En4 , v104
	.byte	W05
	.byte		        En4 , v032
	.byte	W07
	.byte		N04   , En4 , v096
	.byte	W05
	.byte		        En4 , v020
	.byte	W07
	.byte		        En4 , v084
	.byte	W05
	.byte		        En4 , v012
	.byte	W07
	.byte		        En4 , v100
	.byte	W05
	.byte		        En4 , v024
	.byte	W07
	.byte		N05   , En4 , v112
	.byte	W05
	.byte		        En4 , v036
	.byte	W07
	.byte		N04   , En4 , v096
	.byte	W05
	.byte		        En4 , v024
	.byte	W07
	.byte		        En4 , v100
	.byte	W05
	.byte		        En4 , v028
	.byte	W07
	.byte		        En4 , v104
	.byte	W05
	.byte		        En4 , v032
	.byte	W07
	.byte	PEND
	.byte		N05   , En4 , v112
	.byte	W05
	.byte		        En4 , v040
	.byte	W07
	.byte		        En4 , v104
	.byte	W05
	.byte		        En4 , v028
	.byte	W07
	.byte		N04   , En4 , v100
	.byte	W05
	.byte		        En4 , v028
	.byte	W07
	.byte		N05   , En4 , v100
	.byte	W05
	.byte		        En4 , v028
	.byte	W07
	.byte		        Dn4 , v108
	.byte	W05
	.byte		        Dn4 , v032
	.byte	W07
	.byte		N04   , Dn4 , v100
	.byte	W05
	.byte		        Dn4 , v028
	.byte	W07
	.byte		        Dn4 , v100
	.byte	W05
	.byte		        Dn4 , v028
	.byte	W07
	.byte		        Dn4 , v100
	.byte	W05
	.byte		        Dn4 , v028
	.byte	W07
	.byte	PEND
	.byte		N05   , Dn4 , v108
	.byte	W05
	.byte		        Dn4 , v036
	.byte	W07
	.byte		N04   , Dn4 , v100
	.byte	W05
	.byte		        Dn4 , v028
	.byte	W07
	.byte		        Dn4 , v092
	.byte	W05
	.byte		        Dn4 , v016
	.byte	W07
	.byte		N05   , Dn4 , v100
	.byte	W05
	.byte		        Dn4 , v028
	.byte	W07
	.byte		        Cn4 , v104
	.byte	W05
	.byte		        Cn4 , v032
	.byte	W07
	.byte		        Cn4 , v100
	.byte	W05
	.byte		        Cn4 , v028
	.byte	W07
	.byte		        Cn4 , v100
	.byte	W05
	.byte		        Cn4 , v028
	.byte	W07
	.byte		        Cn4 , v104
	.byte	W05
	.byte		        Cn4 , v028
	.byte	W07
	.byte	PEND
	.byte		N05   , Cn4 , v108
	.byte	W05
	.byte		        Cn4 , v036
	.byte	W07
	.byte		        Cn4 , v100
	.byte	W05
	.byte		        Cn4 , v028
	.byte	W07
	.byte		        Cn4 , v096
	.byte	W05
	.byte		        Cn4 , v024
	.byte	W07
	.byte		        Cn4 , v100
	.byte	W05
	.byte		        Cn4 , v028
	.byte	W07
	.byte		        Bn3 , v116
	.byte	W05
	.byte		        Bn3 , v044
	.byte	W07
	.byte		        Bn3 , v108
	.byte	W05
	.byte		        Bn3 , v036
	.byte	W07
	.byte		        Bn3 , v108
	.byte	W05
	.byte		        Bn3 , v032
	.byte	W07
	.byte		        Bn3 , v108
	.byte	W05
	.byte		        Bn3 , v036
	.byte	W07
	.byte	PEND
	.byte	W96
	.byte	W96
	.byte		        Gn4 , v108
	.byte	W06
	.byte		        Gn4 , v036
	.byte	W06
	.byte		N04   , Gn4 , v084
	.byte	W05
	.byte		        Gn4 , v012
	.byte	W07
	.byte		        Gn4 , v092
	.byte	W05
	.byte		        Gn4 , v020
	.byte	W07
	.byte		N05   , Gn4 , v104
	.byte	W05
	.byte		        Gn4 , v032
	.byte	W07
	.byte		        Gn4 , v100
	.byte	W05
	.byte		        Gn4 , v024
	.byte	W07
	.byte		N04   , Gn4 , v096
	.byte	W05
	.byte		        Gn4 , v024
	.byte	W07
	.byte		N05   , Gn4 , v096
	.byte	W05
	.byte		        Gn4 , v024
	.byte	W07
	.byte		N04   , Gn4 , v104
	.byte	W05
	.byte		        Gn4 , v032
	.byte	W07
	.byte	PATT
	 .word	fe6_seq_013_3 + 0x6B
	.byte	PATT
	 .word	fe6_seq_013_3 + 0xA0
	.byte	PATT
	 .word	fe6_seq_013_3 + 0xD3
	.byte	PATT
	 .word	fe6_seq_013_3 + 0x105
	.byte	PATT
	 .word	fe6_seq_013_3 + 0x13A
	.byte	PATT
	 .word	fe6_seq_013_3 + 0x16F
	.byte	PATT
	 .word	fe6_seq_013_3 + 0x1A3
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 48
	.byte		VOL   , 70*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v-21
	.byte		N90   , Gn2 , v108
	.byte	W96
	.byte		N44   , Gs2 
	.byte	W48
	.byte		        Gn2 , v116
	.byte	W48
	.byte		        Fn2 
	.byte	W48
	.byte		        Gs2 , v112
	.byte	W48
	.byte		N92   , Gn2 , v108
	.byte	W96
	.byte		N44   , En2 , v104
	.byte	W48
	.byte		        En2 , v112
	.byte	W48
	.byte		N44
	.byte	W48
	.byte		        Dn2 , v108
	.byte	W48
	.byte		N44
	.byte	W48
	.byte		        Cn2 , v104
	.byte	W48
	.byte		        Cn2 , v108
	.byte	W48
	.byte		        Bn1 , v116
	.byte	W48
	.byte		N92   , Ds2 , v108
	.byte	W96
	.byte		N84   , Fn2 , v116
	.byte	W96
	.byte		TIE   , Gn2 , v104
	.byte	W96
	.byte	W19
	.byte		EOT
	.byte	W05
	.byte		N03   , Gn2 , v100
	.byte	W12
	.byte		N05   , Gn2 , v108
	.byte	W12
	.byte		N44   , Gn2 , v084
	.byte	W48
	.byte		N92   , Ds2 , v104
	.byte	W96
	.byte		N84   , Fn2 
	.byte	W84
	.byte		N06   , En2 , v112
	.byte	W06
	.byte		N05   , Fn2 , v116
	.byte	W06
	.byte		TIE   , Gn2 , v108
	.byte	W96
	.byte	W76
	.byte	W01
	.byte		EOT
	.byte	W19
	.byte	GOTO
	 .word	fe6_seq_013_3 + 0x2F
	.byte	FINE

@*********************** Track 05 ***********************@

fe6_seq_013_4:
	.byte	KEYSH , fe6_seq_013_key+0
	.byte	W96
	.byte		VOICE , 90
	.byte		VOL   , 0*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v-24
	.byte		TIE   , Cn3 , v100
	.byte	W06
	.byte		VOL   , 10*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        18*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        25*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        33*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        37*fe6_seq_013_mvl/mxv
	.byte	W12
	.byte		        44*fe6_seq_013_mvl/mxv
	.byte	W12
	.byte		        52*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        56*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        63*fe6_seq_013_mvl/mxv
	.byte	W30
	.byte	W06
	.byte		        66*fe6_seq_013_mvl/mxv
	.byte	W18
	.byte		        71*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        74*fe6_seq_013_mvl/mxv
	.byte	W06
	.byte		        81*fe6_seq_013_mvl/mxv
	.byte	W12
	.byte		        85*fe6_seq_013_mvl/mxv
	.byte	W18
	.byte		        89*fe6_seq_013_mvl/mxv
	.byte	W23
	.byte		EOT
	.byte	W07
	.byte		VOICE , 33
	.byte		VOL   , 54*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v-20
	.byte		N05   , Cn3 , v100
	.byte	W12
	.byte		N04   , Cn3 , v080
	.byte	W12
	.byte		N03   , Cn3 , v076
	.byte	W12
	.byte		N04   , Cn3 , v092
	.byte	W12
	.byte		        Cn3 , v088
	.byte	W12
	.byte		        Cn3 , v092
	.byte	W12
	.byte		        Cn3 , v080
	.byte	W12
	.byte		N03   , Cn3 , v088
	.byte	W12
	.byte		N04   , Cn3 , v104
	.byte	W12
	.byte		        Cn3 , v096
	.byte	W12
	.byte		        Cn3 , v088
	.byte	W12
	.byte		N03
	.byte	W12
	.byte		N05   , Cn3 , v108
	.byte	W12
	.byte		N04   , Cn3 , v084
	.byte	W12
	.byte		N03   , Cn3 , v080
	.byte	W12
	.byte		N04   , Cn3 , v104
	.byte	W12
	.byte	PEND
	.byte		N04   , Cn3 , v112
	.byte	W12
	.byte		        Cn3 , v088
	.byte	W12
	.byte		N03   , Cn3 , v084
	.byte	W12
	.byte		N03
	.byte	W12
	.byte		N04   , Cn3 , v108
	.byte	W12
	.byte		        Cn3 , v088
	.byte	W12
	.byte		N04
	.byte	W12
	.byte		N03   , Cn3 , v092
	.byte	W12
	.byte	PEND
	.byte		N04   , Cn3 , v104
	.byte	W12
	.byte		        Cn3 , v092
	.byte	W12
	.byte		        Cn3 , v088
	.byte	W12
	.byte		        Cn3 , v092
	.byte	W12
	.byte		        Bn2 , v116
	.byte	W12
	.byte		        Bn2 , v096
	.byte	W12
	.byte		N03   , Bn2 , v092
	.byte	W12
	.byte		N03
	.byte	W12
	.byte	PEND
	.byte		N05   , An2 , v100
	.byte	W12
	.byte		N04   , An2 , v084
	.byte	W12
	.byte		N05   , An2 , v076
	.byte	W12
	.byte		N04   , An2 , v072
	.byte	W12
	.byte		N02   , Gs2 , v108
	.byte	W12
	.byte		N03   , Gs2 , v080
	.byte	W12
	.byte		        Gs2 , v084
	.byte	W12
	.byte		N03
	.byte	W12
	.byte	PEND
	.byte		N05   , Gn2 , v108
	.byte	W12
	.byte		N04   , Gn2 , v092
	.byte	W12
	.byte		N03   , Gn2 , v072
	.byte	W12
	.byte		N04   , Gn2 , v076
	.byte	W12
	.byte		        Fs2 , v100
	.byte	W12
	.byte		        Fs2 , v088
	.byte	W12
	.byte		N03   , Fs2 , v084
	.byte	W12
	.byte		        Fs2 , v088
	.byte	W12
	.byte	PEND
	.byte		N06   , Fn2 , v112
	.byte	W12
	.byte		N04   , Fn2 , v096
	.byte	W12
	.byte		        Fn2 , v092
	.byte	W12
	.byte		        Fn2 , v096
	.byte	W12
	.byte		N05   , Fn2 , v104
	.byte	W12
	.byte		N04   , Fn2 , v096
	.byte	W12
	.byte		N04
	.byte	W12
	.byte		N05   , Fn2 , v088
	.byte	W12
	.byte	PEND
	.byte		N04   , Gn2 , v112
	.byte	W12
	.byte		        Gn2 , v096
	.byte	W12
	.byte		N04
	.byte	W12
	.byte		        Gn2 , v100
	.byte	W12
	.byte		        Gn2 , v104
	.byte	W12
	.byte		        Gn2 , v096
	.byte	W12
	.byte		        Gn2 , v092
	.byte	W12
	.byte		        Gn2 , v096
	.byte	W12
	.byte	PEND
	.byte	W96
	.byte	W96
	.byte		N05   , Cn3 , v100
	.byte	W12
	.byte		N04   , Cn3 , v080
	.byte	W12
	.byte		N03   , Cn3 , v076
	.byte	W12
	.byte		N04   , Cn3 , v092
	.byte	W12
	.byte		        Cn3 , v088
	.byte	W12
	.byte		        Cn3 , v092
	.byte	W12
	.byte		        Cn3 , v080
	.byte	W12
	.byte		N03   , Cn3 , v088
	.byte	W12
	.byte	PATT
	 .word	fe6_seq_013_4 + 0x52
	.byte	PATT
	 .word	fe6_seq_013_4 + 0x6F
	.byte	PATT
	 .word	fe6_seq_013_4 + 0x8A
	.byte	PATT
	 .word	fe6_seq_013_4 + 0xA4
	.byte	PATT
	 .word	fe6_seq_013_4 + 0xC2
	.byte	PATT
	 .word	fe6_seq_013_4 + 0xE0
	.byte	PATT
	 .word	fe6_seq_013_4 + 0xFD
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 48
	.byte		VOL   , 70*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v-21
	.byte		N92   , Cn2 , v100
	.byte	W96
	.byte		        Cn2 , v104
	.byte	W96
	.byte		        Cn2 , v112
	.byte	W96
	.byte		N44   , Cn2 , v104
	.byte	W48
	.byte		        Bn1 , v116
	.byte	W48
	.byte		        An1 , v100
	.byte	W48
	.byte		        Gs1 , v108
	.byte	W48
	.byte		        Gn1 
	.byte	W48
	.byte		        Fs1 , v100
	.byte	W48
	.byte		N92   , Fn1 , v112
	.byte	W96
	.byte		        Gn1 
	.byte	W96
	.byte		        Gs1 , v100
	.byte	W96
	.byte		N88   , As1 
	.byte	W96
	.byte		TIE   , Cn2 
	.byte	W96
	.byte	W19
	.byte		EOT
	.byte	W05
	.byte		N03   , Cn2 , v096
	.byte	W12
	.byte		N04   , Cn2 , v100
	.byte	W12
	.byte		N44   , Cn2 , v084
	.byte	W48
	.byte		N92   , Gs1 , v100
	.byte	W96
	.byte		N84   , As1 , v096
	.byte	W96
	.byte		TIE   , Cn2 , v100
	.byte	W96
	.byte	W76
	.byte		EOT
	.byte	W20
	.byte	GOTO
	 .word	fe6_seq_013_4 + 0x2F
	.byte	FINE

@*********************** Track 06 ***********************@

fe6_seq_013_5:
	.byte	KEYSH , fe6_seq_013_key+0
	.byte		VOICE , 48
	.byte		VOL   , 52*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N05   , Gn2 , v084
	.byte	W18
	.byte		N03
	.byte	W06
	.byte		N30   , As2 
	.byte	W48
	.byte		N04   , Gn2 
	.byte	W18
	.byte		N04
	.byte	W06
	.byte		N92   , As2 
	.byte	W96
	.byte		N78   , Gn2 
	.byte	W72
	.byte		VOICE , 127
	.byte		VOL   , 82*fe6_seq_013_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W12
	.byte		N05   , Gn1 , v108
	.byte	W06
	.byte		        Fn1 , v092
	.byte	W06
	.byte		TIE   , Gn1 , v112
	.byte	W96
	.byte	W80
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		TIE   , Gn1 , v112
	.byte	W96
	.byte	W80
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		TIE   , Gn1 , v112
	.byte	W96
	.byte	W80
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		TIE   , Gn1 , v112
	.byte	W96
	.byte	W80
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		N48   , Gn1 
	.byte	W84
	.byte		N10   , Fn1 , v127
	.byte	W12
	.byte		N30   , Gn1 , v124
	.byte	W36
	.byte		N09   , Fn1 , v127
	.byte	W12
	.byte		N10   , Gn1 , v124
	.byte	W12
	.byte		        Fn1 
	.byte	W12
	.byte		N11   , Gn1 , v127
	.byte	W12
	.byte		N09   , Fn1 , v124
	.byte	W12
	.byte		TIE   , Gn1 , v112
	.byte	W96
	.byte	W80
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		TIE   , Gn1 , v112
	.byte	W96
	.byte	W80
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		TIE   , Gn1 , v112
	.byte	W96
	.byte	W80
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		TIE   , Gn1 , v112
	.byte	W96
	.byte	W80
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		TIE   , Gn1 , v124
	.byte	W96
	.byte	W44
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N02   , Fn1 , v048
	.byte	W03
	.byte		        Gn1 , v052
	.byte	W03
	.byte		        Fn1 
	.byte	W03
	.byte		        Gn1 , v056
	.byte	W03
	.byte		N05   , Fn1 , v060
	.byte	W06
	.byte		N02   , Gn1 , v068
	.byte	W03
	.byte		N05   , Fn1 
	.byte	W06
	.byte		N02   , Gn1 , v076
	.byte	W03
	.byte		N05   , Fn1 , v080
	.byte	W06
	.byte		N02   , Gn1 , v084
	.byte	W03
	.byte		N05   , Fn1 , v088
	.byte	W06
	.byte		N02   , Fn1 , v096
	.byte	W03
	.byte		N92   , Gn1 , v100
	.byte	W96
	.byte		N05   , Fn1 , v036
	.byte	W06
	.byte		N02   , Gn1 , v040
	.byte	W03
	.byte		        Fn1 , v044
	.byte	W03
	.byte		        Gn1 
	.byte	W03
	.byte		N05   , Fn1 , v048
	.byte	W06
	.byte		N02   , Fn1 , v052
	.byte	W03
	.byte		        Gn1 
	.byte	W03
	.byte		        Fn1 , v056
	.byte	W03
	.byte		        Gn1 
	.byte	W03
	.byte		        Fn1 , v060
	.byte	W03
	.byte		        Gn1 
	.byte	W03
	.byte		        Fn1 , v064
	.byte	W03
	.byte		        Gn1 , v068
	.byte	W03
	.byte		        Fn1 
	.byte	W03
	.byte		        Gn1 , v072
	.byte	W03
	.byte		        Fn1 
	.byte	W03
	.byte		        Gn1 , v076
	.byte	W03
	.byte		        Fn1 
	.byte	W03
	.byte		        Gn1 , v080
	.byte	W03
	.byte		N05   , Fn1 
	.byte	W06
	.byte		N02   , Gn1 , v084
	.byte	W03
	.byte		        Fn1 , v088
	.byte	W03
	.byte		        Gn1 
	.byte	W03
	.byte		        Fn1 , v092
	.byte	W03
	.byte		        Gn1 , v096
	.byte	W03
	.byte		        Fn1 
	.byte	W03
	.byte		N05   , Gn1 , v100
	.byte	W06
	.byte		N02   , Fn1 , v104
	.byte	W03
	.byte		TIE   , Gn1 
	.byte	W96
	.byte	W80
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N11   , Fn1 , v124
	.byte	W12
	.byte		TIE   , Gn1 , v127
	.byte	W96
	.byte	W80
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N11   , Fn1 , v124
	.byte	W12
	.byte		TIE   , Gn1 , v127
	.byte	W96
	.byte	W68
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N23   , Fn1 , v112
	.byte	W24
	.byte		N92   , Gn1 , v127
	.byte	W96
	.byte		N11   , Gn1 , v096
	.byte	W12
	.byte		        Fn1 , v100
	.byte	W12
	.byte		        Gn1 , v108
	.byte	W12
	.byte		        Fn1 , v112
	.byte	W12
	.byte		        Gn1 , v116
	.byte	W12
	.byte		        Fn1 , v112
	.byte	W12
	.byte		        Gn1 , v120
	.byte	W12
	.byte		        Fn1 , v116
	.byte	W12
	.byte		TIE   , Gn1 , v127
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W44
	.byte		EOT
	.byte	W01
	.byte		N05   , Fn1 , v068
	.byte	W06
	.byte		N02   , Gn1 , v072
	.byte	W03
	.byte		        Fn1 , v048
	.byte	W03
	.byte		        Gn1 , v072
	.byte	W03
	.byte		N05   , Fn1 , v056
	.byte	W06
	.byte		N02   , Gn1 , v072
	.byte	W03
	.byte		        Fn1 , v056
	.byte	W03
	.byte		        Gn1 , v092
	.byte	W03
	.byte		N05   , Fn1 
	.byte	W06
	.byte		        Fn1 , v088
	.byte		N05   , Gn1 , v104
	.byte	W06
	.byte		        Fn1 , v068
	.byte		N05   , Gn1 , v072
	.byte	W06
	.byte		N02   , Fn1 , v092
	.byte	W03
	.byte		TIE   , Gn1 , v108
	.byte	W96
	.byte	W96
	.byte	W80
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N11   , Fn1 , v088
	.byte	W12
	.byte		N32   , Gn1 , v112
	.byte	W36
	.byte		N11   , Fn1 , v108
	.byte	W12
	.byte		        Gn1 , v112
	.byte	W12
	.byte		        Fn1 , v116
	.byte	W12
	.byte		        Gn1 , v127
	.byte	W12
	.byte		        Fn1 
	.byte	W12
	.byte	GOTO
	 .word	fe6_seq_013_5 + 0x2A
	.byte	FINE

@*********************** Track 07 ***********************@

fe6_seq_013_6:
	.byte	KEYSH , fe6_seq_013_key+0
	.byte		VOICE , 127
	.byte		VOL   , 74*fe6_seq_013_mvl/mxv
	.byte	W96
	.byte	W96
	.byte		N06   , Dn1 , v116
	.byte	W06
	.byte		        Fs2 , v028
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v024
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v020
	.byte	W06
	.byte		        Dn1 , v116
	.byte	W06
	.byte		        Fs2 , v028
	.byte	W06
	.byte		        Dn1 , v116
	.byte	W06
	.byte		        Fs2 , v020
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v016
	.byte	W06
	.byte		        Dn1 , v116
	.byte	W06
	.byte		        Fs2 , v012
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v016
	.byte	W06
	.byte	PEND
	.byte		N06   , Dn1 , v116
	.byte	W06
	.byte		        Fs2 , v028
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v040
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v020
	.byte	W06
	.byte		        Dn1 , v116
	.byte	W06
	.byte		        Fs2 , v020
	.byte	W06
	.byte		        Dn1 , v116
	.byte	W06
	.byte		        Fs2 , v016
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v016
	.byte	W06
	.byte		        Dn1 , v116
	.byte	W06
	.byte		        Fs2 , v020
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v036
	.byte	W06
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x8
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x3A
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x8
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x3A
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x8
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x3A
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x3A
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x3A
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x8
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x3A
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x8
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x3A
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x8
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x3A
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x8
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x3A
	.byte		N22   , An2 , v092
	.byte	W36
	.byte		N02   , Dn1 , v116
	.byte	W12
	.byte		N04
	.byte	W48
	.byte		N05   , Dn1 , v116
	.byte	W36
	.byte		N04
	.byte	W12
	.byte		N05
	.byte	W24
	.byte		N04
	.byte	W24
	.byte	PEND
	.byte		N05   , Dn1 , v116
	.byte	W36
	.byte		N04
	.byte	W12
	.byte		N05
	.byte	W36
	.byte		N03
	.byte	W12
	.byte	PEND
	.byte		N04   , Dn1 , v116
	.byte	W36
	.byte		N03
	.byte	W12
	.byte		N04
	.byte	W36
	.byte		N03
	.byte	W12
	.byte	PEND
	.byte		N06   , Dn1 , v116
	.byte		N06   , Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v028
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v024
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v020
	.byte	W06
	.byte		        Dn1 , v116
	.byte		N06   , Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v028
	.byte	W06
	.byte		        Dn1 , v116
	.byte		N06   , Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v020
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v016
	.byte	W06
	.byte		        Dn1 , v116
	.byte		N06   , Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v012
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v016
	.byte	W06
	.byte	PEND
	.byte		N06   , Dn1 , v116
	.byte		N06   , Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v028
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v040
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v020
	.byte	W06
	.byte		        Dn1 , v116
	.byte		N06   , Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v020
	.byte	W06
	.byte		        Dn1 , v116
	.byte		N06   , Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v016
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v016
	.byte	W06
	.byte		        Dn1 , v116
	.byte		N06   , Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v020
	.byte	W06
	.byte		        Fs2 , v048
	.byte	W06
	.byte		        Fs2 , v036
	.byte	W06
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_013_6 + 0xE7
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x125
	.byte	PATT
	 .word	fe6_seq_013_6 + 0xE7
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x125
	.byte	PATT
	 .word	fe6_seq_013_6 + 0xE7
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x125
	.byte		N28   , An2 , v092
	.byte	W36
	.byte		N02   , Dn1 , v116
	.byte	W12
	.byte		N04
	.byte	W48
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_013_6 + 0xC6
	.byte	PATT
	 .word	fe6_seq_013_6 + 0xD1
	.byte	PATT
	 .word	fe6_seq_013_6 + 0xDC
	.byte	PATT
	 .word	fe6_seq_013_6 + 0x181
	.byte	PATT
	 .word	fe6_seq_013_6 + 0xC6
	.byte	PATT
	 .word	fe6_seq_013_6 + 0xD1
	.byte	PATT
	 .word	fe6_seq_013_6 + 0xDC
	.byte	W96
	.byte	GOTO
	 .word	fe6_seq_013_6 + 0x3A
	.byte	FINE

@******************************************************@

	.align	2

fe6_seq_013:
	.byte	7	@ NumTrks
	.byte	0	@ NumBlks
	.byte	fe6_seq_013_pri	@ Priority
	.byte	fe6_seq_013_rev	@ Reverb

	.word	fe6_seq_013_grp

	.word	fe6_seq_013_0
	.word	fe6_seq_013_1
	.word	fe6_seq_013_2
	.word	fe6_seq_013_3
	.word	fe6_seq_013_4
	.word	fe6_seq_013_5
	.word	fe6_seq_013_6

	.end
