@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	fe6_seq_016_grp, native_instrument_map_bin
	.equ	fe6_seq_016_pri, 10
	.equ	fe6_seq_016_rev, 158
	.equ	fe6_seq_016_mvl, 127
	.equ	fe6_seq_016_key, 0

	.section .rodata
	.global	fe6_seq_016
	.align	2

@*********************** Track 01 ***********************@

fe6_seq_016_0:
	.byte	KEYSH , fe6_seq_016_key+0
	.byte	TEMPO , 132/2
	.byte		VOICE , 1
	.byte		VOL   , 86*fe6_seq_016_mvl/mxv
	.byte		PAN   , c_v-13
	.byte	W24
	.byte		N44   , En3 , v112
	.byte	W48
	.byte		N07   , An2 , v092
	.byte	W08
	.byte		        Cn3 
	.byte	W08
	.byte		        En3 
	.byte	W08
	.byte		        Gn3 
	.byte	W08
	.byte		        En3 , v084
	.byte	W08
	.byte		        Cn3 , v088
	.byte	W08
	.byte		N21   , Fs3 
	.byte	W24
	.byte		N07   , An2 , v084
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		N06   , Fs3 , v088
	.byte	W08
	.byte		N22   , Fn3 , v096
	.byte	W24
	.byte		N07   , An2 , v080
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		        Fn3 , v080
	.byte	W08
	.byte		        En3 
	.byte	W08
	.byte		        An2 , v076
	.byte	W08
	.byte		        Cn3 , v088
	.byte	W08
	.byte		        Dn3 , v072
	.byte	W08
	.byte		        Fn2 , v096
	.byte	W08
	.byte		        Dn3 , v104
	.byte	W08
	.byte		        Cn3 , v084
	.byte	W08
	.byte		        Bn2 , v064
	.byte	W08
	.byte		        An2 , v084
	.byte	W08
	.byte		N08   , En2 , v088
	.byte	W16
	.byte		N07   , En2 , v096
	.byte	W08
	.byte		        Gs2 , v072
	.byte	W08
	.byte		        Bn2 , v084
	.byte	W08
	.byte		        Dn3 , v088
	.byte	W08
	.byte		        Fn3 , v084
	.byte	W08
	.byte		        Dn3 , v088
	.byte	W08
	.byte		        Fn3 , v084
	.byte	W08
	.byte		N28   , Cn3 , v092
	.byte	W48
	.byte		        En3 
	.byte	W48
	.byte		N07   , An2 , v080
	.byte	W08
	.byte		        Cn3 , v084
	.byte	W08
	.byte		        En3 , v080
	.byte	W08
	.byte		        Gn3 , v088
	.byte	W08
	.byte		        En3 , v080
	.byte	W08
	.byte		        Cn3 , v076
	.byte	W08
	.byte		N22   , Fs3 , v084
	.byte	W24
	.byte		N07   , An2 , v080
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		N05   , Fs3 , v092
	.byte	W08
	.byte		N23   , Fn3 , v096
	.byte	W24
	.byte		N07   , An2 , v080
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		        Fn3 , v080
	.byte	W08
	.byte		TIE   , En3 , v100
	.byte	W96
	.byte	W54
	.byte		EOT
	.byte	W18
	.byte		N08   , En3 , v108
	.byte	W16
	.byte		N03   , En3 , v096
	.byte	W08
	.byte		N42   , Fn3 , v108
	.byte	W48
	.byte		N07   , An2 , v080
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		        Fn3 , v084
	.byte	W08
	.byte		        An3 , v092
	.byte	W08
	.byte		        Fn3 , v088
	.byte	W08
	.byte		        Dn3 , v104
	.byte	W08
	.byte		N23   , Gn3 , v096
	.byte	W24
	.byte		N07   , An2 , v092
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		        Gn3 , v084
	.byte	W08
	.byte		N23   , Fn3 , v088
	.byte	W24
	.byte		N07   , An2 , v084
	.byte	W08
	.byte		        Dn3 , v092
	.byte	W08
	.byte		        Fn3 , v080
	.byte	W08
	.byte		        En3 , v088
	.byte	W08
	.byte		        An2 , v084
	.byte	W08
	.byte		        Cn3 , v088
	.byte	W08
	.byte		        Dn3 
	.byte	W08
	.byte		        Fn2 , v096
	.byte	W08
	.byte		        Dn3 , v108
	.byte	W08
	.byte		        Cn3 , v092
	.byte	W08
	.byte		        Bn2 , v084
	.byte	W08
	.byte		        An2 , v076
	.byte	W08
	.byte		N08   , En2 , v096
	.byte	W16
	.byte		N07   , En2 , v088
	.byte	W08
	.byte		        Gs2 , v076
	.byte	W08
	.byte		        Bn2 , v092
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		        Fn3 , v084
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		        Fn3 , v080
	.byte	W08
	.byte		N36   , Cn3 , v092
	.byte	W48
	.byte		N44   , Fn3 , v112
	.byte	W48
	.byte		N07   , An2 , v092
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		        Fn3 , v080
	.byte	W08
	.byte		        An3 , v088
	.byte	W08
	.byte		        Fn3 , v084
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		N23   , Gn3 
	.byte	W24
	.byte		N07   , An2 , v084
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		        Gn3 , v088
	.byte	W08
	.byte		N23   , Fn3 , v092
	.byte	W24
	.byte		N07   , An2 , v088
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		        Fn3 , v076
	.byte	W08
	.byte		N23   , Gn3 , v096
	.byte	W24
	.byte		N07   , An2 , v080
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		        Gn3 , v088
	.byte	W08
	.byte		N23   , Fn3 , v092
	.byte	W24
	.byte		N07   , An2 , v088
	.byte	W08
	.byte		        Dn3 , v096
	.byte	W08
	.byte		        Gn3 , v084
	.byte	W08
	.byte		N68   , Fn3 
	.byte	W72
	.byte		N22   , En3 , v096
	.byte	W24
	.byte		N92   , Dn3 , v108
	.byte	W96
	.byte		N32   , As2 , v080
	.byte	W36
	.byte		        Dn3 , v100
	.byte	W36
	.byte		N23   , An3 , v084
	.byte	W24
	.byte		N92   , Gn3 , v092
	.byte	W96
	.byte		        En3 , v104
	.byte	W96
	.byte		        Fn3 , v092
	.byte	W96
	.byte		N32   , As2 , v084
	.byte	W36
	.byte		        Dn3 , v104
	.byte	W36
	.byte		N23   , An3 , v068
	.byte	W24
	.byte		N92   , Gn3 , v088
	.byte	W96
	.byte		        En3 
	.byte	W96
	.byte		        Fn3 
	.byte	W96
	.byte		N32   , Fn3 , v084
	.byte	W36
	.byte		        An3 
	.byte	W36
	.byte		N23   , Fn3 
	.byte	W24
	.byte		N92   , Gn3 
	.byte	W96
	.byte		        En3 , v092
	.byte	W96
	.byte		        Fn3 , v084
	.byte	W96
	.byte		N32
	.byte	W36
	.byte		        Gn3 , v088
	.byte	W36
	.byte		N23   , Fn3 , v084
	.byte	W24
	.byte		N92   , En3 , v092
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	fe6_seq_016_0 + 0xB
	.byte	FINE

@*********************** Track 02 ***********************@

fe6_seq_016_1:
	.byte	KEYSH , fe6_seq_016_key+0
	.byte		VOICE , 73
	.byte		MOD   , 1
	.byte		VOL   , 82*fe6_seq_016_mvl/mxv
	.byte		PAN   , c_v+12
	.byte	W24
	.byte		N44   , En3 , v088
	.byte	W48
	.byte		N07   , An2 , v076
	.byte	W08
	.byte		        Cn3 , v072
	.byte	W08
	.byte		        En3 , v068
	.byte	W08
	.byte		        Gn3 , v080
	.byte	W08
	.byte		        En3 
	.byte	W08
	.byte		N05   , Cn3 , v060
	.byte	W08
	.byte		N21   , Fs3 , v080
	.byte	W24
	.byte		N07   , An2 , v072
	.byte	W08
	.byte		        Dn3 , v084
	.byte	W08
	.byte		N06   , Fs3 , v072
	.byte	W08
	.byte		N19   , Fn3 , v096
	.byte	W24
	.byte		N07   , An2 , v068
	.byte	W08
	.byte		        Dn3 , v080
	.byte	W08
	.byte		        Fn3 , v084
	.byte	W08
	.byte		N06   , En3 , v080
	.byte	W08
	.byte		N07   , An2 , v068
	.byte	W08
	.byte		        Cn3 , v080
	.byte	W08
	.byte		N06   , Dn3 
	.byte	W08
	.byte		        Fn2 , v052
	.byte	W08
	.byte		N07   , Dn3 , v088
	.byte	W08
	.byte		        Cn3 , v084
	.byte	W08
	.byte		N06   , Bn2 
	.byte	W08
	.byte		        An2 , v056
	.byte	W08
	.byte		N08   , En2 , v088
	.byte	W16
	.byte		N06
	.byte	W08
	.byte		N07   , Gs2 , v068
	.byte	W08
	.byte		        Bn2 , v080
	.byte	W08
	.byte		        Dn3 
	.byte	W08
	.byte		        Fn3 , v064
	.byte	W08
	.byte		        Dn3 , v088
	.byte	W08
	.byte		        Fn3 , v068
	.byte	W08
	.byte		N24   , Cn3 , v080
	.byte	W48
	.byte		N32   , En3 , v092
	.byte	W48
	.byte		N07   , An2 , v080
	.byte	W08
	.byte		        Cn3 
	.byte	W08
	.byte		        En3 , v072
	.byte	W08
	.byte		        Gn3 , v064
	.byte	W08
	.byte		        En3 , v080
	.byte	W08
	.byte		        Cn3 , v064
	.byte	W08
	.byte		N22   , Fs3 , v092
	.byte	W24
	.byte		N07   , An2 , v064
	.byte	W08
	.byte		        Dn3 , v084
	.byte	W08
	.byte		        Fs3 , v068
	.byte	W08
	.byte		N23   , Fn3 , v092
	.byte	W24
	.byte		N06   , An2 , v064
	.byte	W08
	.byte		N07   , Dn3 , v080
	.byte	W08
	.byte		        Fn3 
	.byte	W08
	.byte		TIE   , En3 , v088
	.byte	W96
	.byte	W01
	.byte		EOT
	.byte	W68
	.byte	W03
	.byte		N05   , En3 , v092
	.byte	W16
	.byte		N03   , En3 , v084
	.byte	W08
	.byte		N32   , Fn3 , v088
	.byte	W48
	.byte		N06   , An2 , v080
	.byte	W08
	.byte		N05   , Dn3 , v076
	.byte	W08
	.byte		N07   , Fn3 , v072
	.byte	W08
	.byte		        An3 , v080
	.byte	W08
	.byte		        Fn3 , v084
	.byte	W08
	.byte		        Dn3 
	.byte	W08
	.byte		N22   , Gn3 , v088
	.byte	W24
	.byte		N07   , An2 , v064
	.byte	W08
	.byte		        Dn3 , v084
	.byte	W08
	.byte		        Gn3 , v076
	.byte	W08
	.byte		N22   , Fn3 , v084
	.byte	W24
	.byte		N06   , An2 , v060
	.byte	W08
	.byte		N07   , Dn3 , v084
	.byte	W08
	.byte		        Fn3 , v080
	.byte	W08
	.byte		N06   , En3 
	.byte	W08
	.byte		N07   , An2 , v068
	.byte	W08
	.byte		        Cn3 , v072
	.byte	W08
	.byte		N06   , Dn3 , v092
	.byte	W08
	.byte		N07   , Fn2 , v088
	.byte	W08
	.byte		        Dn3 
	.byte	W08
	.byte		        Cn3 , v076
	.byte	W08
	.byte		N06   , Bn2 , v080
	.byte	W08
	.byte		N05   , An2 , v068
	.byte	W08
	.byte		N07   , En2 , v096
	.byte	W16
	.byte		        En2 , v092
	.byte	W08
	.byte		N06   , Gs2 , v072
	.byte	W08
	.byte		        Bn2 , v088
	.byte	W08
	.byte		N07   , Dn3 
	.byte	W08
	.byte		        Fn3 , v064
	.byte	W08
	.byte		        Dn3 , v080
	.byte	W08
	.byte		        Fn3 , v072
	.byte	W08
	.byte		N32   , Cn3 , v084
	.byte	W48
	.byte		N36   , Fn3 , v088
	.byte	W48
	.byte		N07   , An2 , v084
	.byte	W08
	.byte		        Dn3 
	.byte	W08
	.byte		        Fn3 , v068
	.byte	W08
	.byte		        An3 , v072
	.byte	W08
	.byte		        Fn3 , v084
	.byte	W08
	.byte		        Dn3 , v088
	.byte	W08
	.byte		N22   , Gn3 
	.byte	W24
	.byte		N07   , An2 , v064
	.byte	W08
	.byte		        Dn3 , v088
	.byte	W08
	.byte		        Gn3 , v072
	.byte	W08
	.byte		N22   , Fn3 , v088
	.byte	W24
	.byte		N07   , An2 , v072
	.byte	W08
	.byte		        Dn3 , v084
	.byte	W08
	.byte		        Fn3 , v056
	.byte	W08
	.byte		N22   , Gn3 , v092
	.byte	W24
	.byte		N05   , An2 , v080
	.byte	W08
	.byte		N06   , Dn3 , v088
	.byte	W08
	.byte		N07   , Gn3 , v080
	.byte	W08
	.byte		N21   , Fn3 , v084
	.byte	W24
	.byte		N06   , An2 , v060
	.byte	W08
	.byte		        Dn3 , v080
	.byte	W08
	.byte		N07   , Gn3 
	.byte	W08
	.byte		N76   , Fn3 , v084
	.byte	W72
	.byte		VOICE , 60
	.byte		VOL   , 84*fe6_seq_016_mvl/mxv
	.byte		PAN   , c_v-13
	.byte	W24
	.byte		TIE   , As2 , v080
	.byte	W96
	.byte	W19
	.byte		EOT
	.byte	W05
	.byte		N23   , Fn2 , v100
	.byte	W24
	.byte		        As2 , v076
	.byte	W24
	.byte		        Dn3 , v088
	.byte	W24
	.byte		N92   , Cn3 , v080
	.byte	W96
	.byte	W24
	.byte		N23   , Gn2 , v072
	.byte	W24
	.byte		        Cn3 , v080
	.byte	W24
	.byte		        En3 , v068
	.byte	W24
	.byte		TIE   , As2 , v064
	.byte	W96
	.byte	W04
	.byte		EOT
	.byte	W20
	.byte		N23   , Fn2 , v076
	.byte	W24
	.byte		        As2 , v060
	.byte	W24
	.byte		        Dn3 , v084
	.byte	W24
	.byte		TIE   , Cn3 , v072
	.byte	W96
	.byte	W15
	.byte		EOT
	.byte	W09
	.byte		N23   , Gn2 , v076
	.byte	W24
	.byte		        Cn3 , v080
	.byte	W24
	.byte		        En3 , v076
	.byte	W24
	.byte		TIE   , As2 , v056
	.byte	W96
	.byte	W10
	.byte		EOT
	.byte	W14
	.byte		N23   , Fn2 , v076
	.byte	W24
	.byte		        As2 , v060
	.byte	W24
	.byte		        Dn3 , v084
	.byte	W24
	.byte		TIE   , En3 , v080
	.byte	W96
	.byte	W22
	.byte		EOT
	.byte	W02
	.byte		N23   , Gn2 , v084
	.byte	W24
	.byte		        Cn3 , v080
	.byte	W24
	.byte		        En3 , v076
	.byte	W24
	.byte		N92   , Dn3 , v088
	.byte	W96
	.byte		N44   , Bn2 , v064
	.byte	W48
	.byte		        Fn2 , v068
	.byte	W48
	.byte		        En2 , v076
	.byte	W48
	.byte		        An2 
	.byte	W48
	.byte		        Bn2 , v064
	.byte	W48
	.byte		N40   , Dn3 , v052
	.byte	W48
	.byte	GOTO
	 .word	fe6_seq_016_1 + 0xB
	.byte	FINE

@*********************** Track 03 ***********************@

fe6_seq_016_2:
	.byte	KEYSH , fe6_seq_016_key+0
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W72
	.byte		VOICE , 58
	.byte		VOL   , 74*fe6_seq_016_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W24
	.byte	W72
	.byte		N05   , An3 , v080
	.byte		N06   , En4 , v100
	.byte	W12
	.byte		N11   , An3 , v004
	.byte		N12   , En4 , v012
	.byte	W12
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W72
	.byte		N04   , An3 , v080
	.byte		N05   , En4 , v096
	.byte	W12
	.byte		N10   , An3 , v004
	.byte		N11   , En4 , v008
	.byte	W12
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W72
	.byte		N06   , An3 , v076
	.byte		N07   , Dn4 , v088
	.byte	W12
	.byte		N11   , An3 , v004
	.byte		N11   , Dn4 , v012
	.byte	W12
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		TIE   , As3 , v056
	.byte		TIE   , Fn4 
	.byte	W96
	.byte	PEND
	.byte	W88
	.byte		EOT   , As3 
	.byte	W01
	.byte		        Fn4 
	.byte	W07
	.byte		TIE   , Cn4 , v056
	.byte		TIE   , Gn4 
	.byte	W96
	.byte	PEND
	.byte	W88
	.byte		EOT
	.byte	W02
	.byte		EOT   , Cn4 
	.byte	W06
	.byte	PATT
	 .word	fe6_seq_016_2 + 0x44
	.byte	W90
	.byte	W01
	.byte		EOT   , Fn4 
	.byte	W02
	.byte		        As3 
	.byte	W03
	.byte	PATT
	 .word	fe6_seq_016_2 + 0x51
	.byte	W88
	.byte	W01
	.byte		EOT   , Gn4 
	.byte	W01
	.byte		        Cn4 
	.byte	W06
	.byte	PATT
	 .word	fe6_seq_016_2 + 0x44
	.byte	W92
	.byte	W01
	.byte		EOT   , Fn4 
	.byte	W02
	.byte		        As3 
	.byte	W01
	.byte	PATT
	 .word	fe6_seq_016_2 + 0x51
	.byte	W90
	.byte	W01
	.byte		EOT   , Cn4 
	.byte	W01
	.byte		        Gn4 
	.byte	W04
	.byte		TIE   , Bn3 , v056
	.byte		TIE   , Fn4 
	.byte	W96
	.byte	W92
	.byte	W02
	.byte		EOT
	.byte	W01
	.byte		EOT   , Bn3 
	.byte	W01
	.byte		N92   , An3 
	.byte		N90   , En4 
	.byte	W96
	.byte		N10   , An3 
	.byte		N10   , En4 
	.byte	W24
	.byte		N09   , An3 
	.byte		N09   , En4 
	.byte	W24
	.byte		N08   , An3 
	.byte		N09   , En4 
	.byte	W24
	.byte		N08   , An3 
	.byte		N08   , En4 
	.byte	W24
	.byte	GOTO
	 .word	fe6_seq_016_2 + 0x3
	.byte	FINE

@*********************** Track 04 ***********************@

fe6_seq_016_3:
	.byte	KEYSH , fe6_seq_016_key+0
	.byte		VOICE , 48
	.byte		VOL   , 75*fe6_seq_016_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W24
	.byte		N10   , An1 , v088
	.byte		N10   , En2 , v096
	.byte	W12
	.byte		VOICE , 48
	.byte		VOL   , 75*fe6_seq_016_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N10   , An1 , v008
	.byte		N10   , En2 , v016
	.byte	W60
	.byte		N07   , An1 , v088
	.byte		N08   , En2 , v096
	.byte	W24
	.byte		N07   , An1 , v088
	.byte		N08   , En2 , v092
	.byte	W12
	.byte		N07   , An1 , v008
	.byte		N08   , En2 
	.byte	W60
	.byte		N07   , An1 , v088
	.byte		N08   , En2 , v096
	.byte	W24
	.byte		N07   , An1 , v092
	.byte		N08   , En2 , v100
	.byte	W12
	.byte		N07   , An1 , v008
	.byte		N08   , En2 , v020
	.byte	W60
	.byte		        An1 , v088
	.byte		N08   , En2 , v100
	.byte	W24
	.byte		N07   , An1 , v088
	.byte		N08   , En2 , v096
	.byte	W24
	.byte		N07   , An1 , v088
	.byte		N07   , En2 , v096
	.byte	W12
	.byte		        An1 , v008
	.byte		N07   , En2 , v016
	.byte	W36
	.byte		        An1 , v088
	.byte		N07   , En2 , v100
	.byte	W24
	.byte		N06   , An1 , v088
	.byte		N07   , En2 , v096
	.byte	W12
	.byte		N06   , An1 , v008
	.byte		N07   , En2 , v016
	.byte	W60
	.byte		        An1 , v088
	.byte		N07   , En2 , v096
	.byte	W24
	.byte		        An1 , v084
	.byte		N08   , En2 , v100
	.byte	W12
	.byte		N07   , An1 , v004
	.byte		N08   , En2 , v020
	.byte	W60
	.byte		N07   , An1 , v088
	.byte		N07   , En2 , v096
	.byte	W24
	.byte		        An1 , v088
	.byte		N08   , En2 , v096
	.byte	W12
	.byte		N07   , An1 , v008
	.byte		N08   , En2 , v016
	.byte	W60
	.byte		N06   , An1 , v088
	.byte		N07   , En2 , v096
	.byte	W24
	.byte		        An1 , v092
	.byte		N08   , En2 , v096
	.byte	W24
	.byte		N07   , An1 , v088
	.byte		N08   , En2 , v100
	.byte	W12
	.byte		N07   , An1 , v008
	.byte		N08   , En2 , v020
	.byte	W36
	.byte		N09   , An1 , v084
	.byte		N07   , En2 , v100
	.byte	W24
	.byte		N11   , Dn2 , v076
	.byte		N10   , An2 , v084
	.byte	W24
	.byte		        Dn2 , v088
	.byte		N09   , An2 , v092
	.byte	W12
	.byte		N10   , Dn2 , v008
	.byte		N09   , An2 , v012
	.byte	W60
	.byte		        Dn2 , v080
	.byte		N09   , An2 , v088
	.byte	W24
	.byte		        Dn2 , v084
	.byte		N09   , An2 , v088
	.byte	W12
	.byte		        Dn2 , v004
	.byte		N09   , An2 
	.byte	W60
	.byte		        Dn2 , v084
	.byte		N09   , An2 , v092
	.byte	W24
	.byte		        Dn2 , v084
	.byte		N09   , An2 , v092
	.byte	W12
	.byte		        Dn2 , v004
	.byte		N09   , An2 , v012
	.byte	W60
	.byte		N08   , Dn2 , v088
	.byte		N08   , An2 , v096
	.byte	W24
	.byte		N07   , Dn2 , v088
	.byte		N08   , An2 , v096
	.byte	W12
	.byte		N07   , Dn2 , v008
	.byte		N08   , An2 , v016
	.byte	W36
	.byte		N07   , Dn2 , v084
	.byte		N07   , An2 , v096
	.byte	W24
	.byte		N08   , Dn2 , v088
	.byte		N08   , An2 , v096
	.byte	W24
	.byte		        Dn2 , v084
	.byte		N08   , An2 , v092
	.byte	W12
	.byte		        Dn2 , v004
	.byte		N08   , An2 , v012
	.byte	W36
	.byte		N07   , Dn2 , v088
	.byte		N07   , An2 
	.byte	W24
	.byte		N09   , Ds2 , v104
	.byte		N10   , As2 , v096
	.byte	W24
	.byte		N08   , Ds2 , v092
	.byte		N09   , As2 , v096
	.byte	W12
	.byte		N08   , Ds2 , v012
	.byte		N09   , As2 
	.byte	W36
	.byte		N10   , Ds2 , v092
	.byte		N10   , As2 , v096
	.byte	W24
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_016_3 + 0x129
	.byte		N09   , Dn2 , v096
	.byte		N10   , An2 , v088
	.byte	W24
	.byte		N09   , Dn2 , v100
	.byte		N10   , An2 , v092
	.byte	W24
	.byte		N09   , Dn2 , v104
	.byte		N08   , An2 , v088
	.byte	W24
	.byte		N22   , Cn2 , v104
	.byte		N22   , Gn2 
	.byte	W24
	.byte		VOICE , 49
	.byte		N92   , Dn3 , v092
	.byte	W96
	.byte		N32   , As2 , v060
	.byte	W36
	.byte		        Dn3 , v092
	.byte	W36
	.byte		N23   , An3 , v068
	.byte	W24
	.byte		N92   , Gn3 , v084
	.byte	W96
	.byte		        En3 
	.byte	W96
	.byte		        Fn3 , v072
	.byte	W96
	.byte		N32   , As2 , v068
	.byte	W36
	.byte		N28   , Dn3 , v084
	.byte	W30
	.byte		        An3 , v068
	.byte	W30
	.byte		N92   , Gn3 
	.byte	W96
	.byte		        En3 , v080
	.byte	W96
	.byte		        Fn3 , v076
	.byte	W96
	.byte		N32   , Fn3 , v080
	.byte	W36
	.byte		        An3 , v060
	.byte	W36
	.byte		N23   , Fn3 , v084
	.byte	W24
	.byte		N92   , Gn3 , v068
	.byte	W96
	.byte		        En3 , v072
	.byte	W96
	.byte		TIE   , Fn3 
	.byte	W96
	.byte	W32
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N28   , Gn3 , v068
	.byte	W30
	.byte		        Fn3 , v072
	.byte	W30
	.byte		N92   , En3 , v088
	.byte	W96
	.byte		        Cn3 , v068
	.byte	W96
	.byte	GOTO
	 .word	fe6_seq_016_3 + 0x9
	.byte	FINE

@*********************** Track 05 ***********************@

fe6_seq_016_4:
	.byte	KEYSH , fe6_seq_016_key+0
	.byte		VOICE , 33
	.byte		VOL   , 90*fe6_seq_016_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N18   , An2 , v088
	.byte	W24
	.byte		N13   , An2 , v092
	.byte	W24
	.byte		N14
	.byte	W01
	.byte		BEND  , c_v-34
	.byte	W01
	.byte		        c_v+0
	.byte	W22
	.byte		N12   , An2 , v072
	.byte	W24
	.byte		N13   , An2 , v092
	.byte	W24
	.byte		N14   , An2 , v096
	.byte	W24
	.byte		        An2 , v068
	.byte	W24
	.byte		N12   , An2 , v064
	.byte	W24
	.byte		N13   , An2 , v104
	.byte	W24
	.byte		N15
	.byte	W24
	.byte		N13   , An2 , v056
	.byte	W24
	.byte		N12   , An2 , v060
	.byte	W24
	.byte		N13   , An2 , v096
	.byte	W24
	.byte		N12
	.byte	W24
	.byte		N13   , An2 , v064
	.byte	W24
	.byte		N12
	.byte	W24
	.byte		N14   , An2 , v104
	.byte	W24
	.byte		N16
	.byte	W24
	.byte		N15   , An2 , v080
	.byte	W24
	.byte		N11   , An2 , v060
	.byte	W24
	.byte		N14   , An2 , v104
	.byte	W24
	.byte		N14
	.byte	W24
	.byte		N12   , An2 , v096
	.byte	W24
	.byte		        An2 , v088
	.byte	W24
	.byte		        An2 , v104
	.byte	W24
	.byte		N16
	.byte	W24
	.byte		N12   , An2 , v064
	.byte	W24
	.byte		        An2 , v072
	.byte	W24
	.byte		N13   , An2 , v104
	.byte	W24
	.byte		        An2 , v096
	.byte	W24
	.byte		N12   , An2 , v084
	.byte	W24
	.byte		        An2 , v068
	.byte	W24
	.byte		N15   , An2 , v092
	.byte	W24
	.byte		N16   , Dn3 , v100
	.byte	W24
	.byte		N12   , Dn3 , v072
	.byte	W24
	.byte		N11   , Dn3 , v056
	.byte	W24
	.byte		N14   , Dn3 , v092
	.byte	W24
	.byte		N16   , Dn3 , v096
	.byte	W24
	.byte		N12   , Dn3 , v080
	.byte	W24
	.byte		N11
	.byte	W24
	.byte		N15   , Dn3 , v088
	.byte	W24
	.byte		N18   , Dn3 , v100
	.byte	W24
	.byte		N17   , Dn3 , v096
	.byte	W24
	.byte		N12   , Dn3 , v056
	.byte	W24
	.byte		N15   , Dn3 , v096
	.byte	W24
	.byte		N16
	.byte	W24
	.byte		N15
	.byte	W24
	.byte		N12   , Dn3 , v056
	.byte	W24
	.byte		        Dn3 , v068
	.byte	W24
	.byte		N17   , Dn3 , v096
	.byte	W24
	.byte		N15   , Dn3 , v092
	.byte	W24
	.byte		N11   , Dn3 , v064
	.byte	W24
	.byte		N14   , Dn3 , v088
	.byte	W24
	.byte		N16   , Ds3 , v084
	.byte	W24
	.byte		N15
	.byte	W48
	.byte		N14   , Ds3 , v080
	.byte	W24
	.byte		N13   , Ds3 , v084
	.byte	W24
	.byte		N14   , Ds3 , v092
	.byte	W48
	.byte		N15   , Ds3 , v084
	.byte	W24
	.byte		        Dn3 , v104
	.byte	W24
	.byte		N14   , Dn3 , v096
	.byte	W24
	.byte		N12   , Dn3 , v084
	.byte	W24
	.byte		N15   , Cn3 , v092
	.byte	W24
	.byte		N80   , As2 , v084
	.byte	W84
	.byte		N11   , Fn2 , v068
	.byte	W12
	.byte		        As2 , v080
	.byte	W12
	.byte		N13
	.byte	W24
	.byte		N11   , Fn2 , v072
	.byte	W12
	.byte		N23   , As2 , v084
	.byte	W24
	.byte		        Fn2 , v056
	.byte	W24
	.byte		N80   , Cn3 , v088
	.byte	W84
	.byte		N11   , Gn2 , v068
	.byte	W12
	.byte	PEND
	.byte		        Cn3 , v080
	.byte	W12
	.byte		N12   , Cn3 , v088
	.byte	W24
	.byte		N11   , Gn2 , v056
	.byte	W12
	.byte		        Cn3 , v088
	.byte	W12
	.byte		        Dn3 , v084
	.byte	W12
	.byte		N23   , En3 , v080
	.byte	W24
	.byte		N80   , As2 
	.byte	W84
	.byte		N11   , Fn2 
	.byte	W12
	.byte		        As2 , v076
	.byte	W12
	.byte		N12   , As2 , v092
	.byte	W24
	.byte		N11   , Fn2 , v072
	.byte	W12
	.byte		N32   , As2 , v088
	.byte	W36
	.byte		N11   , Fn2 , v072
	.byte	W12
	.byte	PATT
	 .word	fe6_seq_016_4 + 0x103
	.byte		N11   , Cn3 , v088
	.byte	W12
	.byte		N12
	.byte	W24
	.byte		N11   , Gn2 , v060
	.byte	W12
	.byte		N23   , Cn3 , v088
	.byte	W24
	.byte		        Gn2 , v056
	.byte	W24
	.byte		N80   , As2 , v076
	.byte	W84
	.byte		N11   , Fn2 , v080
	.byte	W12
	.byte		        As2 , v076
	.byte	W12
	.byte		N13   , As2 , v072
	.byte	W24
	.byte		N11   , Fn2 , v060
	.byte	W12
	.byte		N32   , As2 , v092
	.byte	W36
	.byte		N11   , Fn2 , v056
	.byte	W12
	.byte		N56   , Cn3 , v092
	.byte	W60
	.byte		N16   , Cn3 , v084
	.byte	W24
	.byte		N11   , Gn2 , v068
	.byte	W12
	.byte		N32   , Cn3 , v080
	.byte	W36
	.byte		N11   , Gn2 , v056
	.byte	W12
	.byte		N23   , Cn3 
	.byte	W24
	.byte		N11   , Dn3 
	.byte	W12
	.byte		        En3 , v076
	.byte	W12
	.byte		N54   , Bn2 , v064
	.byte	W60
	.byte		N14   , Bn2 , v076
	.byte	W24
	.byte		N11   , Fn2 , v068
	.byte	W12
	.byte		N54   , Bn2 , v084
	.byte	W60
	.byte		N23   , Bn2 , v072
	.byte	W24
	.byte		N11   , Fn2 , v064
	.byte	W12
	.byte		N32   , An2 , v080
	.byte	W36
	.byte		N44   , An2 , v076
	.byte	W48
	.byte		N11   , En2 , v056
	.byte	W12
	.byte		        An2 , v068
	.byte	W12
	.byte		N11
	.byte	W12
	.byte		N19   , En2 , v056
	.byte	W24
	.byte		N11   , An2 , v076
	.byte	W12
	.byte		        En2 , v056
	.byte	W12
	.byte		        An2 , v080
	.byte	W12
	.byte		        En2 , v064
	.byte	W12
	.byte	GOTO
	 .word	fe6_seq_016_4 + 0xC
	.byte	FINE

@*********************** Track 06 ***********************@

fe6_seq_016_5:
	.byte	KEYSH , fe6_seq_016_key+0
	.byte		VOICE , 127
	.byte		VOL   , 90*fe6_seq_016_mvl/mxv
	.byte		PAN   , c_v-4
	.byte	W24
	.byte		N22   , Cn1 , v112
	.byte	W72
	.byte		N21   , Cn1 , v096
	.byte	W24
	.byte		N21   , Cn1 , v112
	.byte	W72
	.byte		        Cn1 , v104
	.byte	W24
	.byte	PEND
	.byte		        Cn1 , v108
	.byte	W72
	.byte		        Cn1 , v100
	.byte	W24
	.byte		        Cn1 , v104
	.byte	W24
	.byte		N22   , Cn1 , v112
	.byte	W48
	.byte		N21   , Fn1 
	.byte	W24
	.byte		        Cn1 , v104
	.byte	W72
	.byte		N21
	.byte	W24
	.byte		        Cn1 , v108
	.byte	W72
	.byte		N21
	.byte	W24
	.byte	PATT
	 .word	fe6_seq_016_5 + 0x11
	.byte		N21   , Cn1 , v104
	.byte	W24
	.byte		N21
	.byte	W48
	.byte		N22   , Fn1 , v112
	.byte	W24
	.byte		N21   , Cn1 , v100
	.byte	W24
	.byte		        Cn1 , v112
	.byte	W72
	.byte		N21   , Cn1 , v104
	.byte	W24
	.byte		N21
	.byte	W72
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_016_5 + 0x49
	.byte		N21   , Cn1 , v096
	.byte	W24
	.byte		        Cn1 , v108
	.byte	W48
	.byte		N22   , Fn1 , v112
	.byte	W24
	.byte		        Cn1 , v104
	.byte	W24
	.byte		N21   , Cn1 , v100
	.byte	W48
	.byte		        Cn1 , v092
	.byte	W24
	.byte		N21
	.byte	W24
	.byte		N20   , Cn1 , v088
	.byte	W48
	.byte		N21   , Cn1 , v084
	.byte	W24
	.byte		N21
	.byte	W24
	.byte		N22   , Cn1 , v088
	.byte	W48
	.byte		N23   , Cn1 , v084
	.byte	W24
	.byte		N21   , Cn1 , v072
	.byte	W24
	.byte		        Cn1 , v064
	.byte	W72
	.byte		N30   , Cn1 , v108
	.byte	W36
	.byte		N11   , Cn1 , v092
	.byte	W12
	.byte		N23   , Cn1 , v104
	.byte	W24
	.byte		        Dn1 , v084
	.byte	W24
	.byte		N11   , Cn1 , v112
	.byte	W12
	.byte		N22   , Cn1 , v092
	.byte	W24
	.byte		N11   , Cn1 , v104
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		N22   , Dn1 
	.byte	W24
	.byte		N23   , Cn1 , v112
	.byte	W36
	.byte		N11   , Cn1 , v104
	.byte	W12
	.byte		N24   , Dn1 , v112
	.byte	W48
	.byte		N11   , Cn1 , v108
	.byte	W12
	.byte		N23   , Cn1 , v088
	.byte	W24
	.byte		N11   , Cn1 , v100
	.byte	W12
	.byte		N24   , Dn1 , v104
	.byte	W48
	.byte		        Cn1 , v080
	.byte	W36
	.byte		N11   , Cn1 , v064
	.byte	W12
	.byte		N36   , Cn1 , v068
	.byte	W48
	.byte		N11   , Cn1 , v104
	.byte	W12
	.byte		N23   , Cn1 , v076
	.byte	W24
	.byte		N11   , Cn1 , v100
	.byte	W12
	.byte		N23   , Cn1 , v096
	.byte	W24
	.byte		        Dn1 
	.byte	W24
	.byte		N24   , Cn1 , v104
	.byte	W36
	.byte		N11   , Cn1 , v044
	.byte	W12
	.byte		N23   , Cn1 , v092
	.byte	W24
	.byte		        Dn1 
	.byte	W24
	.byte		N24   , Cn1 , v088
	.byte	W36
	.byte		N11
	.byte	W12
	.byte		N23   , Cn1 , v100
	.byte	W24
	.byte		        Dn1 , v104
	.byte	W24
	.byte		N28   , Cn1 , v112
	.byte	W36
	.byte		N11   , Cn1 , v084
	.byte	W12
	.byte		N23   , Cn1 , v096
	.byte	W24
	.byte		        Dn1 
	.byte	W24
	.byte		N24   , Cn1 , v104
	.byte	W36
	.byte		N11   , Cn1 , v100
	.byte	W12
	.byte		N23   , Dn1 , v104
	.byte	W24
	.byte		        Dn1 , v092
	.byte	W24
	.byte		N28   , Cn1 , v112
	.byte	W36
	.byte		N11   , Cn1 , v088
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		N22   , Dn1 , v108
	.byte	W24
	.byte		N11   , Cn1 , v104
	.byte	W12
	.byte		N23   , Cn1 , v084
	.byte	W24
	.byte		N11   , Cn1 , v104
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		        Dn1 , v112
	.byte	W24
	.byte		N24   , Cn1 , v104
	.byte	W36
	.byte		N11   , Cn1 , v092
	.byte	W12
	.byte		N23   , Cn1 , v104
	.byte	W24
	.byte		        Dn1 , v100
	.byte	W24
	.byte		N22   , Cn1 , v088
	.byte	W36
	.byte		N11   , Cn1 , v096
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		        Dn1 , v112
	.byte	W24
	.byte		        Cn1 
	.byte	W36
	.byte		N11   , Cn1 , v100
	.byte	W12
	.byte		N24   , Cn1 , v092
	.byte	W36
	.byte		N11   , Cn1 , v076
	.byte	W12
	.byte		N23   , Cn1 , v104
	.byte	W24
	.byte		N22   , Cn1 , v112
	.byte	W24
	.byte		N23
	.byte	W24
	.byte		        Cs2 , v080
	.byte	W24
	.byte	GOTO
	 .word	fe6_seq_016_5 + 0x9
	.byte	FINE

@******************************************************@

	.align	2

fe6_seq_016:
	.byte	6	@ NumTrks
	.byte	0	@ NumBlks
	.byte	fe6_seq_016_pri	@ Priority
	.byte	fe6_seq_016_rev	@ Reverb

	.word	fe6_seq_016_grp

	.word	fe6_seq_016_0
	.word	fe6_seq_016_1
	.word	fe6_seq_016_2
	.word	fe6_seq_016_3
	.word	fe6_seq_016_4
	.word	fe6_seq_016_5

	.end
