@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	fe6_seq_011_grp, native_instrument_map_bin
	.equ	fe6_seq_011_pri, 10
	.equ	fe6_seq_011_rev, 158
	.equ	fe6_seq_011_mvl, 127
	.equ	fe6_seq_011_key, 0

	.section .rodata
	.global	fe6_seq_011
	.align	2

@*********************** Track 01 ***********************@

fe6_seq_011_0:
	.byte	KEYSH , fe6_seq_011_key+0
	.byte	TEMPO , 120/2
	.byte	W24
	.byte		VOICE , 1
	.byte		VOL   , 103*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v+9
	.byte		N28   , Fn2 , v104
	.byte		N28   , As2 , v100
	.byte	W36
	.byte		N11   , Gs2 , v088
	.byte		N11   , Cn3 , v100
	.byte	W12
	.byte		N48   , As2 , v092
	.byte		N48   , Cs3 , v084
	.byte	W48
	.byte	W24
	.byte		N10   , Gs2 , v076
	.byte		N11   , Cn3 , v108
	.byte	W12
	.byte		        As2 , v092
	.byte		N11   , Cs3 , v084
	.byte	W12
	.byte		N19   , Cn3 , v104
	.byte		N23   , Ds3 , v080
	.byte	W24
	.byte		        Gs2 
	.byte		N21   , Cn3 , v112
	.byte	W24
	.byte		N92   , Cn3 , v108
	.byte		N92   , Fn3 , v104
	.byte	W96
	.byte		VOICE , 48
	.byte		VOL   , 82*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v+4
	.byte		N05   , As2 , v072
	.byte	W06
	.byte		N04   , Cn3 , v088
	.byte	W06
	.byte		N05   , As2 , v068
	.byte	W06
	.byte		        Cn3 , v084
	.byte	W06
	.byte		N68   , Cs3 , v080
	.byte	W72
	.byte		VOICE , 1
	.byte		VOL   , 103*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v+9
	.byte		N32   , Fn2 , v088
	.byte		N32   , As2 , v092
	.byte	W36
	.byte		N11   , Gs2 , v080
	.byte		N10   , Cn3 , v100
	.byte	W12
	.byte		N48   , As2 , v088
	.byte		N48   , Cs3 , v084
	.byte	W48
	.byte	W24
	.byte		N11   , Gs2 , v080
	.byte		N10   , Cn3 , v108
	.byte	W12
	.byte		N11   , As2 , v084
	.byte		N11   , Cs3 
	.byte	W12
	.byte		N21   , Cn3 , v072
	.byte		N21   , Ds3 , v092
	.byte	W24
	.byte		N23   , Cs3 , v060
	.byte		N23   , Fn3 , v096
	.byte	W24
	.byte		N44   , As2 , v084
	.byte		N44   , Cs3 , v056
	.byte	W48
	.byte		VOICE , 48
	.byte		VOL   , 82*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v+4
	.byte		N44   , As3 , v096
	.byte	W48
	.byte		        Gs3 , v088
	.byte	W48
	.byte		N36   , Fs3 , v084
	.byte	W48
	.byte		N32   , Fn3 , v108
	.byte	W36
	.byte		N05   , Ds3 , v092
	.byte	W06
	.byte		        Dn3 , v104
	.byte	W06
	.byte		N60   , As2 , v084
	.byte	W48
	.byte	W24
	.byte		N09   , As2 , v104
	.byte	W12
	.byte		N11   , Cn3 
	.byte	W12
	.byte		N23   , Cs3 , v096
	.byte	W24
	.byte		N22   , Ds3 , v084
	.byte	W24
	.byte		N44   , Fn3 , v104
	.byte	W48
	.byte		        As3 
	.byte	W48
	.byte		N88   , Fn3 , v092
	.byte	W96
	.byte		VOICE , 1
	.byte		VOL   , 103*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v+9
	.byte		N32   , Fn3 , v108
	.byte	W36
	.byte		N05   , Ds3 , v080
	.byte	W06
	.byte		        Cs3 , v084
	.byte	W06
	.byte		N68   , As2 
	.byte	W48
	.byte	W24
	.byte		N11   , As2 , v088
	.byte	W12
	.byte		        Cn3 , v096
	.byte	W12
	.byte		N23   , Cs3 
	.byte	W24
	.byte		        Ds3 , v088
	.byte	W24
	.byte		N44   , Fn3 , v096
	.byte	W48
	.byte		        As3 , v104
	.byte	W48
	.byte		        As3 , v100
	.byte	W48
	.byte		        An3 , v096
	.byte	W24
	.byte		VOICE , 1
	.byte		VOL   , 103*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v+9
	.byte	W24
	.byte		N44   , As3 , v076
	.byte	W48
	.byte		N92   , Gs3 , v088
	.byte	W48
	.byte	W48
	.byte		N21   , Fn3 , v100
	.byte	W24
	.byte		N20   , Fs3 
	.byte	W24
	.byte		N44   , Gs3 
	.byte	W48
	.byte		        Fs3 
	.byte	W48
	.byte		N80   , Fn3 
	.byte	W96
	.byte		N44   , Cn3 , v092
	.byte	W48
	.byte		N68   , Ds3 , v080
	.byte	W48
	.byte	W24
	.byte		N22   , Cs3 
	.byte	W24
	.byte		N23   , Ds3 
	.byte	W24
	.byte		N21   , Fn3 , v100
	.byte	W24
	.byte		N44   , Cn3 , v108
	.byte	W48
	.byte		N68   , Ds3 , v084
	.byte	W48
	.byte	W24
	.byte		N22   , Cs3 , v092
	.byte	W24
	.byte		N23   , Gs3 , v096
	.byte	W24
	.byte		        Fs3 , v100
	.byte	W24
	.byte		N92   , Fn3 , v104
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	fe6_seq_011_0 + 0x5
	.byte	FINE

@*********************** Track 02 ***********************@

fe6_seq_011_1:
	.byte	KEYSH , fe6_seq_011_key+0
	.byte	W24
	.byte		VOICE , 68
	.byte		MOD   , 0
	.byte		VOL   , 37*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v+1
	.byte		BEND  , c_v-3
	.byte		TIE   , As2 , v072
	.byte	W96
	.byte	W23
	.byte		EOT
	.byte	W01
	.byte		N23   , Cn3 
	.byte	W24
	.byte		        Cs3 
	.byte	W24
	.byte		        Ds3 
	.byte	W24
	.byte		N44   , Fn3 , v072
	.byte	W48
	.byte		        As3 , v068
	.byte	W48
	.byte	PEND
	.byte		N44   , Ds4 , v068
	.byte	W48
	.byte		        Cn4 
	.byte	W48
	.byte	PEND
	.byte		TIE   , As2 , v072
	.byte	W96
	.byte	W23
	.byte		EOT
	.byte	W01
	.byte		N23   , Cn3 
	.byte	W24
	.byte		        Cs3 
	.byte	W24
	.byte		        Ds3 
	.byte	W24
	.byte	PATT
	 .word	fe6_seq_011_1 + 0x1B
	.byte	PATT
	 .word	fe6_seq_011_1 + 0x23
	.byte		N92   , As3 , v068
	.byte	W96
	.byte		N32   , Ds4 
	.byte	W36
	.byte		N05   , Cs4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		N23   , As3 
	.byte	W24
	.byte		        Gs3 
	.byte	W24
	.byte		N92   , As3 
	.byte	W96
	.byte	PATT
	 .word	fe6_seq_011_1 + 0x23
	.byte		N92   , As3 , v068
	.byte	W96
	.byte		N44   , Gs3 
	.byte	W48
	.byte		        As3 
	.byte	W48
	.byte		        Fn3 , v072
	.byte	W48
	.byte		        Ds3 
	.byte	W48
	.byte		        Cs3 
	.byte	W48
	.byte		        Cn3 
	.byte	W48
	.byte		VOICE , 48
	.byte		VOL   , 82*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v+4
	.byte		N44   , Cs3 , v088
	.byte	W48
	.byte		N88   , Cn3 , v092
	.byte	W48
	.byte	W48
	.byte		N20   , As2 , v060
	.byte	W24
	.byte		N22   , Cn3 
	.byte	W24
	.byte		N44   , Cs3 , v052
	.byte	W48
	.byte		        Cn3 , v084
	.byte	W48
	.byte		N76   , As2 , v076
	.byte	W96
	.byte		N44   , Fn2 , v068
	.byte	W48
	.byte		N68   , Gs2 , v088
	.byte	W48
	.byte	W24
	.byte		N22   , Fs2 , v080
	.byte	W24
	.byte		N23   , Gs2 , v092
	.byte	W24
	.byte		N21   , As2 , v076
	.byte	W24
	.byte		N44   , Fn2 
	.byte	W48
	.byte		N68   , Gs2 , v092
	.byte	W48
	.byte	W24
	.byte		N21   , Fs2 , v076
	.byte	W24
	.byte		N16   , Cn3 , v080
	.byte	W24
	.byte		N17   , As2 , v072
	.byte	W24
	.byte		N92   , Gs2 , v084
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	fe6_seq_011_1 + 0x3
	.byte	FINE

@*********************** Track 03 ***********************@

fe6_seq_011_2:
	.byte	KEYSH , fe6_seq_011_key+0
	.byte	W24
	.byte		VOICE , 68
	.byte		MOD   , 2
	.byte		VOL   , 41*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v+1
	.byte		TIE   , As2 , v076
	.byte	W96
	.byte	W23
	.byte		EOT
	.byte	W01
	.byte		N23   , Cn3 
	.byte	W24
	.byte		        Cs3 
	.byte	W24
	.byte		        Ds3 
	.byte	W24
	.byte		N44   , Fn3 , v076
	.byte	W48
	.byte		        As3 , v072
	.byte	W48
	.byte	PEND
	.byte		N44   , Ds4 , v064
	.byte	W48
	.byte		        Cn4 , v072
	.byte	W48
	.byte	PEND
	.byte		TIE   , As2 , v076
	.byte	W96
	.byte	W22
	.byte		EOT
	.byte	W02
	.byte		N23   , Cn3 
	.byte	W24
	.byte		        Cs3 
	.byte	W24
	.byte		        Ds3 
	.byte	W24
	.byte	PATT
	 .word	fe6_seq_011_2 + 0x19
	.byte	PATT
	 .word	fe6_seq_011_2 + 0x21
	.byte		N88   , As3 , v072
	.byte	W96
	.byte		N32   , Ds4 
	.byte	W36
	.byte		N05   , Cs4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		N23   , As3 
	.byte	W24
	.byte		        Gs3 
	.byte	W24
	.byte		N92   , As3 
	.byte	W96
	.byte		N44   , Ds4 
	.byte	W48
	.byte		        Cn4 
	.byte	W48
	.byte		N92   , As3 
	.byte	W96
	.byte		N44   , Gs3 
	.byte	W48
	.byte		        As3 
	.byte	W48
	.byte		        Fn3 , v076
	.byte	W48
	.byte		        Ds3 
	.byte	W48
	.byte		        Cs3 
	.byte	W48
	.byte		        Cn3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	fe6_seq_011_2 + 0x3
	.byte	FINE

@*********************** Track 04 ***********************@

fe6_seq_011_3:
	.byte	KEYSH , fe6_seq_011_key+0
	.byte	W24
	.byte		VOICE , 1
	.byte		VOL   , 86*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v-20
	.byte		TIE   , As1 , v108
	.byte	W96
	.byte	W96
	.byte	W36
	.byte	W02
	.byte		EOT
	.byte	W10
	.byte		N44   , As1 , v120
	.byte	W48
	.byte		        Fn2 
	.byte	W48
	.byte		        As2 , v108
	.byte	W48
	.byte		TIE   , As1 , v112
	.byte	W96
	.byte	W96
	.byte	W16
	.byte		EOT
	.byte	W08
	.byte		N23   , As1 , v120
	.byte	W24
	.byte		        Fn2 
	.byte	W24
	.byte		        As2 , v100
	.byte	W24
	.byte		N44   , Cs3 , v108
	.byte	W48
	.byte		        As2 , v104
	.byte	W48
	.byte		TIE   , Gs2 , v100
	.byte	W96
	.byte	W92
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		TIE   , Fs2 , v112
	.byte	W96
	.byte	W92
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		TIE   , Gs2 , v104
	.byte	W96
	.byte	W88
	.byte	W01
	.byte		EOT
	.byte	W07
	.byte		TIE   , Fs2 , v100
	.byte	W96
	.byte	W44
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N44   , Fn2 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		TIE   , As1 , v120
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W92
	.byte	W01
	.byte		EOT
	.byte	W03
	.byte		N92   , Fn1 , v100
	.byte	W96
	.byte	GOTO
	 .word	fe6_seq_011_3 + 0x3
	.byte	FINE

@*********************** Track 05 ***********************@

fe6_seq_011_4:
	.byte	KEYSH , fe6_seq_011_key+0
	.byte	W24
	.byte		VOICE , 58
	.byte		VOL   , 99*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v-3
	.byte		N08   , Fn3 , v100
	.byte	W12
	.byte		        Fn3 , v028
	.byte	W24
	.byte		        Fn3 , v104
	.byte	W12
	.byte		        Fn3 , v032
	.byte	W12
	.byte		N05   , Fn3 , v096
	.byte	W06
	.byte		        Fn3 , v024
	.byte	W06
	.byte		N17   , Fn3 , v104
	.byte	W18
	.byte		N04   , Fn3 , v032
	.byte	W06
	.byte		N08   , Fn3 , v100
	.byte	W12
	.byte		        Fn3 , v028
	.byte	W24
	.byte		        Fn3 , v104
	.byte	W12
	.byte		        Fn3 , v032
	.byte	W12
	.byte		N05   , Fn3 , v096
	.byte	W06
	.byte		        Fn3 , v024
	.byte	W06
	.byte		N17   , Fn3 , v104
	.byte	W18
	.byte		N04   , Fn3 , v032
	.byte	W06
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x25
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x25
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x25
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x25
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x25
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x25
	.byte		N08   , Ds3 , v100
	.byte	W12
	.byte		        Ds3 , v028
	.byte	W24
	.byte		        Ds3 , v104
	.byte	W12
	.byte		        Ds3 , v032
	.byte	W12
	.byte		N05   , Ds3 , v096
	.byte	W06
	.byte		        Ds3 , v024
	.byte	W06
	.byte		N17   , Ds3 , v104
	.byte	W18
	.byte		N04   , Ds3 , v032
	.byte	W06
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x60
	.byte		N08   , Cs3 , v100
	.byte	W12
	.byte		        Cs3 , v028
	.byte	W24
	.byte		        Cs3 , v104
	.byte	W12
	.byte		        Cs3 , v032
	.byte	W12
	.byte		N05   , Cs3 , v096
	.byte	W06
	.byte		        Cs3 , v024
	.byte	W06
	.byte		N17   , Cs3 , v104
	.byte	W18
	.byte		N04   , Cs3 , v032
	.byte	W06
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x82
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x60
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x60
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x82
	.byte		N08   , Cs3 , v100
	.byte	W12
	.byte		        Cs3 , v028
	.byte	W24
	.byte		        Cs3 , v104
	.byte	W12
	.byte		        Cs3 , v032
	.byte	W12
	.byte		N05   , Cn3 , v096
	.byte	W06
	.byte		        Cn3 , v024
	.byte	W06
	.byte		N17   , Cn3 , v104
	.byte	W18
	.byte		N04   , Cn3 , v032
	.byte	W06
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x25
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x25
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x25
	.byte	PATT
	 .word	fe6_seq_011_4 + 0x25
	.byte		N08   , Cn3 , v100
	.byte	W12
	.byte		        Cn3 , v028
	.byte	W24
	.byte		        Cn3 , v104
	.byte	W12
	.byte		        Cn3 , v032
	.byte	W12
	.byte		N05   , Cn3 , v096
	.byte	W06
	.byte		        Cn3 , v024
	.byte	W06
	.byte		N17   , Cn3 , v104
	.byte	W18
	.byte		N04   , Cn3 , v032
	.byte	W06
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_011_4 + 0xE3
	.byte	PATT
	 .word	fe6_seq_011_4 + 0xE3
	.byte	PATT
	 .word	fe6_seq_011_4 + 0xE3
	.byte	PATT
	 .word	fe6_seq_011_4 + 0xE3
	.byte	PATT
	 .word	fe6_seq_011_4 + 0xE3
	.byte	GOTO
	 .word	fe6_seq_011_4 + 0x3
	.byte	FINE

@*********************** Track 06 ***********************@

fe6_seq_011_5:
	.byte	KEYSH , fe6_seq_011_key+0
	.byte		VOICE , 127
	.byte		VOL   , 86*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v-4
	.byte	W24
	.byte		N11   , Dn1 , v120
	.byte	W12
	.byte		        Dn1 , v076
	.byte	W12
	.byte		        Dn1 , v072
	.byte	W12
	.byte		        Dn1 , v120
	.byte	W12
	.byte		        Dn1 , v056
	.byte	W12
	.byte		        Dn1 , v060
	.byte	W12
	.byte		        Dn1 , v120
	.byte	W12
	.byte		        Dn1 , v076
	.byte	W12
	.byte	PEND
	.byte		        Dn1 , v120
	.byte	W12
	.byte		        Dn1 , v076
	.byte	W12
	.byte		        Dn1 , v072
	.byte	W12
	.byte		        Dn1 , v120
	.byte	W12
	.byte		        Dn1 , v084
	.byte	W12
	.byte		        Dn1 , v076
	.byte	W12
	.byte		        Dn1 , v124
	.byte	W12
	.byte		        Dn1 , v052
	.byte	W12
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte		N17   , Dn1 , v080
	.byte	W18
	.byte		N05   , Dn1 , v048
	.byte	W06
	.byte		N11   , Dn1 , v068
	.byte	W12
	.byte		        Dn1 , v096
	.byte	W12
	.byte		        Dn1 , v048
	.byte	W12
	.byte		        Dn1 , v072
	.byte	W12
	.byte		        Dn1 , v088
	.byte	W12
	.byte		        Dn1 , v056
	.byte	W12
	.byte		        Dn1 , v088
	.byte	W12
	.byte		        Dn1 , v040
	.byte	W12
	.byte		        Dn1 , v072
	.byte	W12
	.byte		N23   , Dn1 , v096
	.byte	W24
	.byte		N11   , Dn1 , v072
	.byte	W12
	.byte		N11
	.byte	W12
	.byte		        Dn1 , v052
	.byte	W12
	.byte		        Dn1 , v044
	.byte	W12
	.byte		N22   , Dn1 , v060
	.byte	W24
	.byte		N11   , Dn1 , v092
	.byte	W12
	.byte		        Dn1 , v060
	.byte	W12
	.byte		        Dn1 , v084
	.byte	W12
	.byte		N11
	.byte	W12
	.byte		        Dn1 , v068
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		N24   , Dn1 , v056
	.byte	W36
	.byte		N11   , Dn1 , v044
	.byte	W12
	.byte		        Dn1 , v068
	.byte	W12
	.byte		        Dn1 , v064
	.byte	W12
	.byte		        Dn1 , v104
	.byte	W12
	.byte		        Dn1 , v036
	.byte	W12
	.byte		        Dn1 , v060
	.byte	W12
	.byte		        Dn1 , v088
	.byte	W12
	.byte		        Dn1 , v064
	.byte	W12
	.byte		        Dn1 , v060
	.byte	W12
	.byte		N22   , Dn1 , v112
	.byte	W24
	.byte		N11   , Dn1 , v108
	.byte	W12
	.byte		        Dn1 , v076
	.byte	W12
	.byte		        Dn1 , v064
	.byte	W12
	.byte		        Dn1 , v088
	.byte	W12
	.byte		N20   , Dn1 , v044
	.byte	W24
	.byte		N11   , Dn1 , v096
	.byte	W12
	.byte		        Dn1 , v052
	.byte	W12
	.byte		        Dn1 , v088
	.byte	W12
	.byte		        Dn1 , v052
	.byte	W12
	.byte		        Dn1 , v060
	.byte	W12
	.byte		        Dn1 , v056
	.byte	W12
	.byte		        Dn1 , v060
	.byte	W12
	.byte		        Dn1 , v080
	.byte	W12
	.byte		        Dn1 , v084
	.byte	W12
	.byte		N11
	.byte	W12
	.byte		N23   , Dn1 , v100
	.byte	W24
	.byte		N11   , Dn1 , v060
	.byte	W12
	.byte		        Dn1 , v112
	.byte	W12
	.byte		N23   , Dn1 , v072
	.byte	W24
	.byte		N11   , Dn1 , v104
	.byte	W12
	.byte		        Dn1 , v060
	.byte	W12
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte		N22   , Dn1 , v116
	.byte	W24
	.byte		N11   , Dn1 , v060
	.byte	W12
	.byte		N22   , Dn1 , v116
	.byte	W24
	.byte		N11   , Dn1 , v084
	.byte	W12
	.byte		        Dn1 , v112
	.byte	W12
	.byte		        Dn1 , v084
	.byte	W12
	.byte		        Dn1 , v112
	.byte	W12
	.byte		        Dn1 , v044
	.byte	W12
	.byte		        Dn1 , v076
	.byte	W12
	.byte		N22   , Dn1 , v112
	.byte	W24
	.byte		N11   , Dn1 , v080
	.byte	W12
	.byte		        Dn1 , v116
	.byte	W12
	.byte		        Dn1 , v056
	.byte	W12
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte		N22   , Dn1 , v112
	.byte	W24
	.byte		N11   , Dn1 , v084
	.byte	W12
	.byte		        Dn1 , v112
	.byte	W12
	.byte		        Dn1 , v072
	.byte	W12
	.byte		        Dn1 , v080
	.byte	W12
	.byte		        Dn1 , v116
	.byte	W12
	.byte		        Dn1 , v084
	.byte	W12
	.byte	PATT
	 .word	fe6_seq_011_5 + 0x9
	.byte	GOTO
	 .word	fe6_seq_011_5 + 0x9
	.byte	FINE

@*********************** Track 07 ***********************@

fe6_seq_011_6:
	.byte	KEYSH , fe6_seq_011_key+0
	.byte		VOICE , 127
	.byte		VOL   , 86*fe6_seq_011_mvl/mxv
	.byte		PAN   , c_v-4
	.byte	W12
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		N36   , Gn1 , v127
	.byte	W72
	.byte		N11   , Gn1 , v124
	.byte	W12
	.byte		        Fn1 
	.byte	W12
	.byte		N42   , Gn1 , v127
	.byte	W84
	.byte		N11   , Fn1 , v120
	.byte	W12
	.byte		N32   , Gn1 , v124
	.byte	W36
	.byte		N40   , Gn1 , v120
	.byte	W48
	.byte		N11   , Fn1 
	.byte	W12
	.byte		N40   , Gn1 , v124
	.byte	W84
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		N32   , Gn1 , v127
	.byte	W36
	.byte		N40   , Gn1 , v124
	.byte	W48
	.byte		N11   , Fn1 
	.byte	W12
	.byte		N42   , Gn1 
	.byte	W72
	.byte		N11   , Gn1 , v120
	.byte	W12
	.byte		        Fn1 , v100
	.byte	W12
	.byte		N32   , Gn1 , v127
	.byte	W36
	.byte		N36
	.byte	W60
	.byte	W84
	.byte		N11   , Fn1 , v104
	.byte	W12
	.byte		N32   , Gn1 , v127
	.byte	W36
	.byte		        Gn1 , v120
	.byte	W36
	.byte		N11   , Gn1 , v112
	.byte	W12
	.byte		        Fn1 , v116
	.byte	W12
	.byte		N32   , Gn1 , v124
	.byte	W36
	.byte		N23   , Gn1 , v116
	.byte	W24
	.byte		        Gn1 , v124
	.byte	W24
	.byte		N11   , Fn1 
	.byte	W12
	.byte		N32   , Gn1 
	.byte	W36
	.byte		N32
	.byte	W36
	.byte		N11   , Gn1 , v127
	.byte	W12
	.byte		        Fn1 , v116
	.byte	W12
	.byte		N32   , Gn1 , v127
	.byte	W36
	.byte		        Gn1 , v124
	.byte	W36
	.byte		N11   , Gn1 , v127
	.byte	W12
	.byte		        Fn1 , v120
	.byte	W12
	.byte		N32   , Gn1 , v127
	.byte	W36
	.byte		N32
	.byte	W36
	.byte		N11   , Gn1 , v120
	.byte	W12
	.byte		        Fn1 , v127
	.byte	W12
	.byte		N32   , Gn1 
	.byte	W36
	.byte		N32
	.byte	W36
	.byte		N11   , Gn1 , v124
	.byte	W12
	.byte		        Fn1 , v120
	.byte	W12
	.byte		        Gn1 , v124
	.byte	W12
	.byte		        Fn1 , v092
	.byte	W12
	.byte		        Gn1 
	.byte	W12
	.byte		        Fn1 , v080
	.byte	W12
	.byte		        Gn1 , v100
	.byte	W12
	.byte		        Fn1 
	.byte	W12
	.byte		        Gn1 , v120
	.byte	W12
	.byte		        Fn1 , v104
	.byte	W12
	.byte		        Gn1 , v127
	.byte	W12
	.byte		        Fn1 , v116
	.byte	W12
	.byte		        Gn1 , v127
	.byte	W12
	.byte		        Fn1 , v124
	.byte	W12
	.byte		        Gn1 , v127
	.byte	W12
	.byte		        Fn1 
	.byte	W12
	.byte		        Gn1 
	.byte	W12
	.byte		        Fn1 
	.byte	W12
	.byte		N32   , An2 , v116
	.byte	W36
	.byte		N36   , An2 , v108
	.byte	W60
	.byte		N32   , An2 , v112
	.byte	W36
	.byte		N40   , An2 , v100
	.byte	W60
	.byte		N32
	.byte	W36
	.byte		N40   , An2 , v116
	.byte	W60
	.byte		N32   , An2 , v104
	.byte	W36
	.byte		N28   , An2 , v108
	.byte	W30
	.byte		N05   , An2 , v056
	.byte	W06
	.byte		        An2 , v072
	.byte	W06
	.byte		        An2 , v064
	.byte	W06
	.byte		N11   , An2 , v080
	.byte	W12
	.byte		N40   , An2 , v100
	.byte	W84
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		N40   , Gn1 , v127
	.byte	W72
	.byte		N23   , Gn1 , v108
	.byte	W24
	.byte		N36   , Fn1 , v127
	.byte	W84
	.byte		N11   , Fn1 , v124
	.byte	W12
	.byte		N36   , Gn1 , v127
	.byte	W72
	.byte		N23   , Gn1 , v116
	.byte	W24
	.byte		N36   , Fn1 , v127
	.byte	W84
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		N36   , Gn1 , v127
	.byte	W84
	.byte		N11   , Fn1 , v120
	.byte	W12
	.byte	GOTO
	 .word	fe6_seq_011_6 + 0xD
	.byte	FINE

@******************************************************@

	.align	2

fe6_seq_011:
	.byte	7	@ NumTrks
	.byte	0	@ NumBlks
	.byte	fe6_seq_011_pri	@ Priority
	.byte	fe6_seq_011_rev	@ Reverb

	.word	fe6_seq_011_grp

	.word	fe6_seq_011_0
	.word	fe6_seq_011_1
	.word	fe6_seq_011_2
	.word	fe6_seq_011_3
	.word	fe6_seq_011_4
	.word	fe6_seq_011_5
	.word	fe6_seq_011_6

	.end
