@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	fe6_seq_012_grp, native_instrument_map_bin
	.equ	fe6_seq_012_pri, 10
	.equ	fe6_seq_012_rev, 158
	.equ	fe6_seq_012_mvl, 127
	.equ	fe6_seq_012_key, 0

	.section .rodata
	.global	fe6_seq_012
	.align	2

@*********************** Track 01 ***********************@

fe6_seq_012_0:
	.byte	KEYSH , fe6_seq_012_key+0
	.byte	TEMPO , 112/2
	.byte		VOICE , 2
	.byte		VOL   , 97*fe6_seq_012_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N03   , Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Cn3 
	.byte	W04
	.byte		        Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Cn3 
	.byte	W04
	.byte		        Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Cn3 
	.byte	W04
	.byte		        Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Cn3 
	.byte	W04
	.byte		N03   , Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Bn2 
	.byte	W04
	.byte		        Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Bn2 
	.byte	W04
	.byte		        Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Bn2 
	.byte	W04
	.byte		        Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Bn2 
	.byte	W04
	.byte	PEND
	.byte		N03   , Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Cn3 
	.byte	W04
	.byte		        Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Cn3 
	.byte	W04
	.byte		        Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Cn3 
	.byte	W04
	.byte		        Dn1 , v100
	.byte	W04
	.byte		        An1 , v096
	.byte	W04
	.byte		        En2 
	.byte	W04
	.byte		        Fn2 
	.byte	W04
	.byte		        An2 
	.byte	W04
	.byte		        Cn3 
	.byte	W04
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x43
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x7D
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x43
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x7D
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x43
	.byte		VOICE , 1
	.byte		VOL   , 91*fe6_seq_012_mvl/mxv
	.byte		PAN   , c_v+6
	.byte		N23   , An2 , v096
	.byte		N23   , Dn3 
	.byte	W24
	.byte		N44   , Gn2 
	.byte		N40   , Cn3 
	.byte	W48
	.byte		N23   , Ds2 
	.byte		N23   , Gn2 
	.byte	W24
	.byte		N80
	.byte		N90   , Cn3 
	.byte	W96
	.byte		N19   , An2 
	.byte		N19   , Dn3 
	.byte	W24
	.byte		N40   , Gn2 
	.byte		N40   , Cn3 
	.byte	W48
	.byte		N19
	.byte		N19   , Fn3 
	.byte	W24
	.byte		N68   , Gn2 
	.byte		N68   , Cn3 
	.byte	W72
	.byte		N23   , Fn2 
	.byte		N23   , An2 
	.byte	W24
	.byte		N68   , Gn2 
	.byte		N68   , Cn3 
	.byte	W72
	.byte		N23   , Fn2 
	.byte		N23   , As2 
	.byte	W24
	.byte		N68   , Gn2 
	.byte		N68   , Cn3 
	.byte	W72
	.byte		N19   , An2 
	.byte		N23   , Dn3 
	.byte	W24
	.byte		N44   , Dn2 
	.byte		N44   , An2 
	.byte	W48
	.byte		        Fn2 
	.byte		N44   , As2 
	.byte	W48
	.byte		        Gn2 
	.byte		N44   , Cn3 
	.byte	W48
	.byte		N40   , An2 
	.byte		N36   , Dn3 
	.byte	W48
	.byte		N23   , An2 
	.byte		N23   , Dn3 
	.byte	W24
	.byte		N36   , Gn2 
	.byte		N40   , Cn3 
	.byte	W48
	.byte		N23   , Dn2 
	.byte		N20   , Gn2 
	.byte	W24
	.byte		N92
	.byte		N92   , Cn3 
	.byte	W96
	.byte		N23   , An2 
	.byte		N23   , Dn3 
	.byte	W24
	.byte		N32   , Gn2 
	.byte		N36   , Cn3 
	.byte	W48
	.byte		N23
	.byte		N23   , Fn3 
	.byte	W24
	.byte		N44   , An2 
	.byte		N44   , Dn3 
	.byte	W48
	.byte		N42   , Gn2 
	.byte		N40   , Cn3 
	.byte	W48
	.byte		N23   , Gn2 
	.byte		N23   , Cn3 
	.byte	W24
	.byte		N68   , Fn2 
	.byte		N68   , As2 
	.byte	W72
	.byte		N42   , En2 
	.byte		N44   , An2 
	.byte	W48
	.byte		        Dn2 
	.byte		N44   , Fn2 
	.byte	W48
	.byte		        Gn2 
	.byte		N44   , Cn3 
	.byte	W48
	.byte		        Fn2 
	.byte		N44   , As2 
	.byte	W48
	.byte		        Gn2 
	.byte		N44   , Cn3 
	.byte	W48
	.byte		N40   , An2 
	.byte		N40   , Dn3 
	.byte	W48
	.byte		N23   , An2 
	.byte		N19   , Dn3 
	.byte	W24
	.byte		N64
	.byte		N64   , Gn3 
	.byte	W72
	.byte		N23   , Dn3 
	.byte		N21   , Gn3 
	.byte	W24
	.byte		N60
	.byte		N60   , Cn4 
	.byte	W72
	.byte		N23   , Gn3 
	.byte		N23   , Cn4 
	.byte	W24
	.byte		N66   , En3 
	.byte		N66   , An3 
	.byte	W72
	.byte		N23   , En3 
	.byte		N23   , An3 
	.byte	W24
	.byte		N42   , Cn3 
	.byte		N42   , Fn3 
	.byte	W48
	.byte		N23   , An2 
	.byte		N19   , Dn3 
	.byte	W24
	.byte		N92
	.byte		N92   , Gn3 
	.byte	W72
	.byte		VOICE , 46
	.byte		VOL   , 53*fe6_seq_012_mvl/mxv
	.byte		PAN   , c_v-14
	.byte	W24
	.byte		N07   , Gn2 , v108
	.byte	W08
	.byte		        An3 , v096
	.byte	W08
	.byte		        Dn4 
	.byte	W08
	.byte		        Gn2 , v108
	.byte	W08
	.byte		        An3 , v096
	.byte	W08
	.byte		        Dn4 
	.byte	W08
	.byte		        Gn2 , v108
	.byte	W08
	.byte		        An3 , v096
	.byte	W08
	.byte		        Dn4 
	.byte	W08
	.byte		        Gn2 , v108
	.byte	W08
	.byte		        An3 , v096
	.byte	W08
	.byte		        Dn4 
	.byte	W08
	.byte		N07   , Dn2 , v108
	.byte	W08
	.byte		        En3 , v096
	.byte	W08
	.byte		        An3 
	.byte	W08
	.byte		        Dn2 , v108
	.byte	W08
	.byte		        En3 , v096
	.byte	W08
	.byte		        An3 
	.byte	W08
	.byte		        Dn2 , v108
	.byte	W08
	.byte		        En3 , v096
	.byte	W08
	.byte		        An3 
	.byte	W08
	.byte		        Dn2 , v108
	.byte	W08
	.byte		        En3 , v096
	.byte	W08
	.byte		        An3 
	.byte	W08
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x1CE
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x1CE
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x1CE
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x1CE
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x1CE
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x1CE
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x1CE
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x1CE
	.byte	PATT
	 .word	fe6_seq_012_0 + 0x1CE
	.byte	GOTO
	 .word	fe6_seq_012_0 + 0xD0
	.byte	FINE

@*********************** Track 02 ***********************@

fe6_seq_012_1:
	.byte	KEYSH , fe6_seq_012_key+0
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 1
	.byte		VOL   , 53*fe6_seq_012_mvl/mxv
	.byte		PAN   , c_v+6
	.byte	W06
	.byte		N23   , Dn3 , v096
	.byte	W24
	.byte		N40   , Cn3 
	.byte	W48
	.byte		N23   , Gn2 
	.byte	W18
	.byte	W06
	.byte		N90   , Cn3 
	.byte	W90
	.byte	W06
	.byte		N19   , Dn3 
	.byte	W24
	.byte		N40   , Cn3 
	.byte	W48
	.byte		N19   , Fn3 
	.byte	W18
	.byte	W06
	.byte		N68   , Cn3 
	.byte	W72
	.byte		N23   , An2 
	.byte	W18
	.byte	W06
	.byte		N68   , Cn3 
	.byte	W72
	.byte		N23   , As2 
	.byte	W18
	.byte	W06
	.byte		N68   , Cn3 
	.byte	W72
	.byte		N23   , Dn3 
	.byte	W18
	.byte	W06
	.byte		N44   , An2 
	.byte	W48
	.byte		        As2 
	.byte	W42
	.byte	W06
	.byte		        Cn3 
	.byte	W48
	.byte		N36   , Dn3 
	.byte	W42
	.byte	W06
	.byte		N23
	.byte	W24
	.byte		N40   , Cn3 
	.byte	W48
	.byte		N20   , Gn2 
	.byte	W18
	.byte	W06
	.byte		N92   , Cn3 
	.byte	W90
	.byte	W06
	.byte		N23   , Dn3 
	.byte	W24
	.byte		N36   , Cn3 
	.byte	W48
	.byte		N23   , Fn3 
	.byte	W18
	.byte	W06
	.byte		N44   , Dn3 
	.byte	W48
	.byte		N40   , Cn3 
	.byte	W42
	.byte	W06
	.byte		N23
	.byte	W24
	.byte		N68   , As2 
	.byte	W66
	.byte	W06
	.byte		N44   , An2 
	.byte	W48
	.byte		        Fn2 
	.byte	W42
	.byte	W06
	.byte		        Cn3 
	.byte	W48
	.byte		        As2 
	.byte	W42
	.byte	W06
	.byte		        Cn3 
	.byte	W48
	.byte		N40   , Dn3 
	.byte	W42
	.byte	W06
	.byte		N19
	.byte	W24
	.byte		N64   , Gn3 
	.byte	W66
	.byte	W06
	.byte		N21
	.byte	W24
	.byte		N60   , Cn4 
	.byte	W66
	.byte	W06
	.byte		N23
	.byte	W24
	.byte		N66   , An3 
	.byte	W66
	.byte	W06
	.byte		N23
	.byte	W24
	.byte		N42   , Fn3 
	.byte	W48
	.byte		N19   , Dn3 
	.byte	W18
	.byte	W06
	.byte		N88   , Gn3 
	.byte	W66
	.byte		VOICE , 46
	.byte		VOL   , 53*fe6_seq_012_mvl/mxv
	.byte		PAN   , c_v-14
	.byte	W24
	.byte	W04
	.byte		N07   , Dn3 
	.byte	W08
	.byte		        As3 
	.byte	W08
	.byte		        En4 
	.byte	W08
	.byte		        Dn3 
	.byte	W08
	.byte		        As3 
	.byte	W08
	.byte		        En4 
	.byte	W08
	.byte		        Dn3 
	.byte	W08
	.byte		        As3 
	.byte	W08
	.byte		        En4 
	.byte	W08
	.byte		        Dn3 
	.byte	W08
	.byte		        As3 
	.byte	W08
	.byte		        En4 
	.byte	W04
	.byte	W04
	.byte		N07   , An2 , v096
	.byte	W08
	.byte		        Fn3 
	.byte	W08
	.byte		        Cn4 
	.byte	W08
	.byte		        An2 
	.byte	W08
	.byte		        Fn3 
	.byte	W08
	.byte		        Cn4 
	.byte	W08
	.byte		        An2 
	.byte	W08
	.byte		        Fn3 
	.byte	W08
	.byte		        Cn4 
	.byte	W08
	.byte		        An2 
	.byte	W08
	.byte		        Fn3 
	.byte	W08
	.byte		        Cn4 
	.byte	W04
	.byte	PEND
	.byte	W04
	.byte		N07   , An2 , v096
	.byte	W08
	.byte		        Fn3 
	.byte	W08
	.byte		        Bn3 
	.byte	W08
	.byte		        An2 
	.byte	W08
	.byte		        Fn3 
	.byte	W08
	.byte		        Bn3 
	.byte	W08
	.byte		        An2 
	.byte	W08
	.byte		        Fn3 
	.byte	W08
	.byte		        Bn3 
	.byte	W08
	.byte		        An2 
	.byte	W08
	.byte		        Fn3 
	.byte	W08
	.byte		        Bn3 
	.byte	W04
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_012_1 + 0xBF
	.byte	PATT
	 .word	fe6_seq_012_1 + 0xDB
	.byte	PATT
	 .word	fe6_seq_012_1 + 0xBF
	.byte	W04
	.byte		N03   , An2 , v096
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		        Bn3 
	.byte	W08
	.byte		N03   , An2 
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		        Bn3 
	.byte	W08
	.byte		N03   , An2 
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		        Bn3 
	.byte	W08
	.byte		N03   , An2 
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		        Bn3 
	.byte	W04
	.byte	PEND
	.byte	W04
	.byte		N03   , An2 , v096
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		        Cn4 
	.byte	W08
	.byte		N03   , An2 
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		        Cn4 
	.byte	W08
	.byte		N03   , An2 
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		        Cn4 
	.byte	W08
	.byte		N03   , An2 
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		        Cn4 
	.byte	W04
	.byte	PEND
	.byte	PATT
	 .word	fe6_seq_012_1 + 0x106
	.byte	PATT
	 .word	fe6_seq_012_1 + 0x129
	.byte	W04
	.byte		N03   , An2 , v096
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		        Bn3 
	.byte	W08
	.byte		N03   , An2 
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		        Bn3 
	.byte	W08
	.byte		N03   , An2 
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		        Bn3 
	.byte	W08
	.byte		N03   , An2 
	.byte	W08
	.byte		N07   , Fn3 
	.byte	W08
	.byte		N03   , Bn3 
	.byte	W04
	.byte	GOTO
	 .word	fe6_seq_012_1 + 0xA
	.byte	FINE

@*********************** Track 03 ***********************@

fe6_seq_012_2:
	.byte	KEYSH , fe6_seq_012_key+0
	.byte		VOICE , 48
	.byte		VOL   , 16*fe6_seq_012_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		VOL   , 18*fe6_seq_012_mvl/mxv
	.byte		N68   , Bn2 , v100
	.byte		N68   , Bn3 
	.byte	W01
	.byte		VOL   , 21*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        23*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        26*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        28*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        31*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        33*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        37*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        39*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        42*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        45*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        47*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        50*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        53*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        55*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        58*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        61*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        63*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        66*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        69*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        71*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        74*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        77*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        79*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        82*fe6_seq_012_mvl/mxv
	.byte	W48
	.byte		N23   , En2 
	.byte		N23   , En3 
	.byte	W23
	.byte		VOL   , 33*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte	PEND
	.byte		VOL   , 18*fe6_seq_012_mvl/mxv
	.byte		N92   , An2 , v100
	.byte		N92   , An3 
	.byte	W01
	.byte		VOL   , 21*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        23*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        26*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        28*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        31*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        33*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        37*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        38*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        42*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        44*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        47*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        49*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        52*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        54*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        57*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        61*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        62*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        66*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        68*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        71*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        73*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        76*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        78*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        82*fe6_seq_012_mvl/mxv
	.byte	W72
	.byte	PEND
	.byte		N44   , Bn2 , v100
	.byte		N44   , Bn3 
	.byte	W48
	.byte		        Cn3 
	.byte		N44   , Cn4 
	.byte	W48
	.byte	PEND
	.byte		N92   , Dn3 , v100
	.byte		N92   , Dn4 
	.byte	W92
	.byte	W03
	.byte		VOL   , 82*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte	PEND
	.byte		VOL   , 19*fe6_seq_012_mvl/mxv
	.byte		N92   , An2 , v100
	.byte		N92   , An3 
	.byte	W01
	.byte		VOL   , 22*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        24*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        27*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        30*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        32*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        35*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        38*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        40*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        42*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        46*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        47*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        50*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        53*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        55*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        58*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        61*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        63*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        66*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        69*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        71*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        74*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        76*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        79*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        82*fe6_seq_012_mvl/mxv
	.byte	W68
	.byte	W03
	.byte		        82*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte	PEND
	.byte		VOL   , 19*fe6_seq_012_mvl/mxv
	.byte		N92   , Bn2 , v100
	.byte		N92   , Bn3 
	.byte	W01
	.byte		VOL   , 21*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        23*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        26*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        29*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        31*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        34*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        37*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        39*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        42*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        45*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        47*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        50*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        53*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        55*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        57*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        61*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        62*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        66*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        69*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        71*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        74*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        76*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        78*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        82*fe6_seq_012_mvl/mxv
	.byte	W68
	.byte	W03
	.byte		        42*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte	PEND
	.byte		VOL   , 18*fe6_seq_012_mvl/mxv
	.byte		TIE   , En2 , v100
	.byte		TIE   , En3 
	.byte	W01
	.byte		VOL   , 19*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        20*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        22*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        23*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        24*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        26*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        28*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        28*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        30*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        32*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        33*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        34*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        36*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        37*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        38*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        40*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        41*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        42*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        44*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        45*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        47*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        48*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        49*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        50*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        52*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        52*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        54*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        56*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        57*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        58*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        60*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        61*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        62*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        64*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        65*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        66*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        68*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        69*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        71*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        72*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        73*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        75*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        76*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        77*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        79*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        81*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        81*fe6_seq_012_mvl/mxv
	.byte	W01
	.byte		        82*fe6_seq_012_mvl/mxv
	.byte	W48
	.byte	PEND
	.byte	W44
	.byte	W03
	.byte		EOT   , En2 
	.byte		        En3 
	.byte	W01
	.byte		N44   , Dn2 
	.byte		N44   , Dn3 
	.byte	W48
	.byte		VOICE , 45
	.byte		VOL   , 78*fe6_seq_012_mvl/mxv
	.byte		PAN   , c_v-13
	.byte	W12
	.byte		N11   , As2 , v096
	.byte	W12
	.byte		        As2 , v016
	.byte	W12
	.byte		        As2 , v096
	.byte	W12
	.byte		        As2 , v016
	.byte	W12
	.byte		        As2 , v096
	.byte	W12
	.byte		        As2 , v020
	.byte	W12
	.byte		        As2 , v096
	.byte	W12
	.byte		        As2 , v016
	.byte	W12
	.byte		        As2 , v088
	.byte	W12
	.byte		        As2 , v012
	.byte	W12
	.byte		        As2 , v088
	.byte	W12
	.byte		        As2 , v012
	.byte	W12
	.byte		        As2 , v100
	.byte	W12
	.byte		        As2 , v024
	.byte	W12
	.byte		        As2 , v100
	.byte	W12
	.byte		        As2 , v020
	.byte	W12
	.byte		        As2 , v100
	.byte	W12
	.byte		        As2 , v020
	.byte	W12
	.byte		        As2 , v096
	.byte	W12
	.byte		        As2 , v016
	.byte	W12
	.byte		        As2 , v096
	.byte	W12
	.byte		        As2 , v016
	.byte	W12
	.byte		        As2 , v100
	.byte	W12
	.byte		        As2 , v024
	.byte	W12
	.byte		        As2 , v092
	.byte	W12
	.byte		        As2 , v012
	.byte	W12
	.byte		        As2 , v096
	.byte	W12
	.byte		        As2 , v016
	.byte	W12
	.byte		        As2 , v096
	.byte	W12
	.byte		        As2 , v016
	.byte	W12
	.byte		        As2 , v092
	.byte	W12
	.byte		        As2 , v016
	.byte	W12
	.byte		        An2 , v096
	.byte	W12
	.byte		        An2 , v020
	.byte	W12
	.byte		        An2 , v108
	.byte	W12
	.byte		        An2 , v028
	.byte	W12
	.byte		        An2 , v112
	.byte	W12
	.byte		        An2 , v032
	.byte	W12
	.byte		        An2 , v104
	.byte	W12
	.byte		        An2 , v024
	.byte	W12
	.byte		        An2 , v096
	.byte	W12
	.byte		        An2 , v020
	.byte	W12
	.byte		        An2 , v104
	.byte	W12
	.byte		        An2 , v024
	.byte	W12
	.byte		        An2 , v104
	.byte	W12
	.byte		        An2 , v024
	.byte	W12
	.byte		        An2 , v108
	.byte	W12
	.byte		        An2 , v028
	.byte	W12
	.byte		        An2 , v096
	.byte	W12
	.byte		        An2 , v020
	.byte	W12
	.byte		        An2 , v100
	.byte	W12
	.byte		        An2 , v020
	.byte	W12
	.byte		        An2 , v108
	.byte	W12
	.byte		        An2 , v032
	.byte	W12
	.byte		        An2 , v108
	.byte	W12
	.byte		        An2 , v028
	.byte	W12
	.byte		        An2 , v112
	.byte	W12
	.byte		        An2 , v032
	.byte	W12
	.byte		        An2 , v100
	.byte	W12
	.byte		        An2 , v020
	.byte	W12
	.byte		        An2 , v092
	.byte	W12
	.byte		        An2 , v012
	.byte	W12
	.byte		        An2 , v100
	.byte	W12
	.byte		        An2 , v024
	.byte	W12
	.byte		        As2 , v092
	.byte	W12
	.byte		        As2 , v016
	.byte	W12
	.byte		        As2 , v100
	.byte	W12
	.byte		        As2 , v020
	.byte	W12
	.byte		        As2 , v100
	.byte	W12
	.byte		        As2 , v024
	.byte	W12
	.byte		        As2 , v100
	.byte	W12
	.byte		        As2 , v024
	.byte	W12
	.byte		        As2 , v100
	.byte	W12
	.byte		        As2 , v020
	.byte	W12
	.byte		        As2 , v104
	.byte	W12
	.byte		        As2 , v028
	.byte	W12
	.byte		        As2 , v100
	.byte	W12
	.byte		        As2 , v020
	.byte	W12
	.byte		        As2 , v108
	.byte	W12
	.byte		        As2 , v032
	.byte	W12
	.byte		        As2 , v104
	.byte	W12
	.byte		        As2 , v028
	.byte	W12
	.byte		        As2 , v104
	.byte	W12
	.byte		        As2 , v024
	.byte	W12
	.byte		        As2 , v100
	.byte	W12
	.byte		        As2 , v020
	.byte	W12
	.byte		        As2 , v096
	.byte	W12
	.byte		        As2 , v016
	.byte	W12
	.byte		        As2 , v108
	.byte	W12
	.byte		        As2 , v028
	.byte	W12
	.byte		        As2 , v112
	.byte	W12
	.byte		        As2 , v032
	.byte	W12
	.byte		        As2 , v104
	.byte	W12
	.byte		        As2 , v024
	.byte	W12
	.byte		        As2 , v096
	.byte	W12
	.byte		        As2 , v016
	.byte	W12
	.byte		        An2 , v096
	.byte	W12
	.byte		        An2 , v020
	.byte	W12
	.byte		        An2 , v116
	.byte	W12
	.byte		        An2 , v036
	.byte	W12
	.byte		        An2 , v096
	.byte	W12
	.byte		        An2 , v016
	.byte	W12
	.byte		        An2 , v104
	.byte	W12
	.byte		        An2 , v028
	.byte	W12
	.byte		        An2 , v108
	.byte	W12
	.byte		        An2 , v032
	.byte	W12
	.byte		        An2 , v112
	.byte	W12
	.byte		        An2 , v032
	.byte	W12
	.byte		        An2 , v104
	.byte	W12
	.byte		        An2 , v024
	.byte	W12
	.byte		        An2 , v104
	.byte	W12
	.byte		        An2 , v028
	.byte	W12
	.byte		        An2 , v104
	.byte	W12
	.byte		        An2 , v028
	.byte	W12
	.byte		        An2 , v104
	.byte	W12
	.byte		        An2 , v028
	.byte	W12
	.byte		        An2 , v108
	.byte	W12
	.byte		        An2 , v032
	.byte	W12
	.byte		        An2 , v112
	.byte	W12
	.byte		        An2 , v032
	.byte	W12
	.byte		        An2 , v108
	.byte	W12
	.byte		        An2 , v032
	.byte	W12
	.byte		        An2 , v112
	.byte	W12
	.byte		        An2 , v032
	.byte	W12
	.byte		        An2 , v092
	.byte	W12
	.byte		        An2 , v016
	.byte	W12
	.byte		        An2 , v084
	.byte	W12
	.byte		        An2 , v012
	.byte	W12
	.byte		        As2 , v088
	.byte	W12
	.byte		        As2 , v012
	.byte	W12
	.byte		        As2 , v100
	.byte	W12
	.byte		        As2 , v020
	.byte	W12
	.byte		        As2 , v108
	.byte	W12
	.byte		        As2 , v032
	.byte	W12
	.byte		        As2 , v108
	.byte	W12
	.byte		        As2 , v032
	.byte	W12
	.byte		        As2 , v104
	.byte	W12
	.byte		        As2 , v024
	.byte	W12
	.byte		        As2 , v104
	.byte	W12
	.byte		        As2 , v028
	.byte	W12
	.byte		        As2 , v108
	.byte	W12
	.byte		        As2 , v028
	.byte	W12
	.byte		        As2 , v076
	.byte	W12
	.byte		        As2 , v012
	.byte	W12
	.byte		        Cn3 , v096
	.byte	W12
	.byte		        Cn3 , v020
	.byte	W12
	.byte		        Cn3 , v100
	.byte	W12
	.byte		        Cn3 , v020
	.byte	W12
	.byte		        Cn3 , v104
	.byte	W12
	.byte		        Cn3 , v024
	.byte	W12
	.byte		        Cn3 , v116
	.byte	W12
	.byte		        Cn3 , v036
	.byte	W12
	.byte		        Cn3 , v104
	.byte	W12
	.byte		        Cn3 , v028
	.byte	W12
	.byte		        Cn3 , v108
	.byte	W12
	.byte		        Cn3 , v028
	.byte	W12
	.byte		        Cn3 , v120
	.byte	W12
	.byte		        Cn3 , v040
	.byte	W12
	.byte		        Cn3 , v096
	.byte	W12
	.byte		        Cn3 , v020
	.byte	W12
	.byte		        Dn3 , v104
	.byte	W12
	.byte		        Dn3 , v024
	.byte	W12
	.byte		        Dn3 , v108
	.byte	W12
	.byte		        Dn3 , v032
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v036
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v036
	.byte	W12
	.byte		        Dn3 , v116
	.byte	W12
	.byte		        Dn3 , v036
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v036
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v036
	.byte	W12
	.byte		N05   , Dn3 , v108
	.byte	W06
	.byte		        Dn3 , v028
	.byte	W06
	.byte	W96
	.byte	W96
	.byte	PATT
	 .word	fe6_seq_012_2 + 0x2
	.byte	PATT
	 .word	fe6_seq_012_2 + 0x4A
	.byte	PATT
	 .word	fe6_seq_012_2 + 0x84
	.byte	PATT
	 .word	fe6_seq_012_2 + 0x8F
	.byte	PATT
	 .word	fe6_seq_012_2 + 0x9A
	.byte	PATT
	 .word	fe6_seq_012_2 + 0xD7
	.byte	PATT
	 .word	fe6_seq_012_2 + 0x114
	.byte	W44
	.byte	W03
	.byte		EOT   , En2 
	.byte		        En3 
	.byte	W01
	.byte		N44   , Dn2 , v100
	.byte		N44   , Dn3 
	.byte	W48
	.byte	GOTO
	 .word	fe6_seq_012_2 + 0x189
	.byte	FINE

@*********************** Track 04 ***********************@

fe6_seq_012_3:
	.byte	KEYSH , fe6_seq_012_key+0
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 58
	.byte		VOL   , 78*fe6_seq_012_mvl/mxv
	.byte		PAN   , c_v-13
	.byte	W12
	.byte		N11   , Ds3 , v084
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v080
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v084
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v080
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v092
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v092
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v080
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v092
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v092
	.byte	W12
	.byte		        Ds3 , v016
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v092
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Dn3 , v096
	.byte	W12
	.byte		        Dn3 , v020
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v036
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v036
	.byte	W12
	.byte		        Dn3 , v104
	.byte	W12
	.byte		        Dn3 , v024
	.byte	W12
	.byte		        Dn3 , v100
	.byte	W12
	.byte		        Dn3 , v024
	.byte	W12
	.byte		        Dn3 , v100
	.byte	W12
	.byte		        Dn3 , v024
	.byte	W12
	.byte		        Dn3 , v100
	.byte	W12
	.byte		        Dn3 , v024
	.byte	W12
	.byte		        Dn3 , v104
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v100
	.byte	W12
	.byte		        Dn3 , v024
	.byte	W12
	.byte		        Dn3 , v108
	.byte	W12
	.byte		        Dn3 , v032
	.byte	W12
	.byte		        Dn3 , v108
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v108
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v032
	.byte	W12
	.byte		        Dn3 , v104
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v104
	.byte	W12
	.byte		        Dn3 , v024
	.byte	W12
	.byte		        Dn3 , v096
	.byte	W12
	.byte		        Dn3 , v020
	.byte	W12
	.byte		        Ds3 , v080
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v084
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v080
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v100
	.byte	W12
	.byte		        Ds3 , v020
	.byte	W12
	.byte		        Ds3 , v092
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v092
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v084
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v084
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v096
	.byte	W12
	.byte		        Ds3 , v020
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Dn3 , v100
	.byte	W12
	.byte		        Dn3 , v020
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v032
	.byte	W12
	.byte		        Dn3 , v092
	.byte	W12
	.byte		        Dn3 , v012
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v032
	.byte	W12
	.byte		        Dn3 , v108
	.byte	W12
	.byte		        Dn3 , v032
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v032
	.byte	W12
	.byte		        Dn3 , v104
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v108
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v104
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v108
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v108
	.byte	W12
	.byte		        Dn3 , v032
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v032
	.byte	W12
	.byte		        Dn3 , v104
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v112
	.byte	W12
	.byte		        Dn3 , v032
	.byte	W12
	.byte		        Dn3 , v108
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v108
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Ds3 , v080
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v096
	.byte	W12
	.byte		        Ds3 , v016
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v092
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v088
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Ds3 , v076
	.byte	W12
	.byte		        Ds3 , v012
	.byte	W12
	.byte		        Fn3 , v108
	.byte	W12
	.byte		        Fn3 , v032
	.byte	W12
	.byte		        Fn3 , v108
	.byte	W12
	.byte		        Fn3 , v032
	.byte	W12
	.byte		        Fn3 , v116
	.byte	W12
	.byte		        Fn3 , v040
	.byte	W12
	.byte		        Fn3 , v112
	.byte	W12
	.byte		        Fn3 , v032
	.byte	W12
	.byte		        Fn3 , v100
	.byte	W12
	.byte		        Fn3 , v024
	.byte	W12
	.byte		        Fn3 , v108
	.byte	W12
	.byte		        Fn3 , v032
	.byte	W12
	.byte		        Fn3 , v112
	.byte	W12
	.byte		        Fn3 , v032
	.byte	W12
	.byte		        Fn3 , v100
	.byte	W12
	.byte		        Fn3 , v024
	.byte	W12
	.byte		        Gn3 , v100
	.byte	W12
	.byte		        Gn3 , v024
	.byte	W12
	.byte		        Gn3 , v100
	.byte	W12
	.byte		        Gn3 , v024
	.byte	W12
	.byte		        Gn3 , v104
	.byte	W12
	.byte		        Gn3 , v024
	.byte	W12
	.byte		        Gn3 , v108
	.byte	W12
	.byte		        Gn3 , v032
	.byte	W12
	.byte		        Gn3 , v108
	.byte	W12
	.byte		        Gn3 , v028
	.byte	W12
	.byte		        Gn3 , v112
	.byte	W12
	.byte		        Gn3 , v032
	.byte	W12
	.byte		        Gn3 , v108
	.byte	W12
	.byte		        Gn3 , v028
	.byte	W12
	.byte		N05   , Gn3 , v104
	.byte	W06
	.byte		        Gn3 , v028
	.byte	W06
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 58
	.byte		VOL   , 49*fe6_seq_012_mvl/mxv
	.byte		PAN   , c_v-6
	.byte	W24
	.byte		N23   , Bn3 , v108
	.byte	W24
	.byte		        En3 
	.byte	W24
	.byte		N22   , An3 , v104
	.byte	W24
	.byte		TIE   , Bn3 , v112
	.byte	W96
	.byte	W03
	.byte		EOT
	.byte	W21
	.byte		N20   , An3 , v108
	.byte	W24
	.byte		        Bn3 , v100
	.byte	W24
	.byte		N19   , Cn4 , v104
	.byte	W24
	.byte		TIE   , Dn4 , v120
	.byte	W96
	.byte	W04
	.byte		EOT
	.byte	W68
	.byte		N22   , An3 , v108
	.byte	W24
	.byte		N84   , Dn4 , v120
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	fe6_seq_012_3 + 0xA
	.byte	FINE

@*********************** Track 05 ***********************@

fe6_seq_012_4:
	.byte	KEYSH , fe6_seq_012_key+0
	.byte		VOICE , 127
	.byte		VOL   , 62*fe6_seq_012_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N48   , Gn1 , v127
	.byte	W96
	.byte	W72
	.byte		N11   , Gn1 , v108
	.byte	W12
	.byte		        Fn1 , v124
	.byte	W12
	.byte		N23   , Gn1 
	.byte	W24
	.byte		        Gn1 , v108
	.byte	W24
	.byte		        Gn1 , v116
	.byte	W24
	.byte		        Gn1 , v112
	.byte	W24
	.byte		        Gn1 , v120
	.byte	W24
	.byte		        Gn1 , v116
	.byte	W24
	.byte		N23
	.byte	W24
	.byte		N11   , Gn1 , v124
	.byte	W12
	.byte		        Fn1 
	.byte	W12
	.byte		        Gn1 , v127
	.byte	W12
	.byte		N05   , Gn1 , v032
	.byte	W06
	.byte		        Gn1 , v028
	.byte	W06
	.byte		N11   , Gn1 , v104
	.byte	W12
	.byte		N05   , Gn1 , v052
	.byte	W06
	.byte		        Gn1 , v036
	.byte	W06
	.byte		N11   , Gn1 , v108
	.byte	W12
	.byte		N05   , Gn1 , v064
	.byte	W06
	.byte		        Gn1 , v052
	.byte	W06
	.byte		N11   , Gn1 , v124
	.byte	W12
	.byte		        Fn1 , v116
	.byte	W12
	.byte		        Gn1 , v127
	.byte	W12
	.byte		N05   , Gn1 , v048
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		N11   , Gn1 , v092
	.byte	W12
	.byte		N05   , Gn1 , v064
	.byte	W06
	.byte		        Gn1 , v048
	.byte	W06
	.byte		N11   , Gn1 , v104
	.byte	W12
	.byte		N05   , Gn1 , v064
	.byte	W06
	.byte		        Gn1 , v048
	.byte	W06
	.byte		N11   , Gn1 , v112
	.byte	W12
	.byte		        Fn1 , v108
	.byte	W12
	.byte		        Gn1 , v124
	.byte	W12
	.byte		N05   , Gn1 , v052
	.byte	W06
	.byte		        Gn1 , v012
	.byte	W06
	.byte		N11   , Gn1 , v092
	.byte	W12
	.byte		N05   , Gn1 , v060
	.byte	W06
	.byte		        Gn1 , v048
	.byte	W06
	.byte		N11   , Gn1 , v096
	.byte	W12
	.byte		N05   , Gn1 , v060
	.byte	W06
	.byte		        Gn1 , v064
	.byte	W06
	.byte		N11   , Gn1 , v112
	.byte	W12
	.byte		N05   , Gn1 , v048
	.byte	W06
	.byte		        Gn1 , v028
	.byte	W06
	.byte		N11   , Gn1 , v100
	.byte	W12
	.byte		N05   , Gn1 , v060
	.byte	W06
	.byte		        Gn1 , v048
	.byte	W06
	.byte		N11   , Gn1 , v100
	.byte	W12
	.byte		N05   , Gn1 , v072
	.byte	W06
	.byte		        Gn1 , v060
	.byte	W06
	.byte		N11   , Gn1 , v108
	.byte	W12
	.byte		N05   , Gn1 , v076
	.byte	W06
	.byte		        Gn1 , v064
	.byte	W06
	.byte		        Gn1 , v108
	.byte	W06
	.byte		        Gn1 , v104
	.byte	W06
	.byte		        Gn1 , v116
	.byte	W06
	.byte		        Gn1 , v108
	.byte	W06
	.byte		N11   , Gn1 , v127
	.byte	W12
	.byte		N23   , Gn1 , v104
	.byte	W24
	.byte		N11   , Gn1 , v084
	.byte	W12
	.byte		        Gn1 , v104
	.byte	W12
	.byte		N32   , Gn1 , v112
	.byte	W36
	.byte		N11   , Gn1 , v120
	.byte	W12
	.byte		N23   , Gn1 , v116
	.byte	W24
	.byte		N11   , Gn1 , v108
	.byte	W12
	.byte		N11
	.byte	W12
	.byte		N32   , Gn1 , v127
	.byte	W36
	.byte		N11   , Gn1 , v116
	.byte	W12
	.byte		N23   , Gn1 , v112
	.byte	W24
	.byte		N11   , Gn1 , v088
	.byte	W12
	.byte		        Gn1 , v108
	.byte	W12
	.byte		N32   , Gn1 , v116
	.byte	W36
	.byte		N11
	.byte	W12
	.byte		N23   , Gn1 , v124
	.byte	W24
	.byte		N11   , Gn1 , v116
	.byte	W12
	.byte		        Gn1 , v120
	.byte	W12
	.byte		N23   , Gn1 , v127
	.byte	W24
	.byte		N11   , Fn1 , v116
	.byte	W12
	.byte		        Gn1 
	.byte	W12
	.byte		N23   , Gn1 , v120
	.byte	W24
	.byte		N11   , Gn1 , v104
	.byte	W12
	.byte		        Gn1 , v120
	.byte	W12
	.byte		N32
	.byte	W36
	.byte		N11   , Gn1 , v116
	.byte	W12
	.byte		N23   , Gn1 , v124
	.byte	W24
	.byte		N11   , Gn1 , v112
	.byte	W12
	.byte		N11
	.byte	W12
	.byte		N32   , Gn1 , v124
	.byte	W36
	.byte		N11   , Gn1 , v120
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		N11   , Gn1 , v108
	.byte	W12
	.byte		        Gn1 , v120
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		N11   , Fn1 , v096
	.byte	W12
	.byte		        Gn1 , v116
	.byte	W12
	.byte		N23   , Gn1 , v108
	.byte	W24
	.byte		N11   , Fn1 
	.byte	W12
	.byte		        Gn1 , v112
	.byte	W12
	.byte		        Fn1 , v124
	.byte	W12
	.byte		        Gn1 , v120
	.byte	W12
	.byte		        Fn1 , v116
	.byte	W12
	.byte		        Gn1 , v120
	.byte	W12
	.byte		N23   , Gn1 , v116
	.byte	W24
	.byte		N11   , Gn1 , v096
	.byte	W12
	.byte		        Gn1 , v112
	.byte	W12
	.byte		N32   , Gn1 , v116
	.byte	W36
	.byte		N11   , Gn1 , v120
	.byte	W12
	.byte		N23   , Gn1 , v124
	.byte	W24
	.byte		N11   , Gn1 , v108
	.byte	W12
	.byte		        Gn1 , v116
	.byte	W12
	.byte		N32   , Gn1 , v124
	.byte	W36
	.byte		N11   , Gn1 , v112
	.byte	W12
	.byte		N23   , Gn1 , v124
	.byte	W24
	.byte		N11   , Gn1 , v104
	.byte	W12
	.byte		        Gn1 , v120
	.byte	W12
	.byte		N32
	.byte	W36
	.byte		N11   , Gn1 , v116
	.byte	W12
	.byte		N23   , Gn1 , v120
	.byte	W24
	.byte		N11   , Gn1 , v112
	.byte	W12
	.byte		        Gn1 , v116
	.byte	W12
	.byte		N23   , Gn1 , v127
	.byte	W24
	.byte		N11   , Fn1 , v104
	.byte	W12
	.byte		        Gn1 , v108
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		N11   , Gn1 , v104
	.byte	W12
	.byte		        Gn1 , v108
	.byte	W12
	.byte		N32
	.byte	W36
	.byte		N11   , Gn1 , v116
	.byte	W12
	.byte		N23   , Gn1 , v127
	.byte	W24
	.byte		N11   , Gn1 , v104
	.byte	W12
	.byte		        Gn1 , v116
	.byte	W12
	.byte		N32   , Gn1 , v120
	.byte	W36
	.byte		N11   , Gn1 , v124
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		N11   , Gn1 , v112
	.byte	W12
	.byte		        Gn1 , v124
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		N11   , Fn1 , v100
	.byte	W12
	.byte		        Gn1 , v112
	.byte	W12
	.byte		        Fn1 , v060
	.byte	W12
	.byte		        Gn1 , v084
	.byte	W12
	.byte		        Fn1 , v100
	.byte	W12
	.byte		        Gn1 , v124
	.byte	W12
	.byte		        Fn1 , v127
	.byte	W12
	.byte		        Gn1 
	.byte	W12
	.byte		        Fn1 , v116
	.byte	W12
	.byte		N48   , Gn1 , v127
	.byte	W96
	.byte	W84
	.byte		N11   , Fn1 , v124
	.byte	W12
	.byte		N48   , Gn1 , v127
	.byte	W96
	.byte	W84
	.byte		N11   , Fn1 , v120
	.byte	W12
	.byte		N52   , Gn1 , v127
	.byte	W84
	.byte		N05   , Gn1 , v088
	.byte	W06
	.byte		        Gn1 , v084
	.byte	W06
	.byte		N11   , Gn1 , v096
	.byte	W12
	.byte		N05   , Gn1 , v100
	.byte	W06
	.byte		        Gn1 , v088
	.byte	W06
	.byte		N11   , Gn1 , v096
	.byte	W12
	.byte		N05   , Gn1 , v080
	.byte	W06
	.byte		        Gn1 , v072
	.byte	W06
	.byte		N11   , Gn1 , v088
	.byte	W12
	.byte		N05   , Gn1 , v072
	.byte	W06
	.byte		        Gn1 , v084
	.byte	W06
	.byte		N11   , Gn1 , v104
	.byte	W12
	.byte		N05   , Gn1 , v108
	.byte	W06
	.byte		        Gn1 , v096
	.byte	W06
	.byte		N11   , Gn1 , v120
	.byte	W12
	.byte		N05   , Gn1 , v096
	.byte	W06
	.byte		        Gn1 , v088
	.byte	W06
	.byte		N11   , Gn1 , v092
	.byte	W12
	.byte		N05   , Gn1 , v100
	.byte	W06
	.byte		        Gn1 , v096
	.byte	W06
	.byte		N11   , Gn1 , v100
	.byte	W12
	.byte		N05   , Gn1 , v104
	.byte	W06
	.byte		        Gn1 , v092
	.byte	W06
	.byte		N11   , Gn1 , v108
	.byte	W12
	.byte		N05   , Gn1 , v092
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		N11   , Gn1 , v116
	.byte	W12
	.byte		N05   , Gn1 , v096
	.byte	W06
	.byte		        Gn1 , v076
	.byte	W06
	.byte		N11   , Gn1 , v084
	.byte	W12
	.byte		N05   , Gn1 , v104
	.byte	W06
	.byte		        Gn1 , v092
	.byte	W06
	.byte		N11
	.byte	W12
	.byte		N05   , Gn1 , v104
	.byte	W06
	.byte		        Gn1 , v100
	.byte	W06
	.byte		N11
	.byte	W12
	.byte		        Fn1 , v116
	.byte	W12
	.byte		N48   , Gn1 
	.byte	W96
	.byte	W84
	.byte		N05   , Gn1 , v112
	.byte	W06
	.byte		        Fn1 , v100
	.byte	W06
	.byte		N52   , Gn1 , v112
	.byte	W96
	.byte	W84
	.byte		N05
	.byte	W06
	.byte		        Fn1 , v104
	.byte	W06
	.byte		N54   , Gn1 , v120
	.byte	W96
	.byte	W84
	.byte		N05   , Gn1 , v112
	.byte	W06
	.byte		        Fn1 , v108
	.byte	W06
	.byte		N52   , Gn1 , v116
	.byte	W84
	.byte		N05   , Gn1 , v056
	.byte	W06
	.byte		        Fn1 , v080
	.byte	W06
	.byte		N11   , Gn1 , v084
	.byte	W12
	.byte		N05   , Gn1 , v068
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		N11   , Gn1 , v092
	.byte	W12
	.byte		N05   , Gn1 , v080
	.byte	W06
	.byte		        Gn1 , v072
	.byte	W06
	.byte		N11   , Gn1 , v084
	.byte	W12
	.byte		N05   , Gn1 , v092
	.byte	W06
	.byte		        Gn1 , v084
	.byte	W06
	.byte		N11   , Gn1 , v080
	.byte	W12
	.byte		        Gn1 , v100
	.byte	W12
	.byte	GOTO
	 .word	fe6_seq_012_4 + 0xD3
	.byte	FINE

@*********************** Track 06 ***********************@

fe6_seq_012_5:
	.byte	KEYSH , fe6_seq_012_key+0
	.byte		VOICE , 127
	.byte		VOL   , 57*fe6_seq_012_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		TIE   , An2 , v108
	.byte	W96
	.byte	W04
	.byte		EOT
	.byte	W80
	.byte		N11   , An2 , v072
	.byte	W12
	.byte		TIE   , An2 , v124
	.byte	W96
	.byte	W03
	.byte		EOT
	.byte	W92
	.byte	W01
	.byte	W96
	.byte	W84
	.byte		N11   , An2 , v100
	.byte	W12
	.byte		TIE   , An2 , v120
	.byte	W96
	.byte	W03
	.byte		EOT
	.byte	W24
	.byte	W03
	.byte		N05   , An2 , v056
	.byte	W06
	.byte		        An2 , v064
	.byte	W06
	.byte		        An2 , v056
	.byte	W06
	.byte		        An2 , v064
	.byte	W06
	.byte		        An2 , v068
	.byte	W06
	.byte		        An2 , v056
	.byte	W06
	.byte		        An2 , v068
	.byte	W06
	.byte		        An2 , v080
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		        An2 , v072
	.byte	W06
	.byte		        An2 , v088
	.byte	W06
	.byte		N05   , An2 , v112
	.byte	W06
	.byte		N84   , An2 , v104
	.byte	W90
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W42
	.byte		N05   , An2 , v040
	.byte	W06
	.byte		        An2 , v044
	.byte	W06
	.byte		        An2 , v064
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		        An2 , v056
	.byte	W06
	.byte		        An2 , v064
	.byte	W06
	.byte		        An2 , v068
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		        An2 , v084
	.byte	W06
	.byte		N72   , An2 , v112
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W60
	.byte		N11   , An2 , v036
	.byte	W12
	.byte		        An2 , v064
	.byte	W12
	.byte		        An2 , v076
	.byte	W12
	.byte		N80   , An2 , v120
	.byte	W84
	.byte		N11   , An2 , v096
	.byte	W12
	.byte		N80   , An2 , v108
	.byte	W84
	.byte		N11   , An2 , v100
	.byte	W12
	.byte		TIE   , An2 , v116
	.byte	W96
	.byte	W03
	.byte		EOT
	.byte	W80
	.byte	W01
	.byte		N11   , An2 , v100
	.byte	W12
	.byte		TIE   , An2 , v120
	.byte	W96
	.byte	W03
	.byte		EOT
	.byte	W92
	.byte	W01
	.byte	W96
	.byte	W48
	.byte		N05   , An2 , v032
	.byte	W06
	.byte		        An2 , v048
	.byte	W06
	.byte		        An2 , v044
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		        An2 , v052
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		        An2 , v056
	.byte	W06
	.byte		        An2 , v072
	.byte	W06
	.byte		TIE   , An2 , v112
	.byte	W96
	.byte	W03
	.byte		EOT
	.byte	W92
	.byte	W01
	.byte	W96
	.byte	W84
	.byte		N11   , An2 , v088
	.byte	W12
	.byte		TIE   , An2 , v108
	.byte	W96
	.byte	W03
	.byte		EOT
	.byte	W92
	.byte	W01
	.byte	W96
	.byte	W72
	.byte		N05   , An2 , v068
	.byte	W06
	.byte		        An2 , v060
	.byte	W06
	.byte		        An2 , v068
	.byte	W06
	.byte		        An2 , v080
	.byte	W06
	.byte	GOTO
	 .word	fe6_seq_012_5 + 0x4A
	.byte	FINE

@******************************************************@

	.align	2

fe6_seq_012:
	.byte	6	@ NumTrks
	.byte	0	@ NumBlks
	.byte	fe6_seq_012_pri	@ Priority
	.byte	fe6_seq_012_rev	@ Reverb

	.word	fe6_seq_012_grp

	.word	fe6_seq_012_0
	.word	fe6_seq_012_1
	.word	fe6_seq_012_2
	.word	fe6_seq_012_3
	.word	fe6_seq_012_4
	.word	fe6_seq_012_5

	.end
