@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	fe6_seq_018_grp, native_instrument_map_bin
	.equ	fe6_seq_018_pri, 10
	.equ	fe6_seq_018_rev, 158
	.equ	fe6_seq_018_mvl, 127
	.equ	fe6_seq_018_key, 0

	.section .rodata
	.global	fe6_seq_018
	.align	2

@*********************** Track 01 ***********************@

fe6_seq_018_0:
	.byte	KEYSH , fe6_seq_018_key+0
	.byte	TEMPO , 124/2
	.byte	W24
	.byte		VOICE , 1
	.byte		VOL   , 88*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N28   , Gs2 , v096
	.byte	W40
	.byte		N07   , As2 , v092
	.byte	W08
	.byte		N40   , Cn3 , v088
	.byte	W48
	.byte		N06   , Cs3 , v108
	.byte	W08
	.byte		N07   , As2 , v096
	.byte	W08
	.byte		        Cs3 , v104
	.byte	W08
	.byte		N52   , Cn3 , v108
	.byte	W72
	.byte		N32   , Cs3 , v116
	.byte	W40
	.byte		N07   , Cn3 , v096
	.byte	W08
	.byte		N28   , As2 , v100
	.byte	W40
	.byte		N07   , Gs2 , v088
	.byte	W08
	.byte		N76   , Cn3 , v096
	.byte	W96
	.byte		N32   , Gs2 , v104
	.byte	W40
	.byte		N07   , As2 , v092
	.byte	W08
	.byte		N40   , Cn3 
	.byte	W48
	.byte		N07   , Cs3 , v116
	.byte	W08
	.byte		        As2 , v084
	.byte	W08
	.byte		        Cs3 , v100
	.byte	W08
	.byte		N36   , Cn3 , v072
	.byte	W48
	.byte		N07   , Cn3 , v084
	.byte	W08
	.byte		        Cs3 , v112
	.byte	W08
	.byte		        Ds3 , v096
	.byte	W08
	.byte		N24   , Gs3 , v100
	.byte	W32
	.byte		N07   , Fs3 
	.byte	W08
	.byte		        En3 , v092
	.byte	W08
	.byte		N23   , Ds3 , v104
	.byte	W24
	.byte		        Cs3 , v108
	.byte	W24
	.byte		N44   , Ds3 , v112
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 1
	.byte		VOL   , 88*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N12   , Gs2 , v100
	.byte	W16
	.byte		N03   , Gs2 , v108
	.byte	W08
	.byte		N07   , Gs2 , v096
	.byte	W08
	.byte		        As2 , v108
	.byte	W08
	.byte		        Bn2 , v096
	.byte	W08
	.byte		N22   , As2 , v116
	.byte	W24
	.byte		N23   , Fs2 , v100
	.byte	W24
	.byte		N13   , Gs2 
	.byte	W16
	.byte		N03
	.byte	W08
	.byte		N07   , Gs2 , v092
	.byte	W08
	.byte		        As2 , v104
	.byte	W08
	.byte		        Bn2 , v100
	.byte	W08
	.byte		N23   , As2 , v116
	.byte	W24
	.byte		N11   , Cs3 , v104
	.byte	W16
	.byte		N07
	.byte	W08
	.byte		VOICE , 1
	.byte		N08   , Gs3 
	.byte	W08
	.byte		        Fs3 , v100
	.byte	W08
	.byte		        En3 , v096
	.byte	W08
	.byte		N14   , Fs3 , v108
	.byte	W24
	.byte		N08   , Fs3 , v116
	.byte	W08
	.byte		N07   , En3 , v100
	.byte	W08
	.byte		N08   , Dn3 , v088
	.byte	W08
	.byte		N17   , En3 , v092
	.byte	W24
	.byte		N07   , En3 , v104
	.byte	W08
	.byte		N08   , Dn3 , v088
	.byte	W08
	.byte		N09   , Cn3 
	.byte	W08
	.byte		N68   , Dn3 , v100
	.byte	W72
	.byte		N09   , Dn3 , v032
	.byte	W24
	.byte		VOICE , 58
	.byte		VOL   , 82*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N20   , Gs3 , v100
	.byte	W24
	.byte		N19   , Gs3 , v104
	.byte	W24
	.byte		N19
	.byte	W24
	.byte		N13   , Gs3 , v108
	.byte	W16
	.byte		N03   , Gs3 , v100
	.byte	W08
	.byte		N04   , Gs3 , v104
	.byte	W08
	.byte		        Gs3 , v096
	.byte	W08
	.byte		N04
	.byte	W08
	.byte		N11   , Gs3 , v112
	.byte	W16
	.byte		N03   , Gs3 , v100
	.byte	W08
	.byte		N05   , Gs3 , v104
	.byte	W08
	.byte		N04   , Gs3 , v096
	.byte	W08
	.byte		N03   , Gs3 , v100
	.byte	W08
	.byte		N11   , Gs3 , v108
	.byte	W16
	.byte		N03   , Gs3 , v096
	.byte	W08
	.byte		N04   , Gs3 , v108
	.byte	W08
	.byte		        Gs3 , v104
	.byte	W08
	.byte		        Gs3 , v092
	.byte	W08
	.byte		N11   , Gs3 , v112
	.byte	W16
	.byte		N03   , Gs3 , v108
	.byte	W08
	.byte		N03
	.byte	W08
	.byte		        Gs3 , v092
	.byte	W08
	.byte		        Gs3 , v100
	.byte	W08
	.byte		N14   , Gs3 , v104
	.byte	W24
	.byte		N03   , Gs3 , v096
	.byte	W08
	.byte		N04   , Gs3 , v108
	.byte	W08
	.byte		        Gs3 , v104
	.byte	W08
	.byte		        Gs3 , v092
	.byte	W08
	.byte		N11   , Gs3 , v112
	.byte	W16
	.byte		N03   , Gs3 , v108
	.byte	W08
	.byte		        Gs3 , v092
	.byte	W08
	.byte		        Gs3 , v100
	.byte	W08
	.byte		N08   , Gs3 , v104
	.byte	W24
	.byte	GOTO
	 .word	fe6_seq_018_0 + 0x5
	.byte	FINE

@*********************** Track 02 ***********************@

fe6_seq_018_1:
	.byte	KEYSH , fe6_seq_018_key+0
	.byte	W24
	.byte		VOICE , 58
	.byte		VOL   , 91*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N10   , Gs3 , v092
	.byte	W16
	.byte		N03   , Gs3 , v100
	.byte	W08
	.byte		N08   , Gs3 , v084
	.byte	W16
	.byte		N03   , Gs3 , v108
	.byte	W08
	.byte		N07   , Gs3 , v104
	.byte	W16
	.byte		N02   , Gs3 , v112
	.byte	W08
	.byte		N08   , Gs3 , v100
	.byte	W16
	.byte		N02   , Gs3 , v112
	.byte	W08
	.byte		N09   , Gs3 , v104
	.byte	W16
	.byte		N03
	.byte	W08
	.byte		N09   , Gs3 , v100
	.byte	W16
	.byte		N02   , Gs3 , v108
	.byte	W08
	.byte		N06   , Gs3 , v104
	.byte	W16
	.byte		N03   , Gs3 , v112
	.byte	W08
	.byte		N06   , Gs3 , v104
	.byte	W16
	.byte		N04   , Gs3 , v112
	.byte	W08
	.byte		N11   , Fs3 
	.byte	W16
	.byte		N03
	.byte	W08
	.byte		N10   , Fs3 , v104
	.byte	W16
	.byte		N04   , Fs3 , v108
	.byte	W08
	.byte		N08   , Fs3 , v100
	.byte	W16
	.byte		N03   , Fs3 , v108
	.byte	W08
	.byte		N08   , Fs3 , v104
	.byte	W16
	.byte		N03
	.byte	W08
	.byte		N09   , Gs3 , v096
	.byte	W16
	.byte		N03   , Gs3 , v108
	.byte	W08
	.byte		N07   , Gs3 , v104
	.byte	W16
	.byte		N03   , Gs3 , v112
	.byte	W08
	.byte		N09   , Gs3 , v100
	.byte	W16
	.byte		N04   , Gs3 , v108
	.byte	W08
	.byte		N09   , Gs3 , v112
	.byte	W16
	.byte		N05   , Ds3 , v096
	.byte	W08
	.byte		N11   , Gs3 , v112
	.byte	W16
	.byte		N04   , Gs3 , v100
	.byte	W08
	.byte		N11   , Gs3 , v104
	.byte	W16
	.byte		N03
	.byte	W08
	.byte		N11   , Gs3 , v116
	.byte	W16
	.byte		N03   , Gs3 , v100
	.byte	W08
	.byte		N09   , Gs3 , v104
	.byte	W16
	.byte		N04
	.byte	W08
	.byte		N11
	.byte	W16
	.byte		N04
	.byte	W08
	.byte		N10
	.byte	W16
	.byte		N03
	.byte	W08
	.byte		N09
	.byte	W16
	.byte		N03   , Gs3 , v112
	.byte	W08
	.byte		N11   , Gs3 , v116
	.byte	W16
	.byte		N03   , Fs3 , v108
	.byte	W08
	.byte		N13   , En3 
	.byte	W16
	.byte		N03   , En3 , v104
	.byte	W08
	.byte		N12
	.byte	W16
	.byte		N03   , En3 , v100
	.byte	W08
	.byte		N11   , Fs3 
	.byte	W16
	.byte		N03   , Fs3 , v108
	.byte	W08
	.byte		N11
	.byte	W16
	.byte		N03   , Fs3 , v104
	.byte	W08
	.byte		N11   , Gs3 , v108
	.byte	W16
	.byte		N04   , Gs3 , v104
	.byte	W08
	.byte		N11
	.byte	W16
	.byte		N03
	.byte	W08
	.byte		N12
	.byte	W16
	.byte		N04   , Gs3 , v096
	.byte	W08
	.byte		VOICE , 58
	.byte		VOL   , 82*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N11   , Gs3 , v104
	.byte	W16
	.byte		N04   , Fs3 , v096
	.byte	W08
	.byte		N44   , En3 , v124
	.byte	W48
	.byte		        Fs3 , v104
	.byte	W48
	.byte		        En3 , v108
	.byte	W48
	.byte		N36   , Fs3 , v100
	.byte	W40
	.byte		N05   , Fs3 , v104
	.byte	W08
	.byte		N44   , En3 , v092
	.byte	W48
	.byte		        Fs3 , v116
	.byte	W48
	.byte		N36   , En3 
	.byte	W40
	.byte		N07   , En3 , v088
	.byte	W08
	.byte		N21   , Fs3 , v108
	.byte	W24
	.byte		N23   , Fs3 , v104
	.byte	W24
	.byte		N36   , En3 , v096
	.byte	W40
	.byte		N07   , En3 , v100
	.byte	W08
	.byte		N36   , Fs3 
	.byte	W40
	.byte		N06
	.byte	W08
	.byte		N44   , En3 , v104
	.byte	W48
	.byte		N32   , Fs3 , v108
	.byte	W24
	.byte		VOICE , 45
	.byte		VOL   , 82*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W24
	.byte		N21
	.byte	W24
	.byte		N23   , Fs3 , v104
	.byte	W24
	.byte		N21   , Fs3 , v108
	.byte	W24
	.byte		N23   , Fs3 , v104
	.byte	W24
	.byte		N21   , En3 , v108
	.byte	W24
	.byte		N23   , En3 , v104
	.byte	W24
	.byte		N21   , Dn3 , v108
	.byte	W24
	.byte		N23   , Dn3 , v104
	.byte	W24
	.byte	W24
	.byte		        Gs2 
	.byte	W24
	.byte		N21   , Gs2 , v108
	.byte	W24
	.byte		N23   , Gs2 , v104
	.byte	W24
	.byte		N21   , Gs2 , v108
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	fe6_seq_018_1 + 0x3
	.byte	FINE

@*********************** Track 03 ***********************@

fe6_seq_018_2:
	.byte	KEYSH , fe6_seq_018_key+0
	.byte	W24
	.byte		VOICE , 48
	.byte		VOL   , 70*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+10
	.byte		N28   , Ds3 , v096
	.byte	W40
	.byte		N07   , Ds3 , v092
	.byte	W08
	.byte		N40   , Ds3 , v088
	.byte	W48
	.byte		N06   , Ds3 , v108
	.byte	W08
	.byte		N07   , Ds3 , v096
	.byte	W08
	.byte		        Ds3 , v104
	.byte	W08
	.byte		N52   , Ds3 , v108
	.byte	W72
	.byte		N32   , En3 , v116
	.byte	W40
	.byte		N07   , En3 , v096
	.byte	W08
	.byte		N28   , En3 , v100
	.byte	W40
	.byte		N07   , En3 , v088
	.byte	W08
	.byte		N76   , Ds3 , v096
	.byte	W96
	.byte		N32   , Ds3 , v104
	.byte	W40
	.byte		N07   , Ds3 , v092
	.byte	W08
	.byte		N40
	.byte	W48
	.byte		N07   , Ds3 , v116
	.byte	W08
	.byte		        Ds3 , v084
	.byte	W08
	.byte		        Ds3 , v100
	.byte	W08
	.byte		N36   , Ds3 , v072
	.byte	W48
	.byte		N07   , Gs3 , v084
	.byte	W08
	.byte		        Gs3 , v112
	.byte	W08
	.byte		        Gs3 , v096
	.byte	W08
	.byte		N24   , En3 , v100
	.byte	W32
	.byte		N07
	.byte	W08
	.byte		        En3 , v092
	.byte	W08
	.byte		N17   , Fs3 
	.byte	W24
	.byte		N17
	.byte	W24
	.byte		N44   , Gs3 , v096
	.byte	W72
	.byte		VOICE , 48
	.byte		VOL   , 105*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W24
	.byte		N11   , Gs2 , v112
	.byte	W12
	.byte		N03   , Gs2 , v096
	.byte	W12
	.byte		N07   , Gs2 , v092
	.byte	W08
	.byte		        As2 
	.byte	W08
	.byte		        Bn2 , v100
	.byte	W08
	.byte		N23   , As2 
	.byte	W24
	.byte		        Fs2 
	.byte	W24
	.byte		N13   , Gs2 , v104
	.byte	W16
	.byte		N04   , Gs2 , v096
	.byte	W08
	.byte		N07   , Gs2 , v100
	.byte	W08
	.byte		        As2 , v096
	.byte	W08
	.byte		        Bn2 , v104
	.byte	W08
	.byte		N23   , As2 , v100
	.byte	W24
	.byte		        Cs3 , v108
	.byte	W24
	.byte		N12   , Gs2 , v112
	.byte	W16
	.byte		N03   , Gs2 , v104
	.byte	W08
	.byte		N05   , Gs2 , v096
	.byte	W08
	.byte		N07   , As2 , v092
	.byte	W08
	.byte		        Bn2 , v100
	.byte	W08
	.byte		N21   , As2 
	.byte	W24
	.byte		N23   , Fs2 
	.byte	W24
	.byte		N12   , Gs2 
	.byte	W16
	.byte		N03   , Gs2 , v104
	.byte	W08
	.byte		N06   , Gs2 , v096
	.byte	W08
	.byte		N07   , As2 
	.byte	W08
	.byte		        Bn2 
	.byte	W08
	.byte		N23   , As2 , v104
	.byte	W24
	.byte		N20   , Cs3 
	.byte	W24
	.byte		N12   , Bn2 , v100
	.byte	W16
	.byte		N03   , Bn2 , v108
	.byte	W08
	.byte		N07   , Bn2 , v096
	.byte	W08
	.byte		        Cs3 , v108
	.byte	W08
	.byte		        Ds3 , v096
	.byte	W08
	.byte		N22   , Cs3 , v116
	.byte	W24
	.byte		N23   , As2 , v100
	.byte	W24
	.byte		N13   , Bn2 
	.byte	W16
	.byte		N03
	.byte	W08
	.byte		N07   , Bn2 , v092
	.byte	W08
	.byte		        Cs3 , v104
	.byte	W08
	.byte		        Ds3 , v100
	.byte	W08
	.byte		N23   , Cs3 , v116
	.byte	W24
	.byte		N11   , Fs3 , v104
	.byte	W16
	.byte		N07
	.byte	W08
	.byte		N08   , Gs3 
	.byte	W08
	.byte		        Fs3 , v100
	.byte	W08
	.byte		        En3 , v096
	.byte	W08
	.byte		N14   , Fs3 , v108
	.byte	W24
	.byte		N08   , Fs3 , v116
	.byte	W08
	.byte		N07   , En3 , v100
	.byte	W08
	.byte		N08   , Dn3 , v088
	.byte	W08
	.byte		N17   , En3 , v092
	.byte	W24
	.byte		N07   , En3 , v104
	.byte	W08
	.byte		N08   , Dn3 , v088
	.byte	W08
	.byte		N09   , Cn3 
	.byte	W08
	.byte		N68   , Dn3 , v100
	.byte	W72
	.byte		N07   , Dn3 , v032
	.byte	W24
	.byte		VOICE , 61
	.byte		VOL   , 82*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W72
	.byte		N08   , Gs2 , v116
	.byte	W24
	.byte		N09
	.byte	W24
	.byte		N03
	.byte	W08
	.byte		        Gs2 , v108
	.byte	W08
	.byte		N03
	.byte	W08
	.byte		N08
	.byte	W24
	.byte		        Gs2 , v116
	.byte	W24
	.byte		N09
	.byte	W24
	.byte		N03
	.byte	W08
	.byte		        Gs2 , v108
	.byte	W08
	.byte		N03
	.byte	W08
	.byte		N08
	.byte	W24
	.byte		N09   , Gs2 , v124
	.byte	W24
	.byte		N03
	.byte	W08
	.byte		        Gs2 , v108
	.byte	W08
	.byte		        Gs2 , v104
	.byte	W08
	.byte		N06   , Gs2 , v124
	.byte	W24
	.byte		N07   , Gs2 , v120
	.byte	W24
	.byte		        Gs2 , v127
	.byte	W24
	.byte	GOTO
	 .word	fe6_seq_018_2 + 0x3
	.byte	FINE

@*********************** Track 04 ***********************@

fe6_seq_018_3:
	.byte	KEYSH , fe6_seq_018_key+0
	.byte	W24
	.byte		VOICE , 48
	.byte		VOL   , 82*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N12   , Gs1 , v100
	.byte	W12
	.byte		        Gs1 , v028
	.byte	W36
	.byte		        Gs1 , v100
	.byte	W12
	.byte		        Gs1 , v028
	.byte	W36
	.byte		        Gs1 , v100
	.byte	W12
	.byte		        Gs1 , v028
	.byte	W36
	.byte		        Gs1 , v100
	.byte	W12
	.byte		        Gs1 , v028
	.byte	W36
	.byte		        Fs1 , v100
	.byte	W12
	.byte		        Fs1 , v028
	.byte	W36
	.byte		        Fs1 , v100
	.byte	W12
	.byte		        Fs1 , v028
	.byte	W36
	.byte		        Gs1 , v100
	.byte	W12
	.byte		        Gs1 , v028
	.byte	W36
	.byte		        Gs1 , v100
	.byte	W12
	.byte		        Gs1 , v028
	.byte	W12
	.byte		N07   , Gs3 , v108
	.byte	W08
	.byte		        Ds3 
	.byte	W08
	.byte		        Cn3 , v092
	.byte	W08
	.byte		TIE   , Gs2 , v108
	.byte	W96
	.byte	W92
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N44   , En2 , v104
	.byte	W48
	.byte		        Cs2 , v100
	.byte	W48
	.byte		N68   , Cn2 , v112
	.byte	W72
	.byte		VOICE , 48
	.byte		VOL   , 82*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N07   , Gs2 , v096
	.byte	W08
	.byte		        Cn3 , v088
	.byte	W08
	.byte		        Ds3 , v108
	.byte	W08
	.byte		N44   , Gs2 
	.byte	W48
	.byte		        Fs2 , v104
	.byte	W48
	.byte		        Gs2 , v100
	.byte	W48
	.byte		        Fs2 , v108
	.byte	W48
	.byte		        Gs2 , v104
	.byte	W48
	.byte		        Fs2 , v112
	.byte	W48
	.byte		        Gs2 , v104
	.byte	W48
	.byte		        Fs2 , v116
	.byte	W48
	.byte		        Gs2 , v104
	.byte	W48
	.byte		        Fs2 
	.byte	W48
	.byte		        Gs2 , v108
	.byte	W48
	.byte		        As2 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W24
	.byte		VOICE , 61
	.byte		VOL   , 82*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W72
	.byte		N06   , Ds2 
	.byte	W24
	.byte		N07   , Ds2 , v116
	.byte	W24
	.byte		N02   , Ds2 , v108
	.byte	W08
	.byte		N02
	.byte	W08
	.byte		N02
	.byte	W08
	.byte		N07
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N07   , Ds2 , v116
	.byte	W24
	.byte		N02   , Ds2 , v108
	.byte	W08
	.byte		N02
	.byte	W08
	.byte		N02
	.byte	W08
	.byte		N07
	.byte	W24
	.byte		N08   , Ds2 , v124
	.byte	W24
	.byte		N02   , Ds2 , v116
	.byte	W08
	.byte		        Ds2 , v108
	.byte	W08
	.byte		        Ds2 , v104
	.byte	W08
	.byte		N05   , Ds2 , v127
	.byte	W24
	.byte		N06   , Ds2 , v124
	.byte	W24
	.byte		N06
	.byte	W24
	.byte	GOTO
	 .word	fe6_seq_018_3 + 0x3
	.byte	FINE

@*********************** Track 05 ***********************@

fe6_seq_018_4:
	.byte	KEYSH , fe6_seq_018_key+0
	.byte		VOICE , 60
	.byte		VOL   , 100*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v-22
	.byte		N23   , Ds2 , v112
	.byte	W24
	.byte		N84   , Gs2 , v116
	.byte	W88
	.byte		N07   , Ds3 , v084
	.byte	W08
	.byte		        Gs2 , v112
	.byte	W16
	.byte		N06   , Ds3 , v104
	.byte	W08
	.byte		N68   , Gs2 , v120
	.byte	W72
	.byte		N28   , En2 
	.byte	W40
	.byte		N07   , Ds2 , v092
	.byte	W08
	.byte		N32   , Cs2 , v116
	.byte	W40
	.byte		N07   , Cn2 , v096
	.byte	W08
	.byte		N68   , Ds2 , v116
	.byte	W96
	.byte		N72   , Gs2 , v112
	.byte	W88
	.byte		N07   , Ds3 , v100
	.byte	W08
	.byte		        Gs2 , v124
	.byte	W16
	.byte		N06   , Ds3 , v108
	.byte	W08
	.byte		N68   , Gs2 , v124
	.byte	W72
	.byte		N44   , En2 , v116
	.byte	W48
	.byte		        Fs2 , v120
	.byte	W48
	.byte		N60   , Gs2 , v116
	.byte	W72
	.byte		VOICE , 60
	.byte		VOL   , 100*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W24
	.byte		N44   , Bn2 , v104
	.byte	W48
	.byte		        As2 , v112
	.byte	W48
	.byte		N48   , Bn2 , v108
	.byte	W96
	.byte		N42   , Gs2 , v104
	.byte	W48
	.byte		N40   , Fs2 , v108
	.byte	W48
	.byte		N44   , Gs2 , v100
	.byte	W96
	.byte		N36   , Gs2 , v096
	.byte	W48
	.byte		        Fs2 , v104
	.byte	W48
	.byte		N40   , Gs2 , v096
	.byte	W48
	.byte		        As2 , v104
	.byte	W24
	.byte		VOICE , 58
	.byte		VOL   , 100*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W24
	.byte		N19   , Dn3 , v096
	.byte	W24
	.byte		N20   , An3 , v120
	.byte	W24
	.byte		N19   , Cn3 , v112
	.byte	W24
	.byte		N18   , Gn3 , v116
	.byte	W24
	.byte		N17   , As2 , v112
	.byte	W24
	.byte		N18   , Fn3 
	.byte	W24
	.byte		N16   , Dn3 , v120
	.byte	W24
	.byte		N17   , An2 , v112
	.byte	W24
	.byte		VOICE , 60
	.byte		VOL   , 100*fe6_seq_018_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W24
	.byte		TIE   , Ds2 , v100
	.byte		TIE   , Gs2 , v104
	.byte	W96
	.byte	W48
	.byte	W02
	.byte		EOT
	.byte	W02
	.byte		EOT   , Ds2 
	.byte	W44
	.byte		N78   , Cn3 , v112
	.byte	W88
	.byte		N06   , Cs3 , v104
	.byte	W08
	.byte		N56   , Ds3 
	.byte	W96
	.byte	GOTO
	 .word	fe6_seq_018_4 + 0xC
	.byte	FINE

@******************************************************@

	.align	2

fe6_seq_018:
	.byte	5	@ NumTrks
	.byte	0	@ NumBlks
	.byte	fe6_seq_018_pri	@ Priority
	.byte	fe6_seq_018_rev	@ Reverb

	.word	fe6_seq_018_grp

	.word	fe6_seq_018_0
	.word	fe6_seq_018_1
	.word	fe6_seq_018_2
	.word	fe6_seq_018_3
	.word	fe6_seq_018_4

	.end
