@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	fe8_seq_014_grp, native_instrument_map_bin
	.equ	fe8_seq_014_pri, 10
	.equ	fe8_seq_014_rev, 148
	.equ	fe8_seq_014_mvl, 127
	.equ	fe8_seq_014_key, 0

	.section .rodata
	.global	fe8_seq_014
	.align	2

@*********************** Track 01 ***********************@

fe8_seq_014_0:
	.byte	KEYSH , fe8_seq_014_key+0
	.byte	TEMPO , 66/2
	.byte		VOICE , 6
	.byte		VOL   , 34*fe8_seq_014_mvl/mxv
	.byte		PAN   , c_v+40
	.byte		N06   , Ds2 , v104
	.byte	W06
	.byte		        Fn2 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Fn2 
	.byte	W06
	.byte		        Ds2 
	.byte	W06
	.byte		        As1 
	.byte	W06
	.byte		        Bn1 
	.byte	W06
	.byte		        Cs2 
	.byte	W06
	.byte		        Bn1 
	.byte	W06
	.byte		        As1 
	.byte	W06
	.byte		N06   , Ds2 , v104
	.byte	W06
	.byte		        Fn2 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Fn2 
	.byte	W06
	.byte		        Ds2 
	.byte	W06
	.byte		        Fn2 
	.byte	W06
	.byte		        Cs2 
	.byte	W06
	.byte		        Ds2 
	.byte	W06
	.byte		        Bn1 
	.byte	W06
	.byte		        Cs2 
	.byte	W06
	.byte	PEND
	.byte		N06   , Ds2 , v104
	.byte	W06
	.byte		        Fn2 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Fn2 
	.byte	W06
	.byte		        Ds2 
	.byte	W06
	.byte		        As1 
	.byte	W06
	.byte		        Bn1 
	.byte	W06
	.byte		        Cs2 
	.byte	W06
	.byte		        Bn1 
	.byte	W06
	.byte		        As1 
	.byte	W06
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x24
	.byte		N06   , En2 , v104
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte		        As2 
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        En2 
	.byte	W06
	.byte		        Bn1 
	.byte	W06
	.byte		        Cs2 
	.byte	W06
	.byte		        Ds2 
	.byte	W06
	.byte		        Cs2 
	.byte	W06
	.byte		        Bn1 
	.byte	W06
	.byte	PEND
	.byte		N06   , En2 , v104
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte		        As2 
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        En2 
	.byte	W06
	.byte		        Cs2 
	.byte	W06
	.byte		        Ds2 
	.byte	W06
	.byte		        En2 
	.byte	W06
	.byte		        Ds2 
	.byte	W06
	.byte		        Cs2 
	.byte	W06
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x3F
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x24
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x5F
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x7A
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x3F
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x24
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x5F
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x7A
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x3F
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x24
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x5F
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x7A
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x3F
	.byte	PATT
	 .word	fe8_seq_014_0 + 0x24
	.byte	GOTO
	 .word	fe8_seq_014_0 + 0x3F
	.byte	FINE

@*********************** Track 02 ***********************@

fe8_seq_014_1:
	.byte	KEYSH , fe8_seq_014_key+0
	.byte		VOICE , 33
	.byte		VOL   , 47*fe8_seq_014_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N06   , Ds2 , v127
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N06   , Ds2 , v127
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte		N06   , Ds2 , v127
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N06
	.byte	W18
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x12
	.byte		N06   , En2 , v127
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N06
	.byte	W18
	.byte	PEND
	.byte		N06   , En2 , v127
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x1F
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x12
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x2F
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x3A
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x1F
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x12
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x2F
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x3A
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x1F
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x12
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x2F
	.byte		N06   , En2 , v127
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N06
	.byte	W12
	.byte		        Ds2 
	.byte	W12
	.byte		        Cs2 
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x12
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x12
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x12
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x12
	.byte		N06   , Bn1 , v127
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x9E
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x9E
	.byte		N06   , Bn1 , v127
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		        As1 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x1F
	.byte	PATT
	 .word	fe8_seq_014_1 + 0x12
	.byte	GOTO
	 .word	fe8_seq_014_1 + 0x1F
	.byte	FINE

@*********************** Track 03 ***********************@

fe8_seq_014_2:
	.byte	KEYSH , fe8_seq_014_key+0
	.byte		VOICE , 19
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		TIE   , Ds2 , v112
	.byte	W72
	.byte	W72
	.byte		EOT
	.byte		N28   , Ds2 , v116
	.byte	W30
	.byte		N02   , As2 
	.byte	W06
	.byte		N44   , As2 , v120
	.byte	W36
	.byte	W18
	.byte		N17   , Gs2 , v127
	.byte	W18
	.byte		        As2 , v116
	.byte	W18
	.byte		        Bn2 , v112
	.byte	W18
	.byte		N28   , As2 , v120
	.byte	W30
	.byte		N05   , Gs2 , v116
	.byte	W06
	.byte		N52   , Fs2 , v120
	.byte	W36
	.byte	W18
	.byte		N17   , Gs2 , v116
	.byte	W18
	.byte		        Fs2 , v112
	.byte	W18
	.byte		        En2 , v108
	.byte	W18
	.byte		N32   , Ds2 , v080
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte		N36   , Ds2 , v127
	.byte	W36
	.byte		N12   , Fn2 
	.byte	W12
	.byte		        Fs2 
	.byte	W12
	.byte		        Ds2 
	.byte	W12
	.byte		N48   , Fn2 
	.byte	W54
	.byte		N18   , Cs2 
	.byte	W18
	.byte		N36   , Fs2 
	.byte	W36
	.byte		N12   , Gs2 
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		        Fs2 
	.byte	W12
	.byte		N66   , Gs2 
	.byte	W72
	.byte		N36   , Fs2 
	.byte	W36
	.byte		N12   , Gs2 
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		        Bn2 
	.byte	W12
	.byte		N30   , As2 
	.byte	W36
	.byte		N12
	.byte	W12
	.byte		        Gs2 
	.byte	W12
	.byte		        Fs2 
	.byte	W12
	.byte		N72   , Gs2 
	.byte	W72
	.byte		N36   , Cs3 
	.byte	W36
	.byte		        Bn2 
	.byte	W36
	.byte		N06   , Ds3 , v112
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		        Gs3 
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		        As2 
	.byte	W06
	.byte		        Bn2 
	.byte	W06
	.byte		        Cs3 
	.byte	W06
	.byte		        Bn2 
	.byte	W06
	.byte		        As2 
	.byte	W06
	.byte	PEND
	.byte		        En3 
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		        Gs3 
	.byte	W06
	.byte		        As3 
	.byte	W06
	.byte		        Gs3 
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		        En3 
	.byte	W06
	.byte		        Cs3 
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		        En3 
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		        Cs3 
	.byte	W06
	.byte	PATT
	 .word	fe8_seq_014_2 + 0x7D
	.byte		N06   , Ds3 , v112
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		        Gs3 
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        Cs3 
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		        Bn2 
	.byte	W06
	.byte		        Cs3 
	.byte	W06
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_014_2 + 0x7D
	.byte	PATT
	 .word	fe8_seq_014_2 + 0xB5
	.byte	PATT
	 .word	fe8_seq_014_2 + 0x7D
	.byte	PATT
	 .word	fe8_seq_014_2 + 0xB5
	.byte		N60   , As2 , v112
	.byte	W66
	.byte		N06   , Ds2 
	.byte	W06
	.byte		N72
	.byte	W72
	.byte	GOTO
	 .word	fe8_seq_014_2 + 0xE
	.byte	FINE

@*********************** Track 04 ***********************@

fe8_seq_014_3:
	.byte	KEYSH , fe8_seq_014_key+0
	.byte		VOICE , 51
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte		PAN   , c_v-6
	.byte		N68   , Ds2 , v096
	.byte		TIE   , As2 
	.byte	W72
	.byte	W36
	.byte		N17   , Ds3 
	.byte	W18
	.byte		        As3 
	.byte	W17
	.byte		EOT   , As2 
	.byte	W01
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		VOICE , 49
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte		PAN   , c_v-8
	.byte	W72
	.byte		N30   , Ds2 , v104
	.byte	W30
	.byte		N03   , Fn2 , v096
	.byte		N03   , As2 
	.byte	W06
	.byte		N48   , Fn2 , v092
	.byte		N48   , As2 
	.byte	W36
	.byte	W18
	.byte		N15   , Ds2 , v100
	.byte		N18   , Gs2 
	.byte	W18
	.byte		N15   , Fn2 , v096
	.byte		N18   , As2 
	.byte	W18
	.byte		N15   , As2 , v100
	.byte		N18   , Ds3 
	.byte	W18
	.byte		N60   , Gs2 , v108
	.byte		N66   , Cs3 
	.byte	W66
	.byte		N06   , Fs2 , v100
	.byte		N06   , Bn2 
	.byte	W06
	.byte		N32   , Gs2 , v104
	.byte		N36   , Cs3 
	.byte	W36
	.byte		N15   , Cs2 , v100
	.byte		N18   , Fs2 
	.byte	W18
	.byte		N15   , Bn1 
	.byte		N18   , En2 
	.byte	W18
	.byte		N03   , Ds2 , v104
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v088
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v104
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v088
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v104
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v088
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v104
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v088
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 
	.byte		N03   , As2 
	.byte	W06
	.byte	PEND
	.byte		N03   , Ds2 , v104
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v088
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v104
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v088
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v104
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v088
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v104
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v088
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v104
	.byte		N03   , As2 
	.byte	W06
	.byte		        Ds2 , v088
	.byte		N03   , As2 
	.byte	W06
	.byte	PEND
	.byte		N03   , En2 , v104
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v088
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v104
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v088
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v104
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v088
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v104
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v088
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 
	.byte		N03   , Bn2 
	.byte	W06
	.byte	PEND
	.byte		N03   , En2 , v104
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v088
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v104
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v088
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v104
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v088
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v104
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v088
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v104
	.byte		N03   , Bn2 
	.byte	W06
	.byte		        En2 , v088
	.byte		N03   , Bn2 
	.byte	W06
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_014_3 + 0x61
	.byte	PATT
	 .word	fe8_seq_014_3 + 0x9B
	.byte	PATT
	 .word	fe8_seq_014_3 + 0xD7
	.byte	PATT
	 .word	fe8_seq_014_3 + 0x111
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		VOICE , 51
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte		PAN   , c_v-6
	.byte	W72
	.byte		N68   , As2 , v100
	.byte	W36
	.byte		N17   , Ds3 
	.byte	W18
	.byte		        As3 
	.byte	W18
	.byte	GOTO
	 .word	fe8_seq_014_3 + 0x17
	.byte	FINE

@*********************** Track 05 ***********************@

fe8_seq_014_4:
	.byte	KEYSH , fe8_seq_014_key+0
	.byte	W72
	.byte	W72
	.byte		VOICE , 53
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		TIE   , Ds2 , v096
	.byte		TIE   , As2 
	.byte	W72
	.byte	W68
	.byte		EOT   , Ds2 
	.byte	W03
	.byte		        As2 
	.byte	W01
	.byte		TIE   , En2 , v096
	.byte		TIE   , Bn2 
	.byte	W72
	.byte	PEND
	.byte	W68
	.byte		EOT   , En2 
	.byte	W03
	.byte		        Bn2 
	.byte	W01
	.byte		TIE   , Ds2 
	.byte		TIE   , As2 
	.byte	W72
	.byte	W68
	.byte		EOT   , Ds2 
	.byte	W03
	.byte		        As2 
	.byte	W01
	.byte	PATT
	 .word	fe8_seq_014_4 + 0x16
	.byte	W68
	.byte		EOT   , En2 
	.byte	W03
	.byte		        Bn2 
	.byte	W01
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		VOICE , 53
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N68   , Ds2 , v100
	.byte		N72   , As2 , v116
	.byte	W72
	.byte		N68   , En2 , v100
	.byte		N36   , Cs3 , v116
	.byte	W36
	.byte		N32   , Bn2 , v127
	.byte	W36
	.byte		N68   , Ds2 , v100
	.byte		N72   , As2 , v124
	.byte	W72
	.byte		N32   , Ds2 , v100
	.byte		N36   , Gs2 , v116
	.byte	W36
	.byte		N32   , Ds2 , v104
	.byte		N32   , Fs2 , v124
	.byte	W36
	.byte		N68   , Fs2 , v100
	.byte		N72   , Bn2 , v124
	.byte	W72
	.byte		N68   , Fs2 , v100
	.byte		N36   , As2 , v124
	.byte	W36
	.byte		        Bn2 
	.byte	W36
	.byte		N68   , Fs2 , v100
	.byte		N72   , As2 , v124
	.byte	W72
	.byte		N32   , Bn2 , v100
	.byte		N24   , Cs3 , v124
	.byte	W24
	.byte		N06
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		N32   , As2 , v100
	.byte		N32   , Fn3 , v124
	.byte	W36
	.byte		N68   , Ds3 
	.byte	W72
	.byte	W72
	.byte	GOTO
	 .word	fe8_seq_014_4 + 0x4
	.byte	FINE

@*********************** Track 06 ***********************@

fe8_seq_014_5:
	.byte	KEYSH , fe8_seq_014_key+0
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		VOICE , 48
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte		PAN   , c_v-20
	.byte	W72
	.byte		VOL   , 31*fe8_seq_014_mvl/mxv
	.byte		N42   , Fn3 , v080
	.byte	W05
	.byte		VOL   , 32*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        53*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        55*fe8_seq_014_mvl/mxv
	.byte	W21
	.byte		N06   , Fn3 , v028
	.byte	W06
	.byte		N12   , As2 , v080
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		N48   , As3 
	.byte	W32
	.byte	W03
	.byte		VOL   , 54*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        52*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        31*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        29*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        55*fe8_seq_014_mvl/mxv
	.byte		N12   , Ds3 
	.byte	W12
	.byte		N06   , Ds3 , v028
	.byte	W06
	.byte		N36   , Gs3 , v080
	.byte	W36
	.byte		        Fs3 
	.byte	W36
	.byte		        En3 
	.byte	W32
	.byte	W02
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte	W02
	.byte		        54*fe8_seq_014_mvl/mxv
	.byte		N18   , Ds3 
	.byte	W01
	.byte		VOL   , 54*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        53*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        53*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        52*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        52*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_014_mvl/mxv
	.byte		N18   , Cs3 
	.byte	W01
	.byte		VOL   , 46*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_014_mvl/mxv
	.byte		N36   , Ds3 
	.byte	W01
	.byte		VOL   , 41*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        52*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        53*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        53*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        54*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        55*fe8_seq_014_mvl/mxv
	.byte	W12
	.byte		N12   , Fn3 
	.byte	W12
	.byte		        Fs3 
	.byte	W12
	.byte		        Gs3 
	.byte	W12
	.byte		N18   , Fs3 
	.byte	W18
	.byte		        As3 
	.byte	W18
	.byte		N36   , Ds4 
	.byte	W22
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        54*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        53*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        52*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_014_mvl/mxv
	.byte		N36   , Cs4 
	.byte	W01
	.byte		VOL   , 45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        52*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        53*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        54*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        55*fe8_seq_014_mvl/mxv
	.byte	W21
	.byte		N18   , Bn3 
	.byte	W18
	.byte		        As3 
	.byte	W18
	.byte		N66   , Gs3 
	.byte	W36
	.byte	W02
	.byte		VOL   , 54*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        52*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        30*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        29*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        28*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        27*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        25*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        24*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        23*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        22*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        21*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        19*fe8_seq_014_mvl/mxv
	.byte		N06   , Gs3 , v028
	.byte	W01
	.byte		VOL   , 18*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        17*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        16*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        15*fe8_seq_014_mvl/mxv
	.byte	W02
	.byte	W72
	.byte	W72
	.byte		        55*fe8_seq_014_mvl/mxv
	.byte	W54
	.byte		N05   , Ds3 , v096
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		N14   , Ds3 , v080
	.byte		N17   , Fs3 , v096
	.byte	W18
	.byte		N14   , Fn3 , v080
	.byte		N17   , Gs3 , v096
	.byte	W18
	.byte		N14   , Fs3 , v076
	.byte		N17   , As3 , v092
	.byte	W18
	.byte		N14   , As3 , v068
	.byte		N17   , Ds4 , v084
	.byte	W18
	.byte		N56   , As3 , v068
	.byte		N56   , Ds4 , v084
	.byte	W60
	.byte		N05   , Cs4 , v068
	.byte	W06
	.byte		        Bn3 
	.byte	W06
	.byte		N32   , As3 
	.byte		N32   , Cs4 , v084
	.byte	W36
	.byte		        Bn3 , v068
	.byte		N32   , Ds4 , v084
	.byte	W36
	.byte		N68   , Fs3 , v072
	.byte		N68   , As3 , v088
	.byte	W72
	.byte		N32   , Cs3 , v080
	.byte		N32   , Fn3 , v096
	.byte	W36
	.byte		        Gs2 , v080
	.byte		N32   , Cs3 , v096
	.byte	W36
	.byte		TIE   , As2 , v080
	.byte		TIE   , Ds3 , v096
	.byte	W44
	.byte	W03
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        54*fe8_seq_014_mvl/mxv
	.byte	W02
	.byte		        54*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        53*fe8_seq_014_mvl/mxv
	.byte	W02
	.byte		        53*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        52*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        52*fe8_seq_014_mvl/mxv
	.byte	W02
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_014_mvl/mxv
	.byte	W02
	.byte		        50*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_014_mvl/mxv
	.byte	W02
	.byte		        46*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_014_mvl/mxv
	.byte	W02
	.byte		        41*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        31*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        30*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        29*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        29*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        28*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        27*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        26*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        25*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        24*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        23*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        22*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        21*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        20*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        18*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        17*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        16*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        15*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        13*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        12*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        11*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        9*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        7*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        5*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        4*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        2*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        0*fe8_seq_014_mvl/mxv
	.byte	W01
	.byte		        0*fe8_seq_014_mvl/mxv
	.byte	W15
	.byte		EOT   , As2 
	.byte		        Ds3 
	.byte	W07
	.byte	GOTO
	 .word	fe8_seq_014_5 + 0x4
	.byte	FINE

@*********************** Track 07 ***********************@

fe8_seq_014_6:
	.byte	KEYSH , fe8_seq_014_key+0
	.byte		VOICE , 47
	.byte		VOL   , 55*fe8_seq_014_mvl/mxv
	.byte		PAN   , c_v+12
	.byte		N11   , Ds2 , v120
	.byte	W66
	.byte		N05
	.byte	W06
	.byte		N11
	.byte	W72
	.byte		N11   , Ds2 , v120
	.byte	W66
	.byte		N05
	.byte	W06
	.byte	PEND
	.byte		N11
	.byte	W72
	.byte	PATT
	 .word	fe8_seq_014_6 + 0x10
	.byte		N11   , Ds2 , v120
	.byte	W72
	.byte	PATT
	 .word	fe8_seq_014_6 + 0x10
	.byte		N11   , Ds2 , v120
	.byte	W72
	.byte	PATT
	 .word	fe8_seq_014_6 + 0x10
	.byte		N11   , Ds2 , v120
	.byte	W60
	.byte		N02   , As2 
	.byte	W03
	.byte		N02
	.byte	W03
	.byte		N02
	.byte	W03
	.byte		N02
	.byte	W03
	.byte	PATT
	 .word	fe8_seq_014_6 + 0x10
	.byte		N11   , Ds2 , v120
	.byte	W72
	.byte	PATT
	 .word	fe8_seq_014_6 + 0x10
	.byte		N11   , Ds2 , v120
	.byte	W36
	.byte		N11
	.byte	W12
	.byte		N11
	.byte	W12
	.byte		N11
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_014_6 + 0x10
	.byte		N11   , Ds2 , v120
	.byte	W72
	.byte	PATT
	 .word	fe8_seq_014_6 + 0x10
	.byte		N11   , Ds2 , v120
	.byte	W36
	.byte		N11
	.byte	W18
	.byte		N02   , As2 
	.byte	W03
	.byte		N02
	.byte	W03
	.byte		N02
	.byte	W03
	.byte		N02
	.byte	W03
	.byte		N02
	.byte	W03
	.byte		N02
	.byte	W03
	.byte		N11   , Ds2 , v120
	.byte	W60
	.byte		        As2 
	.byte	W12
	.byte	PEND
	.byte		        Ds2 
	.byte	W72
	.byte	PATT
	 .word	fe8_seq_014_6 + 0x76
	.byte		N11   , Ds2 , v120
	.byte	W60
	.byte		N02
	.byte	W03
	.byte		N02
	.byte	W03
	.byte		N02
	.byte	W03
	.byte		N02
	.byte	W03
	.byte	PATT
	 .word	fe8_seq_014_6 + 0x76
	.byte		N11   , Ds2 , v120
	.byte	W60
	.byte		N11
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_014_6 + 0x76
	.byte		N11   , Ds2 , v120
	.byte	W60
	.byte		N05   , As2 
	.byte	W06
	.byte		N05
	.byte	W06
	.byte	PATT
	 .word	fe8_seq_014_6 + 0x10
	.byte		N11   , Ds2 , v120
	.byte	W72
	.byte	GOTO
	 .word	fe8_seq_014_6 + 0x10
	.byte	FINE

@******************************************************@

	.align	2

fe8_seq_014:
	.byte	7	@ NumTrks
	.byte	0	@ NumBlks
	.byte	fe8_seq_014_pri	@ Priority
	.byte	fe8_seq_014_rev	@ Reverb

	.word	fe8_seq_014_grp

	.word	fe8_seq_014_0
	.word	fe8_seq_014_1
	.word	fe8_seq_014_2
	.word	fe8_seq_014_3
	.word	fe8_seq_014_4
	.word	fe8_seq_014_5
	.word	fe8_seq_014_6

	.end
