@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	fe8_seq_069_grp, native_instrument_map_bin
	.equ	fe8_seq_069_pri, 10
	.equ	fe8_seq_069_rev, 148
	.equ	fe8_seq_069_mvl, 127
	.equ	fe8_seq_069_key, 0

	.section .rodata
	.global	fe8_seq_069
	.align	2

@*********************** Track 01 ***********************@

fe8_seq_069_0:
	.byte	KEYSH , fe8_seq_069_key+0
	.byte	TEMPO , 138/2
	.byte	W24
	.byte		VOICE , 50
	.byte		VOL   , 42*fe8_seq_069_mvl/mxv
	.byte		PAN   , c_v-25
	.byte		TIE   , As3 , v100
	.byte	W96
	.byte	W68
	.byte	W03
	.byte		EOT
	.byte	W01
	.byte		N05   , As3 , v032
	.byte	W12
	.byte		        Ds4 , v100
	.byte	W06
	.byte		        Fn4 
	.byte	W06
	.byte		N80   , Fs4 
	.byte	W84
	.byte		N05   , En4 
	.byte	W06
	.byte		        Ds4 
	.byte	W06
	.byte		N80   , Cs4 
	.byte	W84
	.byte		N05   , Cs4 , v032
	.byte	W12
	.byte		N44   , Bn3 , v100
	.byte	W48
	.byte		N05   , Bn3 , v032
	.byte	W12
	.byte		        Bn3 , v100
	.byte	W06
	.byte		        Bn3 , v032
	.byte	W06
	.byte		        Fs4 , v100
	.byte	W06
	.byte		        Fs4 , v032
	.byte	W06
	.byte		        Bn4 , v100
	.byte	W06
	.byte		        Bn4 , v032
	.byte	W06
	.byte		N17   , Bn4 , v100
	.byte	W18
	.byte		N05   , Bn4 , v032
	.byte	W06
	.byte		N17   , An4 , v100
	.byte	W18
	.byte		N05   , An4 , v032
	.byte	W06
	.byte		N11   , Gn4 , v100
	.byte	W12
	.byte		N05   , Fs4 
	.byte	W06
	.byte		        Fs4 , v032
	.byte	W06
	.byte		        En4 , v100
	.byte	W06
	.byte		        En4 , v032
	.byte	W06
	.byte		        Dn4 , v100
	.byte	W06
	.byte		        Dn4 , v032
	.byte	W06
	.byte		N80   , Cn4 , v100
	.byte	W84
	.byte		N05   , Bn3 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		N56   , Dn4 
	.byte	W60
	.byte		N11   , Bn3 
	.byte	W12
	.byte		VOICE , 49
	.byte		VOL   , 38*fe8_seq_069_mvl/mxv
	.byte		PAN   , c_v+25
	.byte		N05   , Cn3 , v112
	.byte	W04
	.byte		        Dn3 
	.byte	W04
	.byte		        En3 
	.byte	W04
	.byte		        Fs3 
	.byte	W04
	.byte		        Gn3 
	.byte	W04
	.byte		        An3 
	.byte	W04
	.byte		N68   , Bn3 
	.byte	W72
	.byte		N05   , An3 
	.byte	W06
	.byte		        An3 , v032
	.byte	W06
	.byte		        Gn3 , v112
	.byte	W06
	.byte		        Gn3 , v032
	.byte	W06
	.byte		N44   , Fs3 , v112
	.byte	W48
	.byte		N28   , Dn3 
	.byte	W30
	.byte		N05   , Dn3 , v032
	.byte	W06
	.byte		        En3 , v112
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		N23   , Gn3 
	.byte	W24
	.byte		        En3 
	.byte	W24
	.byte		        Fs3 
	.byte	W24
	.byte		        Gn3 
	.byte	W24
	.byte		        An3 
	.byte	W24
	.byte		        Fs3 
	.byte	W24
	.byte		        Gn3 
	.byte	W24
	.byte		        Bn3 
	.byte	W24
	.byte		N68   , En3 , v080
	.byte	W72
	.byte		N05   , Fs3 
	.byte	W06
	.byte		        Fs3 , v032
	.byte	W06
	.byte		        Gn3 , v080
	.byte	W06
	.byte		        Gn3 , v032
	.byte	W06
	.byte		N44   , Fs3 , v080
	.byte	W48
	.byte		        Dn3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 17
	.byte		VOL   , 49*fe8_seq_069_mvl/mxv
	.byte		PAN   , c_v-10
	.byte		N44   , Ds4 , v120
	.byte		N44   , As4 , v127
	.byte	W48
	.byte		        As3 , v120
	.byte		N44   , Ds4 , v127
	.byte	W48
	.byte		        Fn4 , v120
	.byte		N44   , Gs4 , v127
	.byte	W48
	.byte		        Cs4 , v120
	.byte		N44   , Fn4 , v127
	.byte	W48
	.byte		N20   , Ds4 , v120
	.byte		N20   , Fs4 , v127
	.byte	W24
	.byte		        As3 , v120
	.byte		N20   , Ds4 , v127
	.byte	W24
	.byte		        Ds4 , v120
	.byte		N20   , Fs4 , v127
	.byte	W24
	.byte		        Fs4 , v120
	.byte		N20   , As4 , v127
	.byte	W24
	.byte		N20   , Fn4 , v120
	.byte		N20   , Gs4 , v127
	.byte	W24
	.byte		        Cs4 , v120
	.byte		N20   , Fn4 , v127
	.byte	W24
	.byte		        Ds4 , v120
	.byte		N20   , Fs4 , v127
	.byte	W24
	.byte		        Fn4 , v120
	.byte		N20   , Gs4 , v127
	.byte	W24
	.byte	PEND
	.byte		N52   , Fs4 , v120
	.byte		N52   , As4 , v127
	.byte	W60
	.byte		N05   , Fs4 , v120
	.byte		N05   , As4 , v127
	.byte	W12
	.byte		        Gs4 , v120
	.byte		N05   , Bn4 , v127
	.byte	W12
	.byte		        As4 , v120
	.byte		N05   , Cs5 , v127
	.byte	W12
	.byte		N44   , As4 , v120
	.byte		N44   , Cs5 , v127
	.byte	W48
	.byte		        Fs4 , v120
	.byte		N44   , As4 , v127
	.byte	W48
	.byte	PATT
	 .word	fe8_seq_069_0 + 0x110
	.byte		N44   , Cn4 , v120
	.byte		N44   , Fs4 , v127
	.byte	W48
	.byte		        Bn3 , v120
	.byte		N44   , Fn4 , v127
	.byte	W48
	.byte	GOTO
	 .word	fe8_seq_069_0 + 0x5
	.byte	FINE

@*********************** Track 02 ***********************@

fe8_seq_069_1:
	.byte	KEYSH , fe8_seq_069_key+0
	.byte	W06
	.byte		VOICE , 33
	.byte	W06
	.byte		VOL   , 42*fe8_seq_069_mvl/mxv
	.byte	W06
	.byte		PAN   , c_v+0
	.byte	W06
	.byte		N06   , As1 , v127
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Ds2 
	.byte	W12
	.byte		        Fn2 
	.byte	W12
	.byte		        Fs2 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        En2 
	.byte	W12
	.byte		        Ds2 
	.byte	W12
	.byte		        Cs2 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Ds2 
	.byte	W12
	.byte		        En2 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Cn2 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        An1 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Bn1 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06   , Cn2 , v127
	.byte	W12
	.byte		N18
	.byte	W24
	.byte		N18
	.byte	W24
	.byte		N18
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte		N06   , Bn1 , v127
	.byte	W12
	.byte		N18
	.byte	W24
	.byte		N18
	.byte	W24
	.byte		N18
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte		        An1 
	.byte	W12
	.byte		N18
	.byte	W24
	.byte		N18
	.byte	W24
	.byte		N18
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_069_1 + 0x9B
	.byte	PATT
	 .word	fe8_seq_069_1 + 0x8E
	.byte	PATT
	 .word	fe8_seq_069_1 + 0x9B
	.byte		N06   , An1 , v127
	.byte	W12
	.byte		N18
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Bn1 
	.byte	W12
	.byte		N18
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Cn2 
	.byte	W12
	.byte		N18
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Dn2 
	.byte	W12
	.byte		N18
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        An1 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Bn1 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Cn2 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Dn2 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06   , Ds2 , v127
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_069_1 + 0xF3
	.byte	PATT
	 .word	fe8_seq_069_1 + 0xF3
	.byte		N06   , Cs2 , v127
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Bn1 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Bn2 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Gs2 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Fs2 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Fn2 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Bn1 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte	GOTO
	 .word	fe8_seq_069_1 + 0xC
	.byte	FINE

@*********************** Track 03 ***********************@

fe8_seq_069_2:
	.byte	KEYSH , fe8_seq_069_key+0
	.byte		VOICE , 61
	.byte		VOL   , 49*fe8_seq_069_mvl/mxv
	.byte		PAN   , c_v+5
	.byte		N05   , Fs2 , v124
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte		        As2 
	.byte	W06
	.byte		        Cn3 
	.byte	W06
	.byte		N42   , Cs3 , v127
	.byte	W54
	.byte		N06   , As2 , v028
	.byte	W06
	.byte		N05   , Cs3 , v112
	.byte	W06
	.byte		N06   , Cs3 , v028
	.byte	W06
	.byte		N05   , Fn3 , v112
	.byte	W06
	.byte		N06   , Fn3 , v028
	.byte	W06
	.byte		N05   , Gs3 , v127
	.byte	W06
	.byte		N06   , Gs3 , v028
	.byte	W06
	.byte		N17   , Gn3 , v127
	.byte	W18
	.byte		N06   , Gn3 , v028
	.byte	W06
	.byte		N17   , Ds3 , v120
	.byte	W18
	.byte		N06   , Ds3 , v028
	.byte	W06
	.byte		N12   , As2 , v120
	.byte	W18
	.byte		N06   , As2 , v028
	.byte	W06
	.byte		N05   , As2 , v116
	.byte	W06
	.byte		N06   , As2 , v028
	.byte	W06
	.byte		N05   , Cn3 , v112
	.byte	W06
	.byte		N06   , Cn3 , v028
	.byte	W06
	.byte		N30   , Cs3 , v124
	.byte	W36
	.byte		N05   , Cn3 , v112
	.byte	W06
	.byte		        Cs3 , v116
	.byte	W06
	.byte		N32   , Ds3 , v124
	.byte	W36
	.byte		N05   , Cs3 , v116
	.byte	W06
	.byte		        Ds3 , v120
	.byte	W06
	.byte		N32   , En3 , v124
	.byte	W36
	.byte		N05   , Ds3 , v116
	.byte	W06
	.byte		        En3 
	.byte	W06
	.byte		N32   , Fs3 , v124
	.byte	W36
	.byte		N05   , En3 , v104
	.byte	W06
	.byte		        Fs3 , v112
	.byte	W06
	.byte		N24   , Gn3 , v124
	.byte	W30
	.byte		N06   , Gn3 , v028
	.byte	W06
	.byte		        Fs3 , v120
	.byte	W06
	.byte		N04   , Gn3 
	.byte	W06
	.byte		N17   , An3 , v127
	.byte	W18
	.byte		N06   , An3 , v028
	.byte	W06
	.byte		N17   , Fs3 , v127
	.byte	W18
	.byte		N06   , Fs3 , v028
	.byte	W06
	.byte		N48   , En3 , v124
	.byte	W54
	.byte		N06   , En3 , v028
	.byte	W06
	.byte		        Dn3 , v120
	.byte	W06
	.byte		        Dn3 , v028
	.byte	W06
	.byte		        En3 , v120
	.byte	W06
	.byte		        En3 , v028
	.byte	W06
	.byte		        Fs3 , v120
	.byte	W06
	.byte		        Fs3 , v028
	.byte	W06
	.byte		N30   , Gn3 , v120
	.byte	W30
	.byte		N06   , Gn3 , v028
	.byte	W06
	.byte		        Fs3 , v120
	.byte	W06
	.byte		        Gn3 
	.byte	W06
	.byte		N30   , An3 
	.byte	W30
	.byte		N06   , An3 , v028
	.byte	W06
	.byte		        Gn3 , v120
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		N48   , Bn3 
	.byte	W48
	.byte		N36   , An3 
	.byte	W48
	.byte		VOICE , 46
	.byte		VOL   , 38*fe8_seq_069_mvl/mxv
	.byte		PAN   , c_v-40
	.byte		N05   , Gn4 , v088
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		N05   , Fs4 , v088
	.byte	W06
	.byte		        Dn4 
	.byte	W06
	.byte		        Bn3 
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		        Fs4 
	.byte	W06
	.byte		        Dn4 
	.byte	W06
	.byte		        Bn3 
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		        Fs4 
	.byte	W06
	.byte		        Dn4 
	.byte	W06
	.byte		        Bn3 
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		        Fs4 
	.byte	W06
	.byte		        Dn4 
	.byte	W06
	.byte		        Bn3 
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte	PEND
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        En3 
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        En3 
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        En3 
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        En3 
	.byte	W06
	.byte	PATT
	 .word	fe8_seq_069_2 + 0x104
	.byte		N05   , Gn4 , v088
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte	PATT
	 .word	fe8_seq_069_2 + 0x104
	.byte		VOICE , 61
	.byte		VOL   , 49*fe8_seq_069_mvl/mxv
	.byte		PAN   , c_v+5
	.byte		N40   , Cn3 , v100
	.byte	W42
	.byte		N05   , Cn3 , v032
	.byte	W06
	.byte		N40   , Dn3 , v100
	.byte	W42
	.byte		N05   , Dn3 , v032
	.byte	W06
	.byte		N40   , En3 , v100
	.byte	W42
	.byte		N05   , En3 , v032
	.byte	W06
	.byte		N40   , Fs3 , v100
	.byte	W42
	.byte		N05   , Fs3 , v032
	.byte	W06
	.byte	PEND
	.byte		N40   , Cn3 , v100
	.byte	W42
	.byte		N05   , Cn3 , v032
	.byte	W06
	.byte		N40   , Dn3 , v100
	.byte	W42
	.byte		N05   , Dn3 , v032
	.byte	W06
	.byte	PATT
	 .word	fe8_seq_069_2 + 0x189
	.byte	W96
	.byte	W96
	.byte	W24
	.byte		VOICE , 50
	.byte	W24
	.byte		VOL   , 42*fe8_seq_069_mvl/mxv
	.byte	W24
	.byte		PAN   , c_v-25
	.byte	W24
	.byte	W72
	.byte		N04   , Bn3 , v088
	.byte	W04
	.byte		        Cs4 
	.byte	W04
	.byte		        Ds4 
	.byte	W04
	.byte		        Fn4 
	.byte	W04
	.byte		        Fs4 
	.byte	W04
	.byte		        Gs4 
	.byte	W04
	.byte		TIE   , As4 
	.byte	W96
	.byte	W24
	.byte		VOL   , 42*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_069_mvl/mxv
	.byte	W02
	.byte		        40*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_069_mvl/mxv
	.byte	W02
	.byte		        38*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_069_mvl/mxv
	.byte	W02
	.byte		        37*fe8_seq_069_mvl/mxv
	.byte	W02
	.byte		        37*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_069_mvl/mxv
	.byte	W02
	.byte		        35*fe8_seq_069_mvl/mxv
	.byte	W02
	.byte		        35*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        31*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        31*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        30*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        30*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        29*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        28*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        28*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        28*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        27*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        27*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        26*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        25*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        25*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        24*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        23*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        23*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        22*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        21*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        21*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        20*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        19*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        19*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        18*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        17*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        16*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        15*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        15*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        14*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        13*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        12*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        11*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        11*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        10*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        8*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        8*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        6*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        6*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        4*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        3*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        2*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        1*fe8_seq_069_mvl/mxv
	.byte	W01
	.byte		        0*fe8_seq_069_mvl/mxv
	.byte	W03
	.byte		EOT
	.byte		VOICE , 61
	.byte		VOL   , 49*fe8_seq_069_mvl/mxv
	.byte		PAN   , c_v+5
	.byte		N32   , Gs2 , v120
	.byte	W36
	.byte		N05   , As2 
	.byte	W06
	.byte		        Bn2 
	.byte	W06
	.byte		N40   , Cs3 
	.byte	W42
	.byte		N05   , Cs3 , v032
	.byte	W06
	.byte		N56   , Ds3 , v120
	.byte	W60
	.byte		N05   , Ds3 , v032
	.byte	W12
	.byte		        Fs2 , v124
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte		        As2 
	.byte	W06
	.byte		        Cn3 
	.byte	W06
	.byte	GOTO
	 .word	fe8_seq_069_2 + 0x12
	.byte	FINE

@*********************** Track 04 ***********************@

fe8_seq_069_3:
	.byte	KEYSH , fe8_seq_069_key+0
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 73
	.byte		VOL   , 42*fe8_seq_069_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W72
	.byte		N05   , Fs4 , v100
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		        An4 
	.byte	W06
	.byte		        Bn4 
	.byte	W06
	.byte		N68   , Dn5 
	.byte	W72
	.byte		N05   , Cn5 
	.byte	W12
	.byte		        Bn4 
	.byte	W12
	.byte		N44   , An4 
	.byte	W48
	.byte		N23   , Gn4 
	.byte	W24
	.byte		        Fs4 
	.byte	W24
	.byte		N05   , En4 
	.byte	W06
	.byte		        Dn4 
	.byte	W06
	.byte		N32   , En4 
	.byte	W36
	.byte		N05   , Fs4 
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		N32   , Fs4 
	.byte	W36
	.byte		N05   , Gn4 
	.byte	W06
	.byte		        Fs4 
	.byte	W06
	.byte		N32   , Gn4 
	.byte	W36
	.byte		N05   , An4 
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		        An4 
	.byte	W06
	.byte		        Bn4 
	.byte	W06
	.byte		        Cn5 
	.byte	W06
	.byte		        Bn4 
	.byte	W06
	.byte		        An4 
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		        En4 
	.byte		N05   , Gn4 
	.byte	W06
	.byte		        Dn4 
	.byte		N05   , Fs4 
	.byte	W06
	.byte		N32   , En4 
	.byte		N32   , Gn4 
	.byte	W36
	.byte		N05   , Fs4 
	.byte		N05   , An4 
	.byte	W06
	.byte		        En4 
	.byte		N05   , Gn4 
	.byte	W06
	.byte		N32   , Fs4 
	.byte		N32   , An4 
	.byte	W36
	.byte		N05   , Gn4 
	.byte		N05   , Bn4 
	.byte	W06
	.byte		        Fs4 
	.byte		N05   , An4 
	.byte	W06
	.byte		N32   , Gn4 
	.byte		N32   , Bn4 
	.byte	W36
	.byte		N05   , An4 
	.byte		N05   , Cn5 
	.byte	W06
	.byte		        Gn4 
	.byte		N05   , Bn4 
	.byte	W06
	.byte		        An4 
	.byte		N05   , Cn5 
	.byte	W06
	.byte		        Bn4 
	.byte		N05   , Dn5 
	.byte	W06
	.byte		        Cn5 
	.byte		N05   , En5 
	.byte	W06
	.byte		        Bn4 
	.byte		N05   , Dn5 
	.byte	W06
	.byte		        An4 
	.byte		N05   , Cn5 
	.byte	W06
	.byte		        En4 
	.byte		N05   , An4 
	.byte	W06
	.byte		N80   , As4 
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	fe8_seq_069_3 + 0x3
	.byte	FINE

@*********************** Track 05 ***********************@

fe8_seq_069_4:
	.byte	KEYSH , fe8_seq_069_key+0
	.byte		VOICE , 62
	.byte		VOL   , 34*fe8_seq_069_mvl/mxv
	.byte		PAN   , c_v+24
	.byte		N05   , Ds2 , v124
	.byte	W06
	.byte		        Fn2 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte		N42   , As2 , v127
	.byte	W48
	.byte		N05   , Fn2 , v112
	.byte	W12
	.byte		N04   , As2 , v096
	.byte	W12
	.byte		N03   , Cs3 , v092
	.byte	W12
	.byte		N04   , Fn3 , v116
	.byte	W12
	.byte		N19   , Ds3 , v120
	.byte	W24
	.byte		N18   , Cn3 , v100
	.byte	W24
	.byte		N12   , Gn2 
	.byte	W24
	.byte		N04   , Gn2 , v092
	.byte	W12
	.byte		        Gs2 , v076
	.byte	W12
	.byte		N30   , As2 , v108
	.byte	W36
	.byte		N05   , Gs2 , v080
	.byte	W06
	.byte		        As2 , v092
	.byte	W06
	.byte		N32   , Cn3 , v112
	.byte	W36
	.byte		N05   , Bn2 , v084
	.byte	W06
	.byte		        Cn3 , v092
	.byte	W06
	.byte		N32   , Cs3 , v104
	.byte	W36
	.byte		N05   , Cn3 , v092
	.byte	W06
	.byte		        Cs3 , v080
	.byte	W06
	.byte		N32   , Ds3 , v112
	.byte	W36
	.byte		N05   , Cs3 , v076
	.byte	W06
	.byte		        Ds3 , v088
	.byte	W06
	.byte		N24   , En3 , v112
	.byte	W36
	.byte		N06   , Dn3 , v100
	.byte	W06
	.byte		N04   , En3 , v092
	.byte	W06
	.byte		N19   , Fs3 , v120
	.byte	W24
	.byte		N17   , Dn3 
	.byte	W24
	.byte		N48   , Bn2 , v112
	.byte	W60
	.byte		N06   , Bn2 , v100
	.byte	W12
	.byte		        Cn3 
	.byte	W12
	.byte		        Dn3 
	.byte	W12
	.byte		N30   , En3 
	.byte	W36
	.byte		N06   , Dn3 
	.byte	W06
	.byte		        En3 
	.byte	W06
	.byte		N30   , Fs3 
	.byte	W36
	.byte		N06   , En3 
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		N48   , Gn3 
	.byte	W48
	.byte		N36   , Fs3 
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N40   , An2 , v100
	.byte	W42
	.byte		N05   , An2 , v032
	.byte	W06
	.byte		N40   , Bn2 , v100
	.byte	W42
	.byte		N05   , Bn2 , v032
	.byte	W06
	.byte	PEND
	.byte		N40   , Cn3 , v100
	.byte	W42
	.byte		N05   , Cn3 , v032
	.byte	W06
	.byte		N40   , Dn3 , v100
	.byte	W42
	.byte		N05   , Dn3 , v032
	.byte	W06
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_069_4 + 0x9F
	.byte	PATT
	 .word	fe8_seq_069_4 + 0xB0
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N56   , Cn3 , v120
	.byte	W60
	.byte		N05   , Cn3 , v032
	.byte	W12
	.byte		        Ds2 , v124
	.byte	W06
	.byte		        Fn2 
	.byte	W06
	.byte		        Fs2 
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte	GOTO
	 .word	fe8_seq_069_4 + 0x12
	.byte	FINE

@*********************** Track 06 ***********************@

fe8_seq_069_5:
	.byte	KEYSH , fe8_seq_069_key+0
	.byte	W03
	.byte		PAN   , c_v+11
	.byte	W06
	.byte		VOICE , 51
	.byte	W06
	.byte		VOL   , 49*fe8_seq_069_mvl/mxv
	.byte	W09
	.byte		N06   , As1 , v127
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Ds2 
	.byte	W12
	.byte		        Fn2 
	.byte	W12
	.byte		        Fs2 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        En2 
	.byte	W12
	.byte		        Ds2 
	.byte	W12
	.byte		        Cs2 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Ds2 
	.byte	W12
	.byte		        En2 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Cn2 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        An1 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Bn1 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06   , Cn2 , v092
	.byte		N06   , Gn2 , v076
	.byte	W12
	.byte		        Cn2 , v092
	.byte		N06   , Gn2 , v076
	.byte	W24
	.byte		        Cn2 , v088
	.byte		N06   , Gn2 , v072
	.byte	W12
	.byte		        Cn2 , v088
	.byte		N06   , Gn2 , v076
	.byte	W12
	.byte		        Cn2 , v092
	.byte		N06   , Gn2 , v072
	.byte	W24
	.byte		        Cn2 , v088
	.byte		N06   , Gn2 , v076
	.byte	W12
	.byte	PEND
	.byte		N06   , Bn1 , v092
	.byte		N06   , Fs2 , v076
	.byte	W12
	.byte		        Bn1 , v092
	.byte		N06   , Fs2 , v076
	.byte	W24
	.byte		        Bn1 , v088
	.byte		N06   , Fs2 , v072
	.byte	W12
	.byte		        Bn1 , v088
	.byte		N06   , Fs2 , v076
	.byte	W12
	.byte		        Bn1 , v088
	.byte		N06   , Fs2 , v076
	.byte	W24
	.byte		        Bn1 , v088
	.byte		N06   , Fs2 , v068
	.byte	W12
	.byte	PEND
	.byte		        An1 , v092
	.byte		N06   , En2 , v076
	.byte	W12
	.byte		        An1 , v092
	.byte		N06   , En2 , v076
	.byte	W24
	.byte		        An1 , v088
	.byte		N06   , En2 , v072
	.byte	W12
	.byte		        An1 , v092
	.byte		N06   , En2 , v076
	.byte	W12
	.byte		        An1 , v092
	.byte		N06   , En2 , v072
	.byte	W24
	.byte		        An1 , v088
	.byte		N06   , En2 , v072
	.byte	W12
	.byte		        Gn1 , v092
	.byte		N06   , Dn2 , v072
	.byte	W12
	.byte		        Gn1 , v092
	.byte		N06   , Dn2 , v076
	.byte	W24
	.byte		        Gn1 , v088
	.byte		N06   , Dn2 , v076
	.byte	W12
	.byte		        Gn1 , v088
	.byte		N06   , Dn2 , v072
	.byte	W12
	.byte		        Gn1 , v088
	.byte		N06   , Dn2 , v072
	.byte	W12
	.byte		        An1 , v092
	.byte		N06   , En2 , v072
	.byte	W12
	.byte		        Bn1 , v092
	.byte		N06   , Fs2 , v072
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_069_5 + 0x8E
	.byte	PATT
	 .word	fe8_seq_069_5 + 0xB4
	.byte		N06   , En2 , v096
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		        En2 , v092
	.byte	W12
	.byte		        Fs2 , v100
	.byte	W12
	.byte		        Fs2 , v080
	.byte	W24
	.byte		        Fs2 , v088
	.byte	W12
	.byte	PEND
	.byte		N06   , En2 , v092
	.byte	W12
	.byte		        En2 , v100
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Fs2 
	.byte	W12
	.byte		        Fs2 , v080
	.byte	W24
	.byte		        Fs2 , v088
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_069_5 + 0x132
	.byte	PATT
	 .word	fe8_seq_069_5 + 0x145
	.byte		TIE   , Ds2 , v088
	.byte		TIE   , As2 , v096
	.byte	W96
	.byte	W96
	.byte	W92
	.byte	W03
	.byte		EOT   , Ds2 
	.byte		        As2 
	.byte	W01
	.byte		N92   , Cs2 , v084
	.byte		N92   , Gs2 , v092
	.byte	W96
	.byte		        Ds2 , v084
	.byte		N92   , As2 , v092
	.byte	W96
	.byte		        Cs2 , v080
	.byte		N92   , As2 , v092
	.byte	W96
	.byte		        Fn2 , v096
	.byte	W96
	.byte		N44   , Ds2 , v092
	.byte	W48
	.byte		        Gs2 
	.byte	W48
	.byte	GOTO
	 .word	fe8_seq_069_5 + 0xC
	.byte	FINE

@*********************** Track 07 ***********************@

fe8_seq_069_6:
	.byte	KEYSH , fe8_seq_069_key+0
	.byte		VOICE , 127
	.byte		VOL   , 44*fe8_seq_069_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N05   , Cn2 , v127
	.byte	W06
	.byte		        An1 
	.byte	W06
	.byte		        Fn1 
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		N48   , Cs2 , v076
	.byte	W12
	.byte		N05   , Fs1 , v036
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		        Fs1 , v040
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v028
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		N06   , Dn1 , v092
	.byte	W06
	.byte		        Dn1 , v096
	.byte	W06
	.byte		        Dn1 , v104
	.byte	W06
	.byte		        Dn1 , v112
	.byte	W06
	.byte		N42   , Cs2 , v076
	.byte	W12
	.byte		N05   , Fs1 , v036
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v040
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v040
	.byte	W12
	.byte		        Fs1 , v044
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		        Fs1 , v040
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v040
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Fs1 , v028
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		        As1 , v048
	.byte	W06
	.byte		        Fs1 , v032
	.byte	W06
	.byte		N11   , Dn2 , v112
	.byte	W12
	.byte		N23   , Dn2 , v100
	.byte	W24
	.byte		N23
	.byte	W24
	.byte		        Dn2 , v116
	.byte	W24
	.byte		N11   , Dn2 , v080
	.byte	W12
	.byte		N11   , Dn2 , v080
	.byte	W12
	.byte		N23   , Dn2 , v116
	.byte	W24
	.byte		        Dn2 , v092
	.byte	W24
	.byte		        Dn2 , v112
	.byte	W24
	.byte		N05   , Dn1 , v116
	.byte	W06
	.byte		        Dn1 , v100
	.byte	W06
	.byte	PEND
	.byte		N06   , Dn1 , v112
	.byte	W12
	.byte		N23   , Dn2 
	.byte	W24
	.byte		        Dn2 , v116
	.byte	W24
	.byte		        Dn2 , v120
	.byte	W24
	.byte		N11   , Dn1 , v084
	.byte	W12
	.byte		N10   , Dn1 , v100
	.byte	W12
	.byte		N23   , Dn2 , v112
	.byte	W24
	.byte		N23
	.byte	W24
	.byte		N11
	.byte	W12
	.byte		        Dn2 , v120
	.byte	W12
	.byte		        Dn2 , v112
	.byte	W12
	.byte		        Dn2 , v120
	.byte	W12
	.byte		N23   , Dn2 , v100
	.byte	W24
	.byte		N23
	.byte	W24
	.byte		        Dn2 , v116
	.byte	W24
	.byte		N11   , Dn2 , v080
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_069_6 + 0xD7
	.byte		N06   , Dn1 , v112
	.byte	W12
	.byte		N23   , Dn2 
	.byte	W24
	.byte		        Dn2 , v116
	.byte	W24
	.byte		        Dn2 , v120
	.byte	W24
	.byte		N11   , Dn1 , v080
	.byte	W12
	.byte		N10   , Dn1 , v100
	.byte	W12
	.byte		N23   , Dn2 , v112
	.byte	W24
	.byte		N23
	.byte	W24
	.byte		N11
	.byte	W12
	.byte		        Dn1 , v120
	.byte	W12
	.byte		N05   , Dn1 , v112
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		N11   , Dn2 
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		        Dn2 , v116
	.byte	W24
	.byte		        Dn2 , v120
	.byte	W24
	.byte		N11   , Dn1 , v084
	.byte	W12
	.byte		N10   , Dn1 , v100
	.byte	W12
	.byte		N23   , Dn2 , v112
	.byte	W24
	.byte		N11
	.byte	W12
	.byte		N05   , Cn2 , v116
	.byte	W12
	.byte		        An1 
	.byte	W12
	.byte		        Fn1 
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		        Dn1 , v096
	.byte	W06
	.byte		        Dn1 , v112
	.byte	W06
	.byte		N23   , Cs2 , v100
	.byte	W24
	.byte		N05   , Fs1 , v032
	.byte	W12
	.byte		        Dn1 , v100
	.byte	W06
	.byte		        Dn1 , v096
	.byte	W06
	.byte		N05
	.byte	W12
	.byte		        Dn1 , v100
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W24
	.byte		N05
	.byte	W24
	.byte		N05
	.byte	W12
	.byte		        Dn1 , v096
	.byte	W06
	.byte		        Dn1 , v088
	.byte	W06
	.byte		        Dn1 , v100
	.byte		N05   , Fs1 , v032
	.byte	W12
	.byte		        Dn1 , v092
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		        Dn1 , v100
	.byte	W06
	.byte		        Dn1 , v092
	.byte	W06
	.byte		        Fs1 , v032
	.byte	W24
	.byte		N05
	.byte	W12
	.byte		        Dn1 , v092
	.byte	W12
	.byte		N05
	.byte		N05   , Fs1 , v032
	.byte	W12
	.byte		        Dn1 , v104
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		        Dn1 , v100
	.byte	W12
	.byte		N05
	.byte		N05   , Fs1 , v032
	.byte	W24
	.byte		N05
	.byte	W12
	.byte		        Dn1 , v092
	.byte	W06
	.byte		        Dn1 , v080
	.byte	W06
	.byte		        Dn1 , v092
	.byte		N05   , Fs1 , v032
	.byte	W12
	.byte		        Dn1 , v096
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		        Dn1 , v100
	.byte	W06
	.byte		        Dn1 , v096
	.byte	W06
	.byte		N32   , Cs2 , v100
	.byte	W24
	.byte		N05   , Fs1 , v032
	.byte	W12
	.byte		        Dn1 , v100
	.byte	W06
	.byte		        Dn1 , v096
	.byte	W06
	.byte		        Dn1 , v100
	.byte	W12
	.byte		        Dn1 , v104
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W24
	.byte		N05
	.byte	W24
	.byte		N05
	.byte	W12
	.byte		        Dn1 , v104
	.byte	W06
	.byte		N05
	.byte	W06
	.byte		        Dn1 , v096
	.byte	W12
	.byte		        Dn1 , v100
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		        Dn1 , v100
	.byte	W06
	.byte		        Dn1 , v092
	.byte	W06
	.byte		        Fs1 , v032
	.byte	W24
	.byte		N05
	.byte	W12
	.byte		        Dn1 , v096
	.byte	W12
	.byte		N05
	.byte		N05   , Fs1 , v032
	.byte	W12
	.byte		        Dn1 , v092
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W12
	.byte		        Dn1 , v092
	.byte	W12
	.byte		        Fs1 , v032
	.byte	W24
	.byte		N05
	.byte	W12
	.byte		        Dn1 , v100
	.byte	W06
	.byte		        Dn1 , v088
	.byte	W06
	.byte		        Dn1 , v100
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Dn1 , v096
	.byte	W06
	.byte		N05
	.byte	W06
	.byte	GOTO
	 .word	fe8_seq_069_6 + 0x12
	.byte	FINE

@******************************************************@

	.align	2

fe8_seq_069:
	.byte	7	@ NumTrks
	.byte	0	@ NumBlks
	.byte	fe8_seq_069_pri	@ Priority
	.byte	fe8_seq_069_rev	@ Reverb

	.word	fe8_seq_069_grp

	.word	fe8_seq_069_0
	.word	fe8_seq_069_1
	.word	fe8_seq_069_2
	.word	fe8_seq_069_3
	.word	fe8_seq_069_4
	.word	fe8_seq_069_5
	.word	fe8_seq_069_6

	.end
