@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	fe8_seq_009_grp, native_instrument_map_bin
	.equ	fe8_seq_009_pri, 10
	.equ	fe8_seq_009_rev, 148
	.equ	fe8_seq_009_mvl, 127
	.equ	fe8_seq_009_key, 0

	.section .rodata
	.global	fe8_seq_009
	.align	2

@*********************** Track 01 ***********************@

fe8_seq_009_0:
	.byte	KEYSH , fe8_seq_009_key+0
	.byte	TEMPO , 120/2
	.byte		VOICE , 50
	.byte		VOL   , 50*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v-8
	.byte		N06   , Ds3 , v092
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        Gn3 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		N60   , As3 , v092
	.byte	W60
	.byte		N12   , Fn3 
	.byte	W12
	.byte		        As3 
	.byte	W12
	.byte		        Cn4 
	.byte	W12
	.byte		VOL   , 50*fe8_seq_009_mvl/mxv
	.byte		N24   , An3 
	.byte	W24
	.byte		N12   , Fn3 
	.byte	W12
	.byte		N54   , Cn3 
	.byte	W11
	.byte		VOL   , 50*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        32*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        30*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        29*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        27*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        25*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        23*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        21*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        18*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte		N48   , As3 
	.byte	W48
	.byte		N23   , Fn3 
	.byte	W24
	.byte		N12   , As3 
	.byte	W12
	.byte		        Cn4 
	.byte	W12
	.byte		N24   , An3 
	.byte	W24
	.byte		N12   , As3 
	.byte	W12
	.byte		N32   , Cn4 
	.byte	W24
	.byte	W02
	.byte		VOL   , 49*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		N24   , Fn4 
	.byte	W01
	.byte		VOL   , 35*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W10
	.byte		N48   , Ds4 
	.byte	W48
	.byte		        As3 
	.byte	W48
	.byte		        Dn4 
	.byte	W48
	.byte		N24   , As3 
	.byte	W24
	.byte		        Fn3 
	.byte	W24
	.byte		N60   , Cs4 
	.byte	W60
	.byte		N12   , Gs3 
	.byte	W12
	.byte		N21   , Cs4 
	.byte	W16
	.byte		VOL   , 45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        32*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        29*fe8_seq_009_mvl/mxv
	.byte		N90   , Ds4 
	.byte	W01
	.byte		VOL   , 30*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        32*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W24
	.byte	W02
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        33*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        32*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        30*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        29*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        28*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        27*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        25*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        24*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        23*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        22*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        20*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        19*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        18*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		VOICE , 62
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte		N48   , As3 
	.byte	W48
	.byte		N06   , As3 , v032
	.byte	W12
	.byte		        Fn3 , v092
	.byte	W06
	.byte		        Fn3 , v032
	.byte	W06
	.byte		        As3 , v092
	.byte	W06
	.byte		        As3 , v032
	.byte	W06
	.byte		        Cn4 , v092
	.byte	W06
	.byte		        Cn4 , v032
	.byte	W06
	.byte		N23   , An3 , v092
	.byte	W24
	.byte		N06   , Fn3 
	.byte	W06
	.byte		        Fn3 , v032
	.byte	W06
	.byte		N54   , Cn3 , v092
	.byte	W60
	.byte		N48   , As3 
	.byte	W48
	.byte		N18   , Fn3 
	.byte	W18
	.byte		N06   , Fn3 , v032
	.byte	W06
	.byte		        As3 , v092
	.byte	W06
	.byte		        As3 , v032
	.byte	W06
	.byte		        Cn4 , v092
	.byte	W06
	.byte		        Cn4 , v032
	.byte	W06
	.byte		N18   , An3 , v092
	.byte	W24
	.byte		N06   , As3 
	.byte	W06
	.byte		        As3 , v032
	.byte	W06
	.byte		N24   , Cn4 , v092
	.byte	W24
	.byte		N06   , Cn4 , v032
	.byte	W09
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		VOICE , 50
	.byte		VOL   , 25*fe8_seq_009_mvl/mxv
	.byte		N24   , Fn4 , v064
	.byte	W01
	.byte		VOL   , 28*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        31*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        53*fe8_seq_009_mvl/mxv
	.byte	W09
	.byte		N48   , Ds4 
	.byte	W48
	.byte		N24   , Fn4 
	.byte	W24
	.byte		        Ds4 
	.byte	W24
	.byte		N48   , Dn4 
	.byte	W06
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        52*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        52*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		N24   , Ds4 
	.byte	W01
	.byte		VOL   , 35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        53*fe8_seq_009_mvl/mxv
	.byte	W14
	.byte		N24   , Dn4 
	.byte	W24
	.byte		N60   , Cs4 
	.byte	W60
	.byte		N12   , Gs3 
	.byte	W12
	.byte		N24   , Cs4 
	.byte	W24
	.byte		N48   , Ds4 
	.byte	W48
	.byte		N24   , Fn4 
	.byte	W14
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        52*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte		N24   , Ds4 
	.byte	W02
	.byte		VOL   , 47*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		N23   , Cs4 , v068
	.byte	W01
	.byte		VOL   , 37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        53*fe8_seq_009_mvl/mxv
	.byte	W04
	.byte		N23   , Gs3 
	.byte	W24
	.byte		        Gn3 
	.byte	W24
	.byte		        Ds3 
	.byte	W24
	.byte		N44   , Cn4 , v060
	.byte	W48
	.byte		N23   , Gs3 , v068
	.byte	W24
	.byte		        Ds4 , v060
	.byte	W24
	.byte		N32   , Cn4 
	.byte	W36
	.byte		N44   , As3 , v052
	.byte	W28
	.byte		VOL   , 52*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		VOICE , 52
	.byte	W01
	.byte		VOL   , 42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        33*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        53*fe8_seq_009_mvl/mxv
	.byte		N05   , Ds4 , v056
	.byte		N05   , Gn4 , v068
	.byte	W06
	.byte		        Fn4 , v056
	.byte		N05   , Gs4 , v068
	.byte	W06
	.byte		N36   , Ds4 , v060
	.byte		N36   , Gn4 , v072
	.byte	W36
	.byte		N05   , Cn4 , v056
	.byte		N05   , Ds4 , v068
	.byte	W06
	.byte		        Dn4 , v056
	.byte		N05   , Fn4 , v068
	.byte	W06
	.byte		N42   , Cn4 , v060
	.byte		N42   , Ds4 , v072
	.byte	W42
	.byte		N05   , Ds4 , v040
	.byte	W06
	.byte		VOICE , 50
	.byte		N23   , Cs3 , v064
	.byte	W24
	.byte		        Gs3 
	.byte	W24
	.byte		        Gn3 
	.byte	W24
	.byte		        Ds3 
	.byte	W24
	.byte		N44   , Cn4 
	.byte	W48
	.byte		N23   , Gs3 
	.byte	W24
	.byte		N20   , Ds4 
	.byte	W24
	.byte		N32
	.byte	W36
	.byte		N05
	.byte	W06
	.byte		        Fn4 
	.byte	W06
	.byte		N32   , Ds4 
	.byte	W36
	.byte		N11   , Cs4 
	.byte	W12
	.byte		N44   , Cn4 
	.byte	W48
	.byte		N23   , Gn3 , v084
	.byte	W24
	.byte		N05   , En3 
	.byte	W06
	.byte		        Gn3 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        En4 
	.byte	W06
	.byte		N04   , Fn2 , v064
	.byte		N04   , Cn3 , v072
	.byte		N06   , Fn4 , v092
	.byte	W06
	.byte		N04   , Cn3 , v016
	.byte		N06   , Fn4 
	.byte	W06
	.byte		VOICE , 53
	.byte		N04   , Fn2 , v056
	.byte		N04   , Cn3 , v064
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v052
	.byte		N04   , Cn3 , v064
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v044
	.byte		N04   , Cn3 , v048
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v040
	.byte		N04   , Cn3 , v056
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v056
	.byte		N04   , Cn3 , v060
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v060
	.byte		N04   , Cn3 , v072
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v052
	.byte		N04   , Cn3 , v064
	.byte	W12
	.byte		        Gn2 , v076
	.byte		N04   , Ds3 
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v056
	.byte		N04   , Ds3 , v072
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v052
	.byte		N04   , Ds3 , v068
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v052
	.byte		N04   , Ds3 , v080
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v052
	.byte		N04   , Ds3 , v076
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v056
	.byte		N04   , Ds3 , v076
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v048
	.byte		N04   , Ds3 , v068
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v044
	.byte		N04   , Ds3 
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Fn2 , v060
	.byte		N04   , Cn3 , v076
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v056
	.byte		N04   , Cn3 , v068
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v052
	.byte		N04   , Cn3 , v064
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v048
	.byte		N04   , Cn3 , v060
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v048
	.byte		N04   , Cn3 , v064
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v044
	.byte		N04   , Cn3 , v060
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v048
	.byte		N04   , Cn3 , v056
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v052
	.byte		N04   , Cn3 , v056
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Gn2 , v072
	.byte		N04   , Ds3 , v080
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v044
	.byte		N04   , Ds3 , v068
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v044
	.byte		N04   , Ds3 , v052
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v052
	.byte		N04   , Ds3 , v076
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v056
	.byte		N04   , Ds3 , v076
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v052
	.byte		N04   , Ds3 , v076
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v056
	.byte		N04   , Ds3 , v076
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Gn2 , v052
	.byte		N04   , Ds3 , v056
	.byte	W06
	.byte		        Ds3 , v016
	.byte	W06
	.byte		        Fn2 , v068
	.byte		N04   , As2 , v084
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v048
	.byte		N04   , As2 , v076
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v040
	.byte		N04   , As2 , v036
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v048
	.byte		N04   , As2 , v076
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v052
	.byte		N04   , As2 , v076
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v048
	.byte		N04   , As2 , v072
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v052
	.byte		N04   , As2 , v068
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v052
	.byte		N04   , As2 , v084
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Gs2 , v064
	.byte		N04   , Cn3 , v072
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Gs2 , v060
	.byte		N04   , Cn3 , v064
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Gs2 , v052
	.byte		N04   , Cn3 , v056
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Gs2 , v040
	.byte		N04   , Cn3 , v064
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Gs2 , v040
	.byte		N04   , Cn3 , v060
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Gs2 , v060
	.byte		N04   , Cn3 
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Gs2 , v064
	.byte		N04   , Cn3 
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Gs2 , v060
	.byte		N04   , Cn3 , v064
	.byte	W06
	.byte		        Cn3 , v016
	.byte	W06
	.byte		        Fn2 , v068
	.byte		N04   , As2 , v084
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v056
	.byte		N04   , As2 , v084
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v056
	.byte		N04   , As2 , v068
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v060
	.byte		N04   , As2 , v076
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v056
	.byte		N04   , As2 , v080
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v056
	.byte		N04   , As2 , v076
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v056
	.byte		N04   , As2 , v076
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Fn2 , v048
	.byte		N04   , As2 , v076
	.byte	W06
	.byte		        As2 , v016
	.byte	W06
	.byte		        Gs2 , v076
	.byte	W06
	.byte		        Gs2 , v016
	.byte	W06
	.byte		        Gs2 , v076
	.byte	W06
	.byte		        Gs2 , v016
	.byte	W06
	.byte		        Gs2 , v080
	.byte	W06
	.byte		        Gs2 , v016
	.byte	W06
	.byte		        Gs2 , v080
	.byte	W06
	.byte		        Gs2 , v016
	.byte	W06
	.byte		        Gs2 , v084
	.byte	W06
	.byte		        Gs2 , v016
	.byte	W06
	.byte		        Gs2 , v076
	.byte	W06
	.byte		        Gs2 , v016
	.byte	W28
	.byte	W01
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		VOICE , 56
	.byte		PAN   , c_v+0
	.byte		N18   , Gs3 , v104
	.byte	W18
	.byte		N06   , Gn3 
	.byte	W09
	.byte		        Gn3 , v024
	.byte	W09
	.byte		N36   , Ds3 , v100
	.byte	W36
	.byte		N06   , Ds3 , v024
	.byte	W12
	.byte		N03   , Ds3 , v100
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		N18   , Fs3 , v104
	.byte	W18
	.byte		N06   , Fn3 
	.byte	W09
	.byte		        Fn3 , v024
	.byte	W09
	.byte		N36   , Cs3 , v100
	.byte	W36
	.byte		N06   , Cs3 , v024
	.byte	W12
	.byte		N03   , Cs3 , v100
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		N18   , En3 , v104
	.byte	W18
	.byte		N06   , Ds3 
	.byte	W09
	.byte		        Ds3 , v024
	.byte	W09
	.byte		N36   , Bn2 , v100
	.byte	W36
	.byte	W03
	.byte		N06   , Bn2 , v024
	.byte	W09
	.byte		N03   , Cs3 , v100
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		N18   , Fs3 , v104
	.byte	W18
	.byte		N06   , Fs3 , v024
	.byte	W06
	.byte		N18   , Fn3 , v104
	.byte	W18
	.byte		N06   , Fn3 , v024
	.byte	W06
	.byte		N18   , Ds3 , v104
	.byte	W18
	.byte		N06   , Ds3 , v024
	.byte	W06
	.byte		N18   , Cs3 , v104
	.byte	W18
	.byte		N06   , Cs3 , v024
	.byte	W06
	.byte		VOICE , 62
	.byte		VOL   , 37*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W12
	.byte		N06   , Fn3 , v080
	.byte		N06   , As3 , v084
	.byte	W06
	.byte		        Ds3 , v080
	.byte		N06   , Gs3 , v084
	.byte	W06
	.byte		N60   , Fn3 
	.byte		N60   , As3 , v088
	.byte	W60
	.byte		N12   , Fn3 , v060
	.byte	W12
	.byte	W12
	.byte		N06   , Gs3 , v080
	.byte		N06   , Cn4 , v084
	.byte	W06
	.byte		        Gn3 , v080
	.byte		N06   , As3 , v084
	.byte	W06
	.byte		N66   , Gs3 
	.byte		N60   , Cn4 , v088
	.byte	W66
	.byte		N06   , Gs3 , v040
	.byte	W06
	.byte	W12
	.byte		        As3 , v080
	.byte		N06   , Dn4 , v084
	.byte	W06
	.byte		        Gs3 , v080
	.byte		N06   , Cn4 , v084
	.byte	W06
	.byte		N66   , As3 , v072
	.byte		N60   , Dn4 , v088
	.byte	W66
	.byte		N06   , As3 , v040
	.byte	W06
	.byte	W12
	.byte		        Cn4 , v080
	.byte		N06   , Ds4 , v084
	.byte	W06
	.byte		        As3 , v080
	.byte		N06   , Dn4 , v084
	.byte	W06
	.byte		N66   , Cn4 , v072
	.byte		N60   , Ds4 , v088
	.byte	W66
	.byte		N06   , Cn4 , v040
	.byte	W06
	.byte	W12
	.byte		        Fn3 , v080
	.byte		N06   , As3 , v084
	.byte	W06
	.byte		        Ds3 , v080
	.byte		N06   , Gs3 , v084
	.byte	W06
	.byte		N44   , Fn3 
	.byte		N36   , As3 , v088
	.byte	W48
	.byte		N17   , As2 
	.byte		N17   , Fn3 
	.byte	W18
	.byte		N06   , Fn3 , v040
	.byte	W06
	.byte	W12
	.byte		        As3 , v080
	.byte		N06   , Dn4 , v084
	.byte	W06
	.byte		        Gs3 , v080
	.byte		N06   , Cn4 , v084
	.byte	W06
	.byte		N44   , As3 
	.byte		N36   , Dn4 , v088
	.byte	W48
	.byte		N17   , Fn3 
	.byte		N17   , As3 
	.byte	W18
	.byte		N06   , As3 , v040
	.byte	W06
	.byte	W12
	.byte		        Cn4 , v080
	.byte		N06   , Ds4 , v084
	.byte	W06
	.byte		        As3 , v080
	.byte		N06   , Dn4 , v084
	.byte	W06
	.byte		N42   , Cn4 , v072
	.byte		N36   , Ds4 , v088
	.byte	W42
	.byte		N06   , Cn4 , v040
	.byte	W06
	.byte		N12   , As3 , v076
	.byte		N12   , Dn4 , v088
	.byte	W12
	.byte		        Cn4 , v076
	.byte		N12   , Ds4 , v088
	.byte	W12
	.byte		N06   , Ds4 , v040
	.byte	W12
	.byte		        Dn4 , v080
	.byte		N06   , Fn4 , v084
	.byte	W06
	.byte		        Cn4 , v080
	.byte		N06   , Ds4 , v084
	.byte	W06
	.byte		N66   , Dn4 , v072
	.byte		N60   , Fn4 , v088
	.byte	W66
	.byte		N06   , Dn4 , v040
	.byte	W06
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 62
	.byte		VOL   , 47*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W24
	.byte		N18   , Gn2 , v104
	.byte	W18
	.byte		N06   , Gn2 , v056
	.byte	W06
	.byte		N18   , An2 , v104
	.byte	W18
	.byte		N06   , An2 , v056
	.byte	W06
	.byte		N18   , As2 , v104
	.byte	W18
	.byte		N06   , As2 , v056
	.byte	W06
	.byte		N18   , Cn3 , v104
	.byte	W18
	.byte		N06   , Cn3 , v056
	.byte	W06
	.byte		N18   , As2 , v104
	.byte	W18
	.byte		N06   , As2 , v056
	.byte	W06
	.byte		N18   , Dn3 , v104
	.byte	W18
	.byte		N06   , Dn3 , v056
	.byte	W06
	.byte		N09   , Cn3 , v096
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		N48   , An2 
	.byte	W48
	.byte		        Cn3 
	.byte	W48
	.byte		N42   , Dn3 
	.byte	W48
	.byte		VOICE , 50
	.byte	W12
	.byte		N05   , An3 , v076
	.byte		N05   , Cn4 
	.byte	W12
	.byte		        Gn3 
	.byte		N05   , As3 
	.byte	W12
	.byte		        Fn3 
	.byte		N05   , An3 
	.byte	W12
	.byte	GOTO
	 .word	fe8_seq_009_0 + 0x14
	.byte	FINE

@*********************** Track 02 ***********************@

fe8_seq_009_1:
	.byte	KEYSH , fe8_seq_009_key+0
	.byte	W24
	.byte		VOICE , 34
	.byte		VOL   , 43*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N06   , Fn2 , v127
	.byte	W12
	.byte		N16
	.byte	W24
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N16
	.byte	W24
	.byte		N05
	.byte	W12
	.byte		N24   , Fn2 , v127
	.byte	W36
	.byte		N04
	.byte	W12
	.byte		N04
	.byte	W12
	.byte		N10
	.byte	W24
	.byte		N04
	.byte	W12
	.byte	PEND
	.byte		N23   , Fn2 , v127
	.byte	W36
	.byte		N04
	.byte	W12
	.byte		N24
	.byte	W36
	.byte		N05
	.byte	W12
	.byte	PEND
	.byte		N24   , Fn2 , v127
	.byte	W36
	.byte		N04
	.byte	W12
	.byte		N04
	.byte	W12
	.byte		N13
	.byte	W24
	.byte		N04
	.byte	W12
	.byte	PEND
	.byte		N23   , Ds2 , v127
	.byte	W36
	.byte		N04
	.byte	W12
	.byte		N15   , Ds3 
	.byte	W24
	.byte		N16   , Ds2 
	.byte	W24
	.byte	PEND
	.byte		N30   , Dn2 , v127
	.byte	W36
	.byte		N05
	.byte	W12
	.byte		N16   , Dn3 
	.byte	W24
	.byte		N13   , Dn2 
	.byte	W24
	.byte	PEND
	.byte		N28   , Cs2 , v127
	.byte	W36
	.byte		N04
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N19   , Gs1 
	.byte	W24
	.byte		N05   , Cs2 
	.byte	W12
	.byte	PEND
	.byte		N19   , Ds2 , v127
	.byte	W36
	.byte		N04
	.byte	W12
	.byte		N20   , Ds3 
	.byte	W24
	.byte		N05   , Ds2 
	.byte	W12
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte		        Fn2 
	.byte	W12
	.byte		N16
	.byte	W24
	.byte		N05
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N16
	.byte	W24
	.byte		N05
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_009_1 + 0x17
	.byte	PATT
	 .word	fe8_seq_009_1 + 0x24
	.byte	PATT
	 .word	fe8_seq_009_1 + 0x2F
	.byte	PATT
	 .word	fe8_seq_009_1 + 0x3C
	.byte	PATT
	 .word	fe8_seq_009_1 + 0x49
	.byte	PATT
	 .word	fe8_seq_009_1 + 0x56
	.byte	PATT
	 .word	fe8_seq_009_1 + 0x65
	.byte		N06   , Cs2 , v120
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_009_1 + 0xA3
	.byte		N06   , Cn2 , v120
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_009_1 + 0xB7
	.byte	PATT
	 .word	fe8_seq_009_1 + 0xA3
	.byte		N06   , As1 , v120
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Ds2 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_009_1 + 0xB7
	.byte		VOICE , 33
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N18   , Fn2 , v076
	.byte	W84
	.byte		N09
	.byte	W12
	.byte		N18   , Cn2 , v076
	.byte	W84
	.byte		N12
	.byte	W12
	.byte	PEND
	.byte		N18   , Fn2 
	.byte	W84
	.byte		N09
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_009_1 + 0xFB
	.byte		N18   , As1 , v076
	.byte	W84
	.byte		N12
	.byte	W12
	.byte		N18   , Fn2 
	.byte	W84
	.byte		N12
	.byte	W12
	.byte		VOICE , 34
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N18   , As1 
	.byte	W84
	.byte		N12
	.byte	W12
	.byte		N18   , Fn2 , v088
	.byte	W84
	.byte		N12   , Fn2 , v096
	.byte	W12
	.byte		        Cs2 , v112
	.byte	W18
	.byte		N06   , Ds2 
	.byte	W18
	.byte		N36   , Gs2 
	.byte	W60
	.byte		N12   , Bn1 
	.byte	W18
	.byte		N06   , Cs2 
	.byte	W18
	.byte		N36   , Fs2 
	.byte	W60
	.byte		N12   , An1 
	.byte	W18
	.byte		N06   , Bn1 
	.byte	W18
	.byte		N36   , En2 
	.byte	W60
	.byte		N18   , Ds2 
	.byte	W24
	.byte		        Fn2 
	.byte	W24
	.byte		        Fs2 
	.byte	W24
	.byte		        Fn2 
	.byte	W24
	.byte		N92   , As1 , v096
	.byte	W96
	.byte		        Gs1 
	.byte	W96
	.byte		        Gn1 
	.byte	W96
	.byte		        Gs1 
	.byte	W96
	.byte		        Ds2 
	.byte	W96
	.byte		        Dn2 
	.byte	W96
	.byte		        Cn2 
	.byte	W96
	.byte		        As1 
	.byte	W96
	.byte		N09   , Ds2 , v120
	.byte	W36
	.byte		        As2 , v108
	.byte	W12
	.byte		        Ds2 , v112
	.byte	W36
	.byte		N09
	.byte	W12
	.byte	PEND
	.byte		        Dn2 , v120
	.byte	W36
	.byte		        An2 , v108
	.byte	W12
	.byte		N21   , Gn2 , v092
	.byte	W36
	.byte		N09   , Dn2 , v120
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_009_1 + 0x160
	.byte		N09   , Dn2 , v112
	.byte	W36
	.byte		N09
	.byte	W12
	.byte		N21   , Gn2 , v092
	.byte	W36
	.byte		N09
	.byte	W12
	.byte		N90   , Ds2 , v100
	.byte	W96
	.byte		N90
	.byte	W96
	.byte		N72   , Dn2 
	.byte	W84
	.byte		N06   , Dn2 , v108
	.byte	W12
	.byte		N30   , Dn2 , v104
	.byte	W36
	.byte		N06   , Dn2 , v108
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N18   , Dn2 , v104
	.byte	W24
	.byte		N06   , Ds2 , v116
	.byte	W12
	.byte	GOTO
	 .word	fe8_seq_009_1 + 0x3
	.byte	FINE

@*********************** Track 03 ***********************@

fe8_seq_009_2:
	.byte	KEYSH , fe8_seq_009_key+0
	.byte	W24
	.byte		VOICE , 46
	.byte		VOL   , 50*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v-24
	.byte	W96
	.byte		N12   , Fn2 , v108
	.byte	W12
	.byte		        Cn3 
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		        An3 
	.byte	W12
	.byte		N06   , Fn2 
	.byte	W06
	.byte		        Cn3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        As3 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        Fn4 
	.byte	W06
	.byte		        As4 , v084
	.byte	W06
	.byte	W96
	.byte		N12   , Fn2 , v108
	.byte	W12
	.byte		        Cn3 
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		        An3 
	.byte	W12
	.byte		N06   , An4 
	.byte	W06
	.byte		        As4 
	.byte	W06
	.byte		        An4 
	.byte	W06
	.byte		        Fn4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        Cn3 
	.byte	W06
	.byte		N12   , Ds2 
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		        Ds3 
	.byte	W12
	.byte		        Gn3 
	.byte	W12
	.byte		        As3 
	.byte	W12
	.byte		        Gn3 
	.byte	W12
	.byte		        Ds3 
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		        Dn2 
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		        Dn3 
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		        As3 
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		        Dn3 
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		        Cs2 
	.byte	W12
	.byte		        Gs2 
	.byte	W12
	.byte		        Cs3 
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		        Gs3 
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		        Cs3 
	.byte	W12
	.byte		        Gs2 
	.byte	W12
	.byte		        Ds2 
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		        Ds3 
	.byte	W12
	.byte		        Gn3 
	.byte	W12
	.byte		N06   , As4 
	.byte	W06
	.byte		        Ds5 
	.byte	W06
	.byte		        As4 
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		        Ds4 
	.byte	W06
	.byte		        As3 
	.byte	W06
	.byte		        Gn3 
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte	W96
	.byte		N12   , Ds2 
	.byte	W12
	.byte		        An2 
	.byte	W12
	.byte		N09   , Cn3 
	.byte	W12
	.byte		N12   , Fn3 
	.byte	W12
	.byte		N06   , Fn2 
	.byte	W06
	.byte		        Cn3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        Fn4 
	.byte	W06
	.byte	W96
	.byte		N12   , Ds2 
	.byte	W12
	.byte		        An2 
	.byte	W12
	.byte		        Cn3 
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		N06   , An4 
	.byte	W06
	.byte		        As4 
	.byte	W06
	.byte		        An4 
	.byte	W06
	.byte		        Fn4 
	.byte	W06
	.byte		        Cn4 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        Cn3 
	.byte	W06
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOL   , 33*fe8_seq_009_mvl/mxv
	.byte	W48
	.byte		N11   , Gs4 , v096
	.byte	W12
	.byte		        Fn4 
	.byte	W12
	.byte		        Cn4 
	.byte	W12
	.byte		        Gs3 
	.byte	W12
	.byte		N11   , Cs3 , v096
	.byte	W12
	.byte		        Gs3 
	.byte	W12
	.byte		        Cn4 
	.byte	W12
	.byte		        Fn4 
	.byte	W12
	.byte		        Gs4 
	.byte	W12
	.byte		        Fn4 
	.byte	W12
	.byte		        Cn4 
	.byte	W12
	.byte		        Gs3 
	.byte	W12
	.byte	PEND
	.byte		N11   , Cn3 , v096
	.byte	W12
	.byte		        Gn3 
	.byte	W12
	.byte		        Cn4 
	.byte	W12
	.byte		        Ds4 
	.byte	W12
	.byte		        Gn4 
	.byte	W12
	.byte		        Ds4 
	.byte	W12
	.byte		        Cn4 
	.byte	W12
	.byte		        Gn3 
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_009_2 + 0xE8
	.byte	PATT
	 .word	fe8_seq_009_2 + 0xD5
	.byte		N11   , As2 , v096
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		        As3 
	.byte	W12
	.byte		        Cs4 
	.byte	W12
	.byte		        Fn4 
	.byte	W12
	.byte		        Cs4 
	.byte	W12
	.byte		        As3 
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		        Ds3 
	.byte	W12
	.byte		        As3 
	.byte	W12
	.byte		        Ds4 
	.byte	W12
	.byte		        Gn4 
	.byte	W12
	.byte		        As4 
	.byte	W12
	.byte		        Gn4 
	.byte	W12
	.byte		        Ds4 
	.byte	W12
	.byte		        As3 
	.byte	W12
	.byte		        Cn3 
	.byte	W12
	.byte		        Gn3 
	.byte	W12
	.byte		        Cn4 
	.byte	W12
	.byte		        En4 
	.byte	W12
	.byte		        Gn4 
	.byte	W12
	.byte		        En4 
	.byte	W12
	.byte		        Cn4 
	.byte	W12
	.byte		        Gn3 
	.byte	W12
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W92
	.byte	W03
	.byte		VOL   , 33*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		VOICE , 48
	.byte		VOL   , 47*fe8_seq_009_mvl/mxv
	.byte		N36   , Dn3 , v088
	.byte	W36
	.byte		N12   , Ds3 
	.byte	W12
	.byte		N36   , Fn3 
	.byte	W36
	.byte		N12   , Gn3 
	.byte	W12
	.byte		N30   , Gs3 , v092
	.byte	W30
	.byte		N06   , Gn3 , v088
	.byte	W06
	.byte		        Gs3 
	.byte	W06
	.byte		        As3 , v096
	.byte	W06
	.byte		N44   , Cn4 
	.byte	W48
	.byte		N17   , Fn4 , v084
	.byte	W18
	.byte		N06   , Ds4 
	.byte	W18
	.byte		N36   , As3 , v064
	.byte	W60
	.byte		N17   , Ds4 , v076
	.byte	W18
	.byte		N06   , Cs4 
	.byte	W18
	.byte		N36   , Gs3 , v064
	.byte	W48
	.byte		N05   , Cs3 , v080
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		N17   , Cs4 , v076
	.byte	W18
	.byte		N06   , Bn3 
	.byte	W18
	.byte		N36   , Fs3 , v048
	.byte	W48
	.byte		N05   , Fs3 , v060
	.byte	W06
	.byte		        Gs3 , v076
	.byte	W06
	.byte		N21   , As3 , v060
	.byte	W24
	.byte		        Gs3 
	.byte	W24
	.byte		        Fs3 
	.byte	W24
	.byte		        Fn3 
	.byte	W24
	.byte		VOICE , 48
	.byte		VOL   , 27*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+21
	.byte		N44   , Fn3 , v124
	.byte	W01
	.byte		VOL   , 27*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        27*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        28*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        29*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        29*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        30*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        30*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        31*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W06
	.byte		N23   , Ds3 
	.byte	W24
	.byte		        Dn3 
	.byte	W24
	.byte		N64   , Ds3 
	.byte	W32
	.byte		VOL   , 50*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte		N11   , Dn3 
	.byte	W01
	.byte		VOL   , 33*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte		N11   , Ds3 
	.byte	W01
	.byte		VOL   , 40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte		N32   , Fn3 
	.byte	W01
	.byte		VOL   , 47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W32
	.byte		TIE   , As2 
	.byte	W60
	.byte	W10
	.byte		VOL   , 50*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		EOT
	.byte		VOL   , 36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte		N11   , Gs3 
	.byte	W01
	.byte		VOL   , 34*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte		N11   , Gn3 
	.byte	W01
	.byte		VOL   , 39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte		N11   , Fn3 
	.byte	W01
	.byte		VOL   , 44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte		N11   , Ds3 
	.byte	W12
	.byte		N44   , Fn3 
	.byte	W48
	.byte		N23   , Ds3 
	.byte	W24
	.byte		        Dn3 
	.byte	W24
	.byte		N64
	.byte	W32
	.byte	W01
	.byte		VOL   , 49*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte		N11   , Cn3 
	.byte	W01
	.byte		VOL   , 36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte		N11   , Dn3 
	.byte	W01
	.byte		VOL   , 47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W07
	.byte		N32   , Ds3 
	.byte	W36
	.byte		N76   , As2 
	.byte	W44
	.byte		VOL   , 50*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte		N23   , Dn3 
	.byte	W01
	.byte		VOL   , 37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte		N23   , Ds3 
	.byte	W01
	.byte		VOL   , 48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W20
	.byte		N24   , Fn3 
	.byte	W24
	.byte		N09   , Fn3 , v040
	.byte	W12
	.byte		N11   , Dn3 , v084
	.byte	W12
	.byte		N06   , Cn3 
	.byte	W36
	.byte		N11   , Dn3 
	.byte	W12
	.byte		N06   , Cn3 
	.byte	W24
	.byte	W12
	.byte		N11
	.byte	W12
	.byte		N06   , An2 
	.byte	W36
	.byte		N11   , Gn2 
	.byte	W12
	.byte		N06   , Gn3 , v052
	.byte	W24
	.byte	W12
	.byte		N11   , Dn3 , v084
	.byte	W12
	.byte		N06   , Cn3 
	.byte	W36
	.byte		N11   , Dn3 
	.byte	W12
	.byte		N06   , Cn3 
	.byte	W24
	.byte	W12
	.byte		N11
	.byte	W12
	.byte		N06   , Dn3 
	.byte	W36
	.byte		N11   , Gn2 
	.byte	W12
	.byte		N06   , Gn3 , v052
	.byte	W24
	.byte		VOICE , 68
	.byte	W24
	.byte		N23   , Gn3 , v084
	.byte	W24
	.byte		        An3 
	.byte	W24
	.byte		        As3 
	.byte	W24
	.byte		        Cn4 
	.byte	W24
	.byte		        As3 
	.byte	W24
	.byte		N17   , Dn4 
	.byte	W18
	.byte		N05   , Dn4 , v032
	.byte	W06
	.byte		        Cn4 , v084
	.byte	W06
	.byte		        Cn4 , v032
	.byte	W06
	.byte		        As3 , v084
	.byte	W06
	.byte		        As3 , v032
	.byte	W06
	.byte		N68   , An3 , v072
	.byte	W72
	.byte		N11   , An3 , v080
	.byte	W12
	.byte		        As3 , v076
	.byte	W12
	.byte		N44   , Cn4 , v064
	.byte	W28
	.byte		VOL   , 50*fe8_seq_009_mvl/mxv
	.byte	W20
	.byte		VOICE , 46
	.byte		VOL   , 47*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N06   , Dn2 , v108
	.byte	W06
	.byte		        An2 
	.byte	W06
	.byte		        Dn3 
	.byte	W06
	.byte		        Gn3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Dn4 
	.byte	W06
	.byte		        An4 , v084
	.byte	W06
	.byte	GOTO
	 .word	fe8_seq_009_2 + 0x3
	.byte	FINE

@*********************** Track 04 ***********************@

fe8_seq_009_3:
	.byte	KEYSH , fe8_seq_009_key+0
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 69
	.byte		VOL   , 37*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+17
	.byte		N48   , As2 , v096
	.byte	W60
	.byte		N12   , Fn2 
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		        Cn3 
	.byte	W12
	.byte		N24   , An2 
	.byte	W24
	.byte		N12   , Fn2 
	.byte	W12
	.byte		N54   , Cn2 
	.byte	W60
	.byte		N42   , As2 
	.byte	W48
	.byte		N24   , Fn2 
	.byte	W24
	.byte		N12   , As2 
	.byte	W12
	.byte		        Cn3 
	.byte	W12
	.byte		N24   , An2 
	.byte	W24
	.byte		N12   , As2 
	.byte	W12
	.byte		N30   , Cn3 
	.byte	W36
	.byte		N24   , Fn3 , v072
	.byte	W24
	.byte		N48   , Ds3 , v096
	.byte	W48
	.byte		        As2 
	.byte	W48
	.byte		N42   , Dn3 
	.byte	W48
	.byte		N21   , As2 
	.byte	W24
	.byte		N06   , Gn2 
	.byte	W06
	.byte		        An2 
	.byte	W06
	.byte		        As2 
	.byte	W06
	.byte		        Cn3 
	.byte	W06
	.byte		N56   , Cs3 
	.byte	W60
	.byte		N12   , Gs2 
	.byte	W12
	.byte		N21   , Cs3 
	.byte	W24
	.byte		N48   , Ds3 
	.byte	W48
	.byte		N18   , As2 
	.byte	W23
	.byte		VOL   , 37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		VOICE , 68
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N05
	.byte	W06
	.byte		        Cn3 
	.byte	W06
	.byte		        Cs3 
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		N23   , Fn3 
	.byte	W24
	.byte		        Cn4 , v092
	.byte	W24
	.byte		        As3 , v096
	.byte	W24
	.byte		        Gs3 
	.byte	W24
	.byte		        Ds4 , v076
	.byte	W24
	.byte		N20   , Cn4 , v084
	.byte	W24
	.byte		N23   , Cn4 , v080
	.byte	W24
	.byte		        As3 , v076
	.byte	W24
	.byte		VOL   , 36*fe8_seq_009_mvl/mxv
	.byte		TIE   , Gn3 , v092
	.byte	W10
	.byte		VOL   , 37*fe8_seq_009_mvl/mxv
	.byte	W08
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W07
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W05
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W06
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W05
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W05
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W06
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W05
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte	W01
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W03
	.byte		        53*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        52*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        52*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        31*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        31*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        30*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        29*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        28*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        27*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        26*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        25*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        24*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        23*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        22*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        21*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        20*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        19*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        17*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        16*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        15*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        13*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        11*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        10*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        8*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		EOT
	.byte		VOL   , 6*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        5*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        3*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        0*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        0*fe8_seq_009_mvl/mxv
	.byte	W10
	.byte		        53*fe8_seq_009_mvl/mxv
	.byte	W04
	.byte		VOICE , 69
	.byte		N23   , Fn2 , v116
	.byte	W24
	.byte		        Cn3 , v104
	.byte	W24
	.byte		        As2 , v116
	.byte	W24
	.byte		        Gs2 , v108
	.byte	W24
	.byte		N44   , Ds3 , v104
	.byte	W48
	.byte		N23   , Cn3 
	.byte	W24
	.byte		        Gs3 , v084
	.byte	W24
	.byte		N88   , Gn3 , v092
	.byte	W90
	.byte		N06   , Gn3 , v040
	.byte	W06
	.byte		N90   , En3 , v104
	.byte	W90
	.byte		N06   , En3 , v040
	.byte	W06
	.byte	W48
	.byte		VOICE , 50
	.byte		MOD   , 0
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W12
	.byte		N12   , Fn4 , v052
	.byte	W12
	.byte		        Ds4 , v064
	.byte	W12
	.byte		        Dn4 , v072
	.byte	W12
	.byte		N30   , Cn4 
	.byte	W36
	.byte		N06   , Cn4 , v076
	.byte	W06
	.byte		        Dn4 , v072
	.byte	W03
	.byte		VOL   , 50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        31*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        31*fe8_seq_009_mvl/mxv
	.byte		N24   , Ds4 , v060
	.byte	W01
	.byte		VOL   , 33*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        53*fe8_seq_009_mvl/mxv
	.byte	W11
	.byte		N12   , Dn4 , v064
	.byte	W12
	.byte		N06   , Cn4 , v060
	.byte	W12
	.byte	W60
	.byte		N12   , Fn4 , v052
	.byte	W12
	.byte		        Ds4 , v064
	.byte	W12
	.byte		        Dn4 , v068
	.byte	W12
	.byte		N30   , Cn4 , v064
	.byte	W36
	.byte		N06   , Cn4 , v072
	.byte	W06
	.byte		        Dn4 
	.byte	W02
	.byte		VOL   , 51*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte		N24   , Ds4 , v064
	.byte	W01
	.byte		VOL   , 39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        53*fe8_seq_009_mvl/mxv
	.byte	W07
	.byte		N12   , Fn4 
	.byte	W12
	.byte		        Ds4 , v052
	.byte	W12
	.byte		        Dn4 , v044
	.byte	W60
	.byte		        As4 , v028
	.byte	W12
	.byte		        Gs4 , v048
	.byte	W12
	.byte		        Gn4 , v064
	.byte	W12
	.byte		N30   , Fn4 
	.byte	W36
	.byte		N06
	.byte	W06
	.byte		        Gn4 
	.byte	W03
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte		N24   , Gs4 
	.byte	W01
	.byte		VOL   , 42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        53*fe8_seq_009_mvl/mxv
	.byte	W06
	.byte		N12   , Gn4 , v060
	.byte	W12
	.byte		        Fn4 
	.byte	W12
	.byte		VOICE , 68
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W60
	.byte		N12   , As4 
	.byte	W12
	.byte		        Gs4 , v072
	.byte	W12
	.byte		        Gn4 , v064
	.byte	W12
	.byte		N30   , Fn4 , v068
	.byte	W30
	.byte		N06   , Fn4 , v032
	.byte	W06
	.byte		        Fn4 , v064
	.byte	W06
	.byte		        Gn4 
	.byte	W06
	.byte		N21   , Gs4 
	.byte	W24
	.byte		N06   , As3 , v052
	.byte		N06   , Cs4 , v068
	.byte	W06
	.byte		        Cn4 , v056
	.byte		N06   , Ds4 , v076
	.byte	W06
	.byte		        Cs4 , v060
	.byte		N06   , Fn4 , v080
	.byte	W06
	.byte		        Ds4 , v064
	.byte		N06   , Gn4 , v084
	.byte	W06
	.byte		N18   , Gs4 , v092
	.byte	W18
	.byte		N06   , Gn4 
	.byte	W06
	.byte		        Gn4 , v032
	.byte	W12
	.byte		N36   , Ds4 , v088
	.byte	W36
	.byte		N06   , Ds4 , v032
	.byte	W12
	.byte		N03   , Ds4 , v088
	.byte	W06
	.byte		        Fn4 
	.byte	W06
	.byte		N18   , Fs4 , v092
	.byte	W18
	.byte		N06   , Fn4 
	.byte	W06
	.byte		        Fn4 , v032
	.byte	W12
	.byte		N36   , Cs4 , v088
	.byte	W36
	.byte		N06   , Cs4 , v032
	.byte	W12
	.byte		N03   , Cs4 , v088
	.byte	W06
	.byte		        Ds4 
	.byte	W06
	.byte		N18   , En4 , v092
	.byte	W18
	.byte		N06   , Ds4 
	.byte	W06
	.byte		        Ds4 , v032
	.byte	W12
	.byte		N36   , Bn3 , v088
	.byte	W36
	.byte	W03
	.byte		N06   , Bn3 , v032
	.byte	W09
	.byte		N03   , Cs4 , v088
	.byte	W06
	.byte		        Ds4 
	.byte	W06
	.byte		N18   , Fs4 , v092
	.byte	W18
	.byte		N06   , Fs4 , v032
	.byte	W06
	.byte		N18   , Fn4 , v092
	.byte	W18
	.byte		N06   , Fn4 , v032
	.byte	W06
	.byte		N18   , Ds4 , v092
	.byte	W18
	.byte		N06   , Ds4 , v032
	.byte	W06
	.byte		N18   , Cs4 , v092
	.byte	W18
	.byte		N06   , Cs4 , v032
	.byte	W06
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		VOICE , 68
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+0
	.byte	W12
	.byte		N12   , Gn3 , v104
	.byte	W12
	.byte		N06   , Fn3 
	.byte	W06
	.byte		        Fn3 , v032
	.byte	W30
	.byte		N12   , As3 , v104
	.byte	W12
	.byte		N06   , Gn3 
	.byte	W06
	.byte		        Gn3 , v032
	.byte	W18
	.byte	W12
	.byte		N12   , An3 , v104
	.byte	W12
	.byte		N06   , Dn3 
	.byte	W06
	.byte		        Dn3 , v032
	.byte	W30
	.byte		N12   , Gn3 , v104
	.byte	W36
	.byte	W12
	.byte		N12
	.byte	W12
	.byte		N06   , Fn3 
	.byte	W06
	.byte		        Fn3 , v032
	.byte	W30
	.byte		N12   , As3 , v104
	.byte	W12
	.byte		N06   , Gn3 
	.byte	W06
	.byte		        Gn3 , v032
	.byte	W18
	.byte	W12
	.byte		N12   , An3 , v104
	.byte	W12
	.byte		N06   , As3 
	.byte	W06
	.byte		        As3 , v032
	.byte	W30
	.byte		N12   , Gn3 , v104
	.byte	W36
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	fe8_seq_009_3 + 0x3
	.byte	FINE

@*********************** Track 05 ***********************@

fe8_seq_009_4:
	.byte	KEYSH , fe8_seq_009_key+0
	.byte	W24
	.byte		VOICE , 60
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+20
	.byte		N52   , Fn3 , v096
	.byte	W60
	.byte		N05   , Cn3 
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N23
	.byte	W24
	.byte		N05   , Cn3 
	.byte	W12
	.byte		N44   , An2 
	.byte	W60
	.byte		N40   , Fn3 , v096
	.byte	W48
	.byte		N17   , Cn3 
	.byte	W24
	.byte		N05   , Fn3 
	.byte	W12
	.byte		N05
	.byte	W12
	.byte	PEND
	.byte		N23
	.byte	W24
	.byte		N05   , Gn3 
	.byte	W12
	.byte		N28   , An3 
	.byte	W36
	.byte		N23   , Cn4 , v080
	.byte	W24
	.byte		N44   , As3 
	.byte	W48
	.byte		N28   , Gn3 
	.byte	W36
	.byte		N05   , An3 
	.byte	W12
	.byte		N40   , As3 
	.byte	W48
	.byte		N17   , Fn3 
	.byte	W24
	.byte		        Dn3 
	.byte	W24
	.byte		N56   , Gs3 
	.byte	W60
	.byte		N05   , Fn3 
	.byte	W12
	.byte		        Gn3 
	.byte	W12
	.byte		        Gs3 
	.byte	W12
	.byte		N11   , As3 
	.byte	W24
	.byte		N17   , Gn3 , v100
	.byte		N17   , As3 
	.byte	W24
	.byte		        Ds3 , v088
	.byte		N17   , Gn3 
	.byte	W24
	.byte		        As2 , v096
	.byte		N17   , Ds3 
	.byte	W24
	.byte		N52   , Fn3 
	.byte	W60
	.byte		N05   , Cn3 
	.byte	W12
	.byte		        Fn3 
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		N20
	.byte	W24
	.byte		N05   , Cn3 
	.byte	W12
	.byte		N44   , An2 
	.byte	W60
	.byte	PATT
	 .word	fe8_seq_009_4 + 0x1C
	.byte		N20   , Fn3 , v096
	.byte	W24
	.byte		N05   , Cn3 
	.byte	W12
	.byte		N28   , An2 
	.byte	W36
	.byte		N23   , Cn4 , v080
	.byte	W24
	.byte		N40   , As3 , v096
	.byte	W48
	.byte		N32   , Fs3 
	.byte	W36
	.byte		N05   , Gs3 
	.byte	W12
	.byte		N40   , As3 
	.byte	W48
	.byte		N11   , Fn3 
	.byte	W24
	.byte		N05   , Dn3 
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        Gn3 
	.byte	W06
	.byte		N52   , Gs3 
	.byte	W60
	.byte		N05   , Fn3 
	.byte	W12
	.byte		        Gn3 
	.byte	W12
	.byte		        Gs3 
	.byte	W12
	.byte		N40   , As3 
	.byte	W48
	.byte		N20   , Fn3 
	.byte		N20   , Gs3 
	.byte	W24
	.byte		        Ds3 
	.byte		N20   , Fs3 
	.byte	W24
	.byte		N92   , Fn3 
	.byte	W13
	.byte		VOL   , 53*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        52*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        52*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        51*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        50*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        49*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        48*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        47*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        46*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        45*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        44*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        43*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        42*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        41*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        40*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        39*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        38*fe8_seq_009_mvl/mxv
	.byte	W02
	.byte		        37*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        36*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        35*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        34*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        33*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        32*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        31*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        30*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        30*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        29*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        28*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        28*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        27*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        26*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        25*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        25*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        24*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        23*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        22*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        21*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        20*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        19*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        18*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        17*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        16*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        15*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        14*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        13*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        12*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        11*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        10*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        8*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        7*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        6*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        4*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        3*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        2*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		        0*fe8_seq_009_mvl/mxv
	.byte	W06
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W92
	.byte	W03
	.byte		        0*fe8_seq_009_mvl/mxv
	.byte	W01
	.byte		VOICE , 57
	.byte		VOL   , 48*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+10
	.byte	W36
	.byte		N12   , Dn3 , v084
	.byte	W12
	.byte		N24   , Cn3 , v080
	.byte	W36
	.byte		N09   , Bn2 
	.byte	W12
	.byte		N24   , Cn3 , v084
	.byte	W24
	.byte		N66   , Gn2 , v076
	.byte	W72
	.byte	W36
	.byte		N12   , Dn3 , v084
	.byte	W12
	.byte		N24   , Cn3 , v080
	.byte	W36
	.byte		N09   , Bn2 
	.byte	W12
	.byte		N24   , Cn3 , v084
	.byte	W24
	.byte		N42   , Gn2 , v076
	.byte	W48
	.byte		N09
	.byte	W12
	.byte		        An2 
	.byte	W12
	.byte		N12   , As2 
	.byte	W36
	.byte		        Fn3 , v084
	.byte	W12
	.byte		N24   , Ds3 , v080
	.byte	W36
	.byte		N12   , Dn3 
	.byte	W12
	.byte		N24   , Ds3 , v084
	.byte	W24
	.byte		N66   , Gs2 , v076
	.byte	W72
	.byte	W36
	.byte		N12   , Fn3 , v084
	.byte	W12
	.byte		N24   , Ds3 , v080
	.byte	W36
	.byte		N12   , Dn3 
	.byte	W12
	.byte		N24   , Ds3 , v092
	.byte	W24
	.byte		N66   , Gs2 , v084
	.byte	W72
	.byte		VOICE , 64
	.byte		N06   , Gs3 , v104
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N36   , Ds3 
	.byte	W36
	.byte		N06   , Ds3 , v032
	.byte	W24
	.byte		        Gs3 , v104
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N36   , Cs3 
	.byte	W36
	.byte		N06   , Cs3 , v032
	.byte	W24
	.byte		        Fs3 , v104
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N36   , Bn2 
	.byte	W36
	.byte		N06   , Bn2 , v032
	.byte	W24
	.byte		N21   , Ds3 , v104
	.byte	W24
	.byte		        Fn3 
	.byte	W24
	.byte		        Fs3 
	.byte	W24
	.byte		        Fn3 
	.byte	W24
	.byte		N06   , Fn3 , v100
	.byte	W12
	.byte		        Fn3 , v028
	.byte	W12
	.byte		        Fn3 , v100
	.byte	W12
	.byte		        Fn3 , v028
	.byte	W12
	.byte		        Fn3 , v100
	.byte	W12
	.byte		        Fn3 , v028
	.byte	W12
	.byte		        Fn3 , v100
	.byte	W12
	.byte		        Fn3 , v028
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_009_4 + 0x1E3
	.byte		N06   , Dn3 , v100
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v100
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v100
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte		        Dn3 , v100
	.byte	W12
	.byte		        Dn3 , v028
	.byte	W12
	.byte	PEND
	.byte		N06   , Ds3 , v100
	.byte	W12
	.byte		        Ds3 , v028
	.byte	W12
	.byte		        Ds3 , v100
	.byte	W12
	.byte		        Ds3 , v028
	.byte	W12
	.byte		        Ds3 , v100
	.byte	W12
	.byte		        Ds3 , v028
	.byte	W12
	.byte		        Ds3 , v100
	.byte	W12
	.byte		        Ds3 , v028
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_009_4 + 0x1E3
	.byte	PATT
	 .word	fe8_seq_009_4 + 0x202
	.byte	PATT
	 .word	fe8_seq_009_4 + 0x21C
	.byte	PATT
	 .word	fe8_seq_009_4 + 0x202
	.byte		VOICE , 57
	.byte	W12
	.byte		N12   , Gn2 , v084
	.byte	W12
	.byte		N06   , Fn2 
	.byte	W06
	.byte		        Fn2 , v040
	.byte	W30
	.byte		N12   , As2 , v084
	.byte	W12
	.byte		N06   , Gn2 
	.byte	W06
	.byte		        Gn2 , v040
	.byte	W18
	.byte	W12
	.byte		N12   , An2 , v084
	.byte	W12
	.byte		N06   , Dn2 
	.byte	W06
	.byte		        Dn2 , v040
	.byte	W30
	.byte		N12   , Gn2 , v084
	.byte	W12
	.byte		N06   , Gn3 , v056
	.byte	W12
	.byte		        Gn3 , v008
	.byte	W12
	.byte	W12
	.byte		N12   , Gn2 , v084
	.byte	W12
	.byte		N06   , Fn2 
	.byte	W06
	.byte		        Fn2 , v040
	.byte	W30
	.byte		N12   , As2 , v084
	.byte	W12
	.byte		N06   , Gn2 
	.byte	W06
	.byte		        Gn2 , v040
	.byte	W18
	.byte	W12
	.byte		N12   , An2 , v084
	.byte	W12
	.byte		N06   , As2 
	.byte	W06
	.byte		        As2 , v040
	.byte	W30
	.byte		N12   , Gn2 , v084
	.byte	W12
	.byte		N06   , Gn3 , v056
	.byte	W12
	.byte		        Gn3 , v008
	.byte	W12
	.byte		N78   , Ds3 , v084
	.byte	W84
	.byte		N06
	.byte	W12
	.byte		N90
	.byte	W96
	.byte		N48   , Dn3 
	.byte	W48
	.byte		N24   , Cn3 
	.byte	W24
	.byte		        Ds3 
	.byte	W24
	.byte		N48   , Dn3 
	.byte	W48
	.byte		N09   , Dn3 , v040
	.byte	W12
	.byte		N06   , An2 , v084
	.byte	W12
	.byte		        Dn3 
	.byte	W12
	.byte		        Ds3 
	.byte	W12
	.byte	GOTO
	 .word	fe8_seq_009_4 + 0x3
	.byte	FINE

@*********************** Track 06 ***********************@

fe8_seq_009_5:
	.byte	KEYSH , fe8_seq_009_key+0
	.byte	W24
	.byte		VOICE , 64
	.byte		VOL   , 47*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v-14
	.byte		N06   , Fn3 , v084
	.byte	W12
	.byte		N06
	.byte	W36
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06   , Fn3 , v084
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W36
	.byte	PEND
	.byte		N06   , Fn3 , v084
	.byte	W12
	.byte		N06
	.byte	W36
	.byte		        Cn3 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte		N06   , Fn3 , v084
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Cn3 
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte		N06   , Ds3 , v084
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte		N06   , Fn3 , v084
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte		N06   , Cs3 , v084
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte		N06   , Ds3 , v084
	.byte	W12
	.byte		N06
	.byte	W36
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte		        Fn3 
	.byte	W12
	.byte		N06
	.byte	W36
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_009_5 + 0x15
	.byte	PATT
	 .word	fe8_seq_009_5 + 0x22
	.byte	PATT
	 .word	fe8_seq_009_5 + 0x2F
	.byte	PATT
	 .word	fe8_seq_009_5 + 0x3E
	.byte	PATT
	 .word	fe8_seq_009_5 + 0x4D
	.byte	PATT
	 .word	fe8_seq_009_5 + 0x5E
	.byte	PATT
	 .word	fe8_seq_009_5 + 0x6D
	.byte		N06   , Gs3 , v084
	.byte	W06
	.byte		        Gs3 , v040
	.byte	W06
	.byte		        Gs3 , v084
	.byte	W06
	.byte		        Gs3 , v040
	.byte	W18
	.byte		        Gs3 , v084
	.byte	W12
	.byte		N06
	.byte	W06
	.byte		        Gs3 , v040
	.byte	W06
	.byte		        Gs3 , v084
	.byte	W06
	.byte		        Gs3 , v040
	.byte	W18
	.byte		        Gs3 , v084
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_009_5 + 0xA9
	.byte		N06   , Gn3 , v084
	.byte	W06
	.byte		        Gn3 , v040
	.byte	W06
	.byte		        Gn3 , v084
	.byte	W06
	.byte		        Gn3 , v040
	.byte	W18
	.byte		        Gn3 , v084
	.byte	W12
	.byte		N06
	.byte	W06
	.byte		        Gn3 , v040
	.byte	W06
	.byte		        Gn3 , v084
	.byte	W06
	.byte		        Gn3 , v040
	.byte	W18
	.byte		        Gn3 , v084
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_009_5 + 0xCD
	.byte	PATT
	 .word	fe8_seq_009_5 + 0xA9
	.byte	PATT
	 .word	fe8_seq_009_5 + 0xA9
	.byte	PATT
	 .word	fe8_seq_009_5 + 0xCD
	.byte	PATT
	 .word	fe8_seq_009_5 + 0xCD
	.byte		VOICE , 65
	.byte		VOL   , 33*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v-24
	.byte		N03   , Cn3 , v088
	.byte		N03   , Fn3 
	.byte	W06
	.byte		        Cn3 
	.byte		N03   , Fn3 
	.byte	W06
	.byte		        Cn3 
	.byte		N03   , Fn3 
	.byte	W06
	.byte		        Cn3 , v040
	.byte		N03   , Fn3 
	.byte	W78
	.byte		        Ds3 , v088
	.byte		N03   , Gn3 
	.byte	W06
	.byte		        Ds3 
	.byte		N03   , Gn3 
	.byte	W06
	.byte		        Ds3 
	.byte		N03   , Gn3 
	.byte	W06
	.byte		        Ds3 , v040
	.byte		N03   , Gn3 
	.byte	W54
	.byte		N24   , Gn3 , v088
	.byte	W24
	.byte		N03   , Cn3 
	.byte		N03   , Fn3 
	.byte	W06
	.byte		        Cn3 
	.byte		N03   , Fn3 
	.byte	W06
	.byte		        Cn3 
	.byte		N03   , Fn3 
	.byte	W06
	.byte		        Cn3 , v040
	.byte		N03   , Fn3 
	.byte	W54
	.byte		N06   , Fn2 , v084
	.byte	W06
	.byte		        An2 
	.byte	W06
	.byte		        Cn3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		N03   , Ds3 
	.byte		N03   , Gn3 
	.byte	W06
	.byte		        Ds3 
	.byte		N03   , Gn3 
	.byte	W06
	.byte		        Ds3 
	.byte		N03   , Gn3 
	.byte	W06
	.byte		        Ds3 , v040
	.byte		N03   , Gn3 
	.byte	W54
	.byte		N09   , Gn2 , v088
	.byte	W12
	.byte		        An2 
	.byte	W12
	.byte		N03   , Fn2 
	.byte		N03   , As2 
	.byte	W06
	.byte		        Fn2 
	.byte		N03   , As2 
	.byte	W06
	.byte		        Fn2 
	.byte		N03   , As2 
	.byte	W06
	.byte		        As2 , v040
	.byte	W78
	.byte		        Gs2 , v088
	.byte		N03   , Cn3 
	.byte	W06
	.byte		        Gs2 
	.byte		N03   , Cn3 
	.byte	W06
	.byte		        Gs2 
	.byte		N03   , Cn3 
	.byte	W06
	.byte		        Gs2 , v040
	.byte		N03   , Cn3 
	.byte	W54
	.byte		N24   , Cn3 , v088
	.byte	W24
	.byte		N03   , Fn2 
	.byte		N03   , As2 
	.byte	W06
	.byte		        Fn2 
	.byte		N03   , As2 
	.byte	W06
	.byte		        Fn2 
	.byte		N03   , As2 
	.byte	W06
	.byte		        Fn2 , v040
	.byte		N03   , As2 
	.byte	W54
	.byte		N06   , As1 , v084
	.byte	W06
	.byte		        Dn2 
	.byte	W06
	.byte		        Fn2 
	.byte	W06
	.byte		        As2 
	.byte	W06
	.byte		N03   , Gs2 , v088
	.byte		N03   , Cn3 , v084
	.byte	W06
	.byte		        Gs2 , v088
	.byte		N03   , Cn3 , v084
	.byte	W06
	.byte		        Gs2 , v088
	.byte		N03   , Cn3 , v084
	.byte	W06
	.byte		        Gs2 , v040
	.byte		N03   , Cn3 
	.byte	W54
	.byte		N21   , Fn2 , v100
	.byte	W24
	.byte		VOICE , 57
	.byte		VOL   , 47*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v-4
	.byte	W36
	.byte		N36   , Gs3 , v084
	.byte	W36
	.byte	W03
	.byte		N06   , Gs3 , v032
	.byte	W21
	.byte		        Ds3 , v084
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N36   , Fs3 
	.byte	W36
	.byte	W03
	.byte		N06   , Fs3 , v032
	.byte	W21
	.byte		        Bn2 , v084
	.byte	W18
	.byte		N06
	.byte	W18
	.byte		N36   , En3 
	.byte	W36
	.byte		N06   , En3 , v032
	.byte	W24
	.byte		N21   , As3 , v084
	.byte	W24
	.byte		        Gs3 
	.byte	W24
	.byte		        Fs3 
	.byte	W24
	.byte		        Gs3 
	.byte	W24
	.byte		N44   , As2 , v072
	.byte	W48
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W06
	.byte		        Gs2 
	.byte	W06
	.byte		N21   , As2 
	.byte	W24
	.byte	PEND
	.byte		N44
	.byte	W48
	.byte		N06
	.byte	W12
	.byte		        Cn3 
	.byte	W06
	.byte		        As2 
	.byte	W06
	.byte		N21   , Cn3 
	.byte	W24
	.byte		N44   , As2 , v072
	.byte	W48
	.byte		N06
	.byte	W12
	.byte		        Dn3 
	.byte	W06
	.byte		        Cn3 
	.byte	W06
	.byte		N21   , Dn3 
	.byte	W24
	.byte	PEND
	.byte		N44   , As2 
	.byte	W48
	.byte		N06
	.byte	W12
	.byte		        Ds3 
	.byte	W06
	.byte		        Dn3 
	.byte	W06
	.byte		N21   , Ds3 
	.byte	W24
	.byte	PATT
	 .word	fe8_seq_009_5 + 0x1F9
	.byte	PATT
	 .word	fe8_seq_009_5 + 0x212
	.byte		N44   , Cn3 , v072
	.byte	W48
	.byte		N06
	.byte	W12
	.byte		        Ds3 
	.byte	W06
	.byte		        Dn3 
	.byte	W06
	.byte		N21   , Ds3 
	.byte	W24
	.byte		N06   , As2 
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Fn3 
	.byte	W06
	.byte		        Ds3 
	.byte	W06
	.byte		N21   , Fn3 
	.byte	W24
	.byte		VOICE , 48
	.byte		VOL   , 42*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+16
	.byte	W12
	.byte		N12   , Gn2 , v084
	.byte	W12
	.byte		N06   , Fn2 
	.byte	W36
	.byte		N12   , As2 
	.byte	W12
	.byte		N06   , Gn2 
	.byte	W24
	.byte	W12
	.byte		N12   , An2 
	.byte	W12
	.byte		N06   , Dn2 
	.byte	W36
	.byte		N12   , Gn2 
	.byte	W12
	.byte		N09   , Gn3 , v056
	.byte	W09
	.byte		        Gn3 , v024
	.byte	W15
	.byte	W12
	.byte		N12   , Gn2 , v084
	.byte	W12
	.byte		N06   , Fn2 
	.byte	W36
	.byte		N12   , As2 
	.byte	W12
	.byte		N06   , Gn2 
	.byte	W24
	.byte	W12
	.byte		N12   , An2 
	.byte	W12
	.byte		N06   , As2 
	.byte	W36
	.byte		N12   , Gn2 
	.byte	W12
	.byte		N09   , Gn3 , v056
	.byte	W09
	.byte		        Gn3 , v024
	.byte	W15
	.byte		VOICE , 57
	.byte		VOL   , 47*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v-4
	.byte		N90   , As2 , v084
	.byte	W96
	.byte		N66   , Gn2 
	.byte	W72
	.byte		N06   , An2 
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		N42   , Cn3 
	.byte	W48
	.byte		N30   , An2 
	.byte	W36
	.byte		N06   , As2 
	.byte	W12
	.byte		N48   , An2 
	.byte	W60
	.byte		N06
	.byte	W12
	.byte		        As2 
	.byte	W12
	.byte		        Cn3 
	.byte	W12
	.byte	GOTO
	 .word	fe8_seq_009_5 + 0x3
	.byte	FINE

@*********************** Track 07 ***********************@

fe8_seq_009_6:
	.byte	KEYSH , fe8_seq_009_key+0
	.byte	W24
	.byte		VOICE , 126
	.byte		VOL   , 41*fe8_seq_009_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N06   , Fs1 , v064
	.byte	W36
	.byte		N06
	.byte	W12
	.byte		        Fs1 , v068
	.byte	W36
	.byte		        Fs1 , v048
	.byte	W12
	.byte		        Fs1 , v056
	.byte	W36
	.byte		        Fs1 , v052
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Fs1 , v056
	.byte	W06
	.byte		        Fs1 , v052
	.byte	W06
	.byte		N11   , As1 , v072
	.byte	W12
	.byte		N06   , Fs1 , v060
	.byte	W36
	.byte		        Fs1 , v072
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Fs1 , v076
	.byte	W24
	.byte		        Fs1 , v072
	.byte	W12
	.byte		        Fs1 , v080
	.byte	W36
	.byte		        Fs1 , v072
	.byte	W12
	.byte		        Fs1 , v076
	.byte	W12
	.byte		        Fs1 , v040
	.byte	W12
	.byte		        Fs1 , v076
	.byte	W12
	.byte		N11   , As1 , v068
	.byte	W12
	.byte		N06   , Fs1 , v060
	.byte	W36
	.byte		        Fs1 , v068
	.byte	W12
	.byte		        Fs1 , v060
	.byte	W12
	.byte		        Fs1 , v048
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Fs1 , v076
	.byte	W36
	.byte		        Fs1 , v068
	.byte	W12
	.byte		        Fs1 , v072
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N10   , As1 , v068
	.byte	W12
	.byte		N06   , Fs1 , v056
	.byte	W36
	.byte		        Fs1 , v068
	.byte	W12
	.byte		        Fs1 , v076
	.byte	W36
	.byte		        Fs1 , v072
	.byte	W12
	.byte		        Fs1 , v068
	.byte	W12
	.byte		N06
	.byte	W24
	.byte		        Fs1 , v076
	.byte	W12
	.byte		        Fs1 , v052
	.byte	W12
	.byte		N10   , As1 , v076
	.byte	W12
	.byte		N06   , Fs1 , v060
	.byte	W12
	.byte		        Fs1 , v076
	.byte	W06
	.byte		        Fs1 , v060
	.byte	W06
	.byte		        Fs1 , v064
	.byte	W36
	.byte		N06
	.byte	W12
	.byte		        Fs1 , v068
	.byte	W24
	.byte		N08   , Dn1 , v120
	.byte	W12
	.byte		N06   , Fs1 , v048
	.byte	W12
	.byte		        Fs1 , v056
	.byte	W36
	.byte		        Fs1 , v052
	.byte	W12
	.byte		        Fs1 , v036
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Fs1 , v056
	.byte	W06
	.byte		        Fs1 , v052
	.byte	W06
	.byte		N11   , As1 , v084
	.byte	W12
	.byte		N06   , Fs1 , v060
	.byte	W36
	.byte		        Fs1 , v072
	.byte	W12
	.byte		N06
	.byte	W12
	.byte		        Fs1 , v076
	.byte	W12
	.byte		N08   , Dn1 , v120
	.byte	W12
	.byte		N06   , Fs1 , v072
	.byte	W12
	.byte		        Fs1 , v080
	.byte	W36
	.byte		        Fs1 , v072
	.byte	W12
	.byte		        Fs1 , v076
	.byte	W12
	.byte		        Fs1 , v040
	.byte	W12
	.byte		        Dn1 , v112
	.byte	W12
	.byte		N11   , As1 , v068
	.byte	W12
	.byte		N07   , Dn1 , v116
	.byte	W36
	.byte		N05
	.byte	W12
	.byte		N06   , Fs1 , v060
	.byte	W12
	.byte		        Fs1 , v048
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		        Dn1 , v120
	.byte	W36
	.byte		N07   , Dn1 , v116
	.byte	W12
	.byte		N06   , Fs1 , v072
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N05   , Dn1 , v116
	.byte	W12
	.byte		N06
	.byte	W36
	.byte		N07
	.byte	W12
	.byte		N06   , Fs1 , v076
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N04   , Dn1 , v100
	.byte	W12
	.byte		N05
	.byte	W12
	.byte		        Dn1 , v120
	.byte	W24
	.byte		        Dn1 , v116
	.byte	W24
	.byte		N04
	.byte	W12
	.byte		N05   , Dn1 , v120
	.byte	W24
	.byte		N44   , Cs2 , v080
	.byte	W12
	.byte		N05   , Dn1 , v092
	.byte	W36
	.byte		        Dn1 , v116
	.byte	W12
	.byte		N06   , Dn1 , v100
	.byte	W24
	.byte		N04   , Dn1 , v112
	.byte	W12
	.byte		N05   , Dn1 , v092
	.byte	W12
	.byte		        Dn1 , v112
	.byte	W36
	.byte		N06   , Dn1 , v092
	.byte	W12
	.byte		N05   , Dn1 , v100
	.byte	W36
	.byte		        Dn1 , v112
	.byte	W12
	.byte		        Dn1 , v084
	.byte	W36
	.byte		        Dn1 , v116
	.byte	W12
	.byte		        Dn1 , v084
	.byte	W24
	.byte		N04   , Dn1 , v112
	.byte	W12
	.byte		N05   , Dn1 , v100
	.byte	W12
	.byte		        Dn1 , v080
	.byte	W24
	.byte		        Dn1 , v072
	.byte	W12
	.byte		        Dn1 , v100
	.byte	W12
	.byte		        Dn1 , v092
	.byte	W24
	.byte		N03   , Dn1 , v084
	.byte	W06
	.byte		        Dn1 , v068
	.byte	W06
	.byte		N05   , Dn1 , v076
	.byte	W12
	.byte		        Dn1 , v092
	.byte	W36
	.byte		        Dn1 , v100
	.byte	W12
	.byte		N06   , Dn1 , v080
	.byte	W24
	.byte		N04   , Dn1 , v092
	.byte	W12
	.byte		N05   , Dn1 , v084
	.byte	W12
	.byte		        Dn1 , v080
	.byte	W36
	.byte		N04   , Dn1 , v116
	.byte	W12
	.byte		N05   , Dn1 , v092
	.byte	W36
	.byte		N04   , Dn1 , v100
	.byte	W12
	.byte		N05   , Dn1 , v084
	.byte	W36
	.byte		N04   , Dn1 , v100
	.byte	W12
	.byte		N05
	.byte	W24
	.byte		N04   , Dn1 , v084
	.byte	W12
	.byte		        Dn1 , v092
	.byte	W12
	.byte		        Dn1 , v112
	.byte	W24
	.byte		        Dn1 , v080
	.byte	W12
	.byte		        Dn1 , v092
	.byte	W12
	.byte		N04
	.byte	W12
	.byte		        Dn1 , v100
	.byte	W12
	.byte		N03
	.byte	W06
	.byte		        Dn1 , v072
	.byte	W06
	.byte		N05   , Dn1 , v084
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W18
	.byte		TIE   , En2 , v127
	.byte	W54
	.byte		N24   , Ds1 , v100
	.byte	W24
	.byte		N12   , Dn1 , v108
	.byte	W60
	.byte		EOT   , En2 
	.byte		N04   , Dn1 , v056
	.byte	W04
	.byte		        Dn1 , v084
	.byte	W04
	.byte		N04
	.byte	W04
	.byte		N12   , Dn1 , v108
	.byte	W24
	.byte	W60
	.byte		N04   , Dn1 , v084
	.byte	W04
	.byte		N04
	.byte	W04
	.byte		N04
	.byte	W04
	.byte		N12   , Dn1 , v108
	.byte	W24
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_009_6 + 0x1D0
	.byte		N12   , Dn1 , v108
	.byte	W24
	.byte		N12
	.byte	W24
	.byte		N12
	.byte	W12
	.byte		N12
	.byte	W12
	.byte		N12
	.byte	W12
	.byte		N06
	.byte	W06
	.byte		N06
	.byte	W06
	.byte		N12
	.byte	W24
	.byte		N06   , Fs1 , v056
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N06   , Fs1 , v056
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W12
	.byte	PEND
	.byte		N06   , Fs1 , v056
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W24
	.byte	PEND
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W06
	.byte		        Fs1 , v024
	.byte	W06
	.byte		N12   , As1 , v052
	.byte	W12
	.byte	PATT
	 .word	fe8_seq_009_6 + 0x20A
	.byte	PATT
	 .word	fe8_seq_009_6 + 0x1FD
	.byte	PATT
	 .word	fe8_seq_009_6 + 0x20A
	.byte		N06   , Fs1 , v056
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W24
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W06
	.byte		        Fs1 , v024
	.byte	W06
	.byte	W12
	.byte		N12   , As1 , v032
	.byte	W12
	.byte		N06   , Fs1 , v056
	.byte	W36
	.byte		N12   , As1 , v032
	.byte	W12
	.byte		N06   , Fs1 , v056
	.byte	W12
	.byte		        Fs1 , v028
	.byte	W12
	.byte	PEND
	.byte	W12
	.byte		N12   , As1 , v032
	.byte	W12
	.byte		N06   , Fs1 , v056
	.byte	W36
	.byte		N04   , Fs2 , v048
	.byte	W04
	.byte		        Fs2 , v056
	.byte	W04
	.byte		        Fs2 , v068
	.byte	W04
	.byte		N06   , Fs2 , v080
	.byte	W12
	.byte		        Fs2 , v028
	.byte	W12
	.byte	PEND
	.byte	PATT
	 .word	fe8_seq_009_6 + 0x242
	.byte	PATT
	 .word	fe8_seq_009_6 + 0x257
	.byte	W24
	.byte		N42   , Dn2 , v076
	.byte	W60
	.byte		N12
	.byte	W12
	.byte		N24
	.byte	W24
	.byte		N24
	.byte	W48
	.byte		N24
	.byte	W24
	.byte		N42
	.byte	W84
	.byte		N12
	.byte	W12
	.byte		N42
	.byte	W48
	.byte		N42
	.byte	W48
	.byte	GOTO
	 .word	fe8_seq_009_6 + 0x3
	.byte	FINE

@******************************************************@

	.align	2

fe8_seq_009:
	.byte	7	@ NumTrks
	.byte	0	@ NumBlks
	.byte	fe8_seq_009_pri	@ Priority
	.byte	fe8_seq_009_rev	@ Reverb

	.word	fe8_seq_009_grp

	.word	fe8_seq_009_0
	.word	fe8_seq_009_1
	.word	fe8_seq_009_2
	.word	fe8_seq_009_3
	.word	fe8_seq_009_4
	.word	fe8_seq_009_5
	.word	fe8_seq_009_6

	.end
