/* Generated by BIN2S - please don't edit directly */
	.section .rodata
	.balign 4
	.global character_palette_Alfonse_lz_size
	.global character_palette_Alfonse_lz
character_palette_Alfonse_lz:
	.byte  16,160,  0,  0,  0, 85, 83,255,127,158, 99, 31, 75,  0, 57, 42
	.byte  73, 57,139, 69,197, 36,  0,152,119,210,106,203, 73,191, 95,  0
	.byte 217, 62,255,127,176, 41,165, 20,144, 16, 31,255,107,144, 31,243
	.byte 110, 45, 86,  0, 95, 75, 95, 34, 26,  0, 16,  4,192,240, 31, 48
	.byte  31,251, 91,231, 27,200, 38, 48,195, 25,240, 31, 48, 31,123,115
	.byte 182, 94, 12, 15, 78, 41, 57, 48, 31,240,127,115,127,  8,108,118
	.byte 104, 97, 16,127

	.global character_palette_Alfonse_lz_end
character_palette_Alfonse_lz_end:

	.balign 4
character_palette_Alfonse_lz_size: .int 100
