/* Generated by BIN2S - please don't edit directly */
	.section .rodata.character_palette_Laevatein_lz, "a"
	.balign 4
	.global character_palette_Laevatein_lz
character_palette_Laevatein_lz:
	.byte  16,160,  0,  0,  0, 84, 83,239, 61,214, 86,222, 90,  0,158, 37
	.byte 121,  8,203, 16,255, 27,  0,158, 26,107, 45,246, 37,115, 25,135
	.byte  16, 11, 63, 63,165, 20,240, 31,240, 31,240, 31,240,240, 31,240
	.byte  31,240, 31,240, 31,165, 20,  0

	.global character_palette_Laevatein_lz_end
character_palette_Laevatein_lz_end:

	.global character_palette_Laevatein_lz_size
	.balign 4
character_palette_Laevatein_lz_size: .int 56
