/* Generated by BIN2S - please don't edit directly */
	.section .rodata.character_palette_MyUnit_lz, "a"
	.balign 4
	.global character_palette_MyUnit_lz
character_palette_MyUnit_lz:
	.byte  16,128,  0,  0,  0, 85, 83,255,127,255,107,223, 46,  0, 46, 25
	.byte 123, 27, 58, 22,147, 33,  0,159, 87,189,115, 20, 54,156,107,  0
	.byte 249, 78, 17, 58, 98, 16,165, 20,252,240, 31,240, 31,240, 31,240
	.byte  31,240, 31, 48, 31,  0,  0,  0

	.global character_palette_MyUnit_lz_end
character_palette_MyUnit_lz_end:

	.global character_palette_MyUnit_lz_size
	.balign 4
character_palette_MyUnit_lz_size: .int 56
