/* Generated by BIN2S - please don't edit directly */
	.section .rodata
	.balign 4
	.global character_palette_Sharena_lz_size
	.global character_palette_Sharena_lz
character_palette_Sharena_lz:
	.byte  16,160,  0,  0,  0, 85, 83,255,127,255,107, 31, 75,  0, 24, 42
	.byte  46, 25,222,111,125, 91,  0,217, 70,171, 73,164, 32,222,119,  0
	.byte  83, 74,190,123, 15, 37,165, 20,128,144, 31,179,127,137,122, 98
	.byte  85,250,  0,  4,144, 12, 28, 91, 61, 66,153, 16, 49,209, 24,240
	.byte  31, 98, 85, 78, 50,  0, 73, 37,120, 83,113, 79,175, 54, 32,104
	.byte  33,240, 31, 98, 85,241, 57, 41,  0, 41,247, 94,181, 86, 49, 70
	.byte 107,  6, 45,165, 20,  0,  0,240,  1,144,  1,  0

	.global character_palette_Sharena_lz_end
character_palette_Sharena_lz_end:

	.balign 4
character_palette_Sharena_lz_size: .int 108
