/* Generated by BIN2S - please don't edit directly */
	.section .rodata
	.balign 4
	.global character_palette_Anna_lz_size
	.global character_palette_Anna_lz
character_palette_Anna_lz:
	.byte  16,160,  0,  0,  0, 85, 83,255,127,190,107, 30, 59,  0,138, 69
	.byte  90,103, 84, 78,212, 28,  0,152,119,243,110, 45, 86,251, 74,  0
	.byte 223,115, 75, 37,245, 41,165, 20,132, 16, 31,255,107, 31, 75,144
	.byte  31, 78, 90,  0, 28, 30,123,  4, 83,  0, 55, 46,192,240, 31, 48
	.byte  31,183, 59,  6,  7,  7, 34,192,240, 31, 80, 31,148, 90,238, 69
	.byte   8, 49,192, 80, 31,240,127,140,102,137, 93,101, 72,128, 16,127

	.global character_palette_Anna_lz_end
character_palette_Anna_lz_end:

	.balign 4
character_palette_Anna_lz_size: .int 96
