/* Generated by BIN2S - please don't edit directly */
	.section .rodata.character_palette_Dagr_lz, "a"
	.balign 4
	.global character_palette_Dagr_lz
character_palette_Dagr_lz:
	.byte  16, 64,  0,  0,  0, 31,  2,255,127, 94, 99, 29, 91,  0, 90, 50
	.byte 214, 33, 89, 66,222,119,  0, 90,107, 49, 70,239, 61, 24, 95,  0
	.byte 220,123, 54,103,115, 78,165, 20,192,240, 31,176, 31,  0,  0,  0

	.global character_palette_Dagr_lz_end
character_palette_Dagr_lz_end:

	.global character_palette_Dagr_lz_size
	.balign 4
character_palette_Dagr_lz_size: .int 48
