/* Generated by BIN2S - please don't edit directly */
	.section .rodata.character_palette_Eitri_lz, "a"
	.balign 4
	.global character_palette_Eitri_lz
character_palette_Eitri_lz:
	.byte  16,128,  0,  0,  0,138, 70,107, 45, 62, 87,255,127,  0,157, 99
	.byte  59, 87,150, 66,113, 29,  0, 99, 12,255,119, 58, 54, 57, 99,  0
	.byte 181, 86, 90,107, 99, 12,165, 20,252,240, 31,240, 31,240, 31,240
	.byte  31,240, 31, 48, 31,  0,  0,  0

	.global character_palette_Eitri_lz_end
character_palette_Eitri_lz_end:

	.global character_palette_Eitri_lz_size
	.balign 4
character_palette_Eitri_lz_size: .int 56
