/* Generated by BIN2S - please don't edit directly */
	.section .rodata.character_palette_Takumi_lz, "a"
	.balign 4
	.global character_palette_Takumi_lz
character_palette_Takumi_lz:
	.byte  16, 32,  0,  0,  0, 85, 83,255,127,191,111, 95, 95,  0, 46, 25
	.byte  93, 99, 87, 58,208, 53,  0,167,106,197, 77, 37, 53,213,123,  0
	.byte 171,123,232, 65, 72,111,165, 20

	.global character_palette_Takumi_lz_end
character_palette_Takumi_lz_end:

	.global character_palette_Takumi_lz_size
	.balign 4
character_palette_Takumi_lz_size: .int 40
