/* Generated by BIN2S - please don't edit directly */
	.section .rodata
	.balign 4
	.global character_palette_Xander_lz_size
	.global character_palette_Xander_lz
character_palette_Xander_lz:
	.byte  16,160,  0,  0,  0, 85, 83,255,127,255, 91, 41, 33,  0,244, 49
	.byte 165, 20,254, 54,165, 16,  0, 49, 70, 99,  8, 41, 33, 42,  0,  0
	.byte  29, 71, 54, 50, 78, 29,165, 20,254,240, 31,240, 31,240, 31,240
	.byte  31,240, 31,240, 31,240, 31,165,  0, 20,  0,  0

	.global character_palette_Xander_lz_end
character_palette_Xander_lz_end:

	.balign 4
character_palette_Xander_lz_size: .int 60
