/* Generated by BIN2S - please don't edit directly */
	.section .rodata.character_palette_Nott_lz, "a"
	.balign 4
	.global character_palette_Nott_lz
character_palette_Nott_lz:
	.byte  16,128,  0,  0,  0,  0,  0,159,107, 29, 91,122, 70,  0, 41, 37
	.byte 255,123,122,107,173, 49,  0, 90,103,255,127,247, 90,156,115,  0
	.byte  49, 70, 74, 41,255,127,165, 20,252,240, 31,240, 31,240, 31,240
	.byte  31,240, 31, 48, 31,  0,  0,  0

	.global character_palette_Nott_lz_end
character_palette_Nott_lz_end:

	.global character_palette_Nott_lz_size
	.balign 4
character_palette_Nott_lz_size: .int 56
