/* Generated by BIN2S - please don't edit directly */
	.section .rodata
	.balign 4
	.global S2132_png_cfg_size
	.global S2132_png_cfg
S2132_png_cfg:
	.byte  16,  0,  0,  0,  0,  0,  0,  0

	.global S2132_png_cfg_end
S2132_png_cfg_end:

	.balign 4
S2132_png_cfg_size: .int 8
