/* Generated by BIN2S - please don't edit directly */
	.section .rodata.S505_cfg, "a"
	.balign 4
	.global S505_cfg
S505_cfg:
	.byte  16,  0,  0,  0,  0,  0,  0,  0

	.global S505_cfg_end
S505_cfg_end:

	.global S505_cfg_size
	.balign 4
S505_cfg_size: .int 8
