. = 0x8019f80;
.text.GenerateUnitMovementMapInjector : {*(.text.GenerateUnitMovementMapInjector)}
. = 0x8019fc0;
.text.GenerateUnitMovementMapExtInjector : {*(.text.GenerateUnitMovementMapExtInjector)}
. = 0x801a090;
.text.GenerateMovementMapOnWorkingMapInjector : {*(.text.GenerateMovementMapOnWorkingMapInjector)}
. = 0x802a6a4;
.text.BattleInitTargetCanCounterInjector : {*(.text.BattleInitTargetCanCounterInjector)}

