. = 0x80bcfa8;
.rodata.patch_opening_movie_disabler_bcfa8 : {*(.rodata.patch_opening_movie_disabler_bcfa8)}
. = 0x8012e24;
.rodata.patch_opening_movie_disabler_12e24 : {*(.rodata.patch_opening_movie_disabler_12e24)}
. = 0x8012e1a;
.rodata.patch_opening_movie_disabler_12e1a : {*(.rodata.patch_opening_movie_disabler_12e1a)}
. = 0x8012e1c;
.rodata.patch_opening_movie_disabler_12e1c : {*(.rodata.patch_opening_movie_disabler_12e1c)}