. = 0x8054850;
.rodata.patch_expand_animation_script_compression_type_54850 : {*(.rodata.patch_expand_animation_script_compression_type_54850)}
. = 0x80548ec;
.rodata.patch_expand_animation_script_compression_type_548ec : {*(.rodata.patch_expand_animation_script_compression_type_548ec)}
. = 0x8055316;
.rodata.patch_expand_animation_script_compression_type_55316 : {*(.rodata.patch_expand_animation_script_compression_type_55316)}
. = 0x8055318;
.rodata.patch_expand_animation_script_compression_type_55318 : {*(.rodata.patch_expand_animation_script_compression_type_55318)}