. = 0x8054850;
.rodata.patch_expand_animation_script_compression_type_54850 : {*(.rodata.patch_expand_animation_script_compression_type_54850)}
. = 0x80548ec;
.rodata.patch_expand_animation_script_compression_type_548ec : {*(.rodata.patch_expand_animation_script_compression_type_548ec)}
. = 0x8055316;
.rodata.patch_expand_animation_script_compression_type_55316 : {*(.rodata.patch_expand_animation_script_compression_type_55316)}
. = 0x8055318;
.rodata.patch_expand_animation_script_compression_type_55318 : {*(.rodata.patch_expand_animation_script_compression_type_55318)}
. = 0x805549e;
.rodata.patch_expand_animation_script_compression_type_5549e : {*(.rodata.patch_expand_animation_script_compression_type_5549e)}
. = 0x80554a0;
.rodata.patch_expand_animation_script_compression_type_554a0 : {*(.rodata.patch_expand_animation_script_compression_type_554a0)}

. = 0x8054952;
.rodata.patch_expand_animation_oam_r_compression_type_54952 : {*(.rodata.patch_expand_animation_oam_r_compression_type_54952)}
. = 0x8054954;
.rodata.patch_expand_animation_oam_r_compression_type_54954 : {*(.rodata.patch_expand_animation_oam_r_compression_type_54954)}
. = 0x8055376;
.rodata.patch_expand_animation_oam_r_compression_type_55376 : {*(.rodata.patch_expand_animation_oam_r_compression_type_55376)}
. = 0x8055378;
.rodata.patch_expand_animation_oam_r_compression_type_55378 : {*(.rodata.patch_expand_animation_oam_r_compression_type_55378)}

. = 0x80548b8;
.rodata.patch_expand_animation_oam_l_compression_type_548b8 : {*(.rodata.patch_expand_animation_oam_l_compression_type_548b8)}
. = 0x8055354;
.rodata.patch_expand_animation_oam_l_compression_type_55354 : {*(.rodata.patch_expand_animation_oam_l_compression_type_55354)}

. = 0x805486e;
.rodata.patch_expand_animation_palette_compression_type_5486e : {*(.rodata.patch_expand_animation_palette_compression_type_5486e)}
. = 0x8054870;
.rodata.patch_expand_animation_palette_compression_type_54870 : {*(.rodata.patch_expand_animation_palette_compression_type_54870)}
. = 0x8054908;
.rodata.patch_expand_animation_palette_compression_type_54908 : {*(.rodata.patch_expand_animation_palette_compression_type_54908)}
. = 0x805541a;
.rodata.patch_expand_animation_palette_compression_type_5541a : {*(.rodata.patch_expand_animation_palette_compression_type_5541a)}
. = 0x805541c;
.rodata.patch_expand_animation_palette_compression_type_5541c : {*(.rodata.patch_expand_animation_palette_compression_type_5541c)}

. = 0x8054882;
.rodata.patch_expand_animation_character_palette_compression_type_54882 : {*(.rodata.patch_expand_animation_character_palette_compression_type_54882)}
. = 0x8054884;
.rodata.patch_expand_animation_character_palette_compression_type_54884 : {*(.rodata.patch_expand_animation_character_palette_compression_type_54884)}
. = 0x805491c;
.rodata.patch_expand_animation_character_palette_compression_type_5491c : {*(.rodata.patch_expand_animation_character_palette_compression_type_5491c)}
. = 0x8055436;
.rodata.patch_expand_animation_character_palette_compression_type_55436 : {*(.rodata.patch_expand_animation_character_palette_compression_type_55436)}
. = 0x8055438;
.rodata.patch_expand_animation_character_palette_compression_type_55438 : {*(.rodata.patch_expand_animation_character_palette_compression_type_55438)}

. = 0x8051f92;
.rodata.patch_expand_animation_sheet_compression_type_51f92 : {*(.rodata.patch_expand_animation_sheet_compression_type_51f92)}
. = 0x8051f94;
.rodata.patch_expand_animation_sheet_compression_type_51f94 : {*(.rodata.patch_expand_animation_sheet_compression_type_51f94)}
. = 0x8051fb6;
.rodata.patch_expand_animation_sheet_compression_type_51fb6 : {*(.rodata.patch_expand_animation_sheet_compression_type_51fb6)}
. = 0x8051fb8;
.rodata.patch_expand_animation_sheet_compression_type_51fb8 : {*(.rodata.patch_expand_animation_sheet_compression_type_51fb8)}
. = 0x8051fc4;
.rodata.patch_expand_animation_sheet_compression_type_51fc4 : {*(.rodata.patch_expand_animation_sheet_compression_type_51fc4)}
. = 0x8051fd0;
.rodata.patch_expand_animation_sheet_compression_type_51fd0 : {*(.rodata.patch_expand_animation_sheet_compression_type_51fd0)}
. = 0x8054778;
.rodata.patch_expand_animation_sheet_compression_type_54778 : {*(.rodata.patch_expand_animation_sheet_compression_type_54778)}

