//
// Created by laqieer on 2020/11/27.
//

#ifndef FE7_JP_STUNNING_TRIBBLE_ANIMATION_ID_H
#define FE7_JP_STUNNING_TRIBBLE_ANIMATION_ID_H

#define ANIMATION_BALLISTA 0x8b
#define ANIMATION_ANNA_AXE 0xca
#define ANIMATION_ANNA_HANDAXE 0xcb
#define ANIMATION_ANNA_UNARMED 0xcc

#endif //FE7_JP_STUNNING_TRIBBLE_ANIMATION_ID_H
