//
// Created by laqieer on 2020/11/27.
//

#ifndef FE7_JP_STUNNING_TRIBBLE_ANIMATION_ID_H
#define FE7_JP_STUNNING_TRIBBLE_ANIMATION_ID_H

#define ANIMATION_BALLISTA 0x8b
#define ANIMATION_ANNA_AXE 0xca
#define ANIMATION_ANNA_HANDAXE 0xcb
#define ANIMATION_ANNA_UNARMED 0xcc
#define ANIMATION_GREAT_KNIGHT_SWORD 0xd5
#define ANIMATION_GREAT_KNIGHT_LANCE 0xd6
#define ANIMATION_GREAT_KNIGHT_AXE 0xd7
#define ANIMATION_GREAT_KNIGHT_HAND_AXE 0xd8
#define ANIMATION_GREAT_KNIGHT_DISARMED 0xd9
#define ANIMATION_DRACOZOMBIE 0xda
#define ANIMATION_WARRIOR_FEMALE_AXE 0xdb
#define ANIMATION_WARRIOR_FEMALE_HANDAXE 0xdc
#define ANIMATION_WARRIOR_FEMALE_BOW 0xdd
#define ANIMATION_WARRIOR_FEMALE_UNARMED 0xde
#define ANIMATION_WITCH_MAGIC 0xdf
#define ANIMATION_WITCH_STAFF 0xe0

#endif //FE7_JP_STUNNING_TRIBBLE_ANIMATION_ID_H
