//
// Created by laqieer on 2020/3/24.
//

#ifndef FE7_JP_STUNNING_TRIBBLE_CHARACTER_ID_H
#define FE7_JP_STUNNING_TRIBBLE_CHARACTER_ID_H

#define CHARACTER_ALFONSE_ID 1
#define CHARACTER_ANNA_ID 2
#define CHARACTER_SHARENA_ID 3
#define CHARACTER_BRUNO_ID 0x51
#define CHARACTER_XANDER_ID 0x5A
#define CHARACTER_VERONICA_ID 0x5B

#endif //FE7_JP_STUNNING_TRIBBLE_CHARACTER_ID_H
