//
// Created by laqieer on 2020/3/24.
//

#ifndef FE7_JP_STUNNING_TRIBBLE_CHARACTER_ID_H
#define FE7_JP_STUNNING_TRIBBLE_CHARACTER_ID_H

#define CHARACTER_ALFONSE_ID 1
#define CHARACTER_ALFONS_ID CHARACTER_ALFONSE_ID
#define CHARACTER_ANNA_ID 2
#define CHARACTER_SHARENA_ID 3
#define CHARACTER_SHARON_ID CHARACTER_SHARENA_ID
#define CHARACTER_BRUNO_ID 0x51
#define CHARACTER_XANDER_ID 0x5A
#define CHARACTER_VERONICA_ID 0x5B

#define CHARACTER_GENERIC_EMBLIAN_ID 0x67
#define CHARACTER_GENERIC_EMBLIAN_WEAK_ID 0x68
#define CHARACTER_GENERIC_EMBLIAN_STRONG_ID 0x69
#define CHARACTER_GENERIC_SUMMONED_ID 0x72
#define CHARACTER_GENERIC_SUMMONED_WEAK_ID 0x73
#define CHARACTER_GENERIC_SUMMONED_STRONG_ID 0x74
#define CHARACTER_GENERIC_ASKR_ID 0x75
#define CHARACTER_GENERIC_ASKR_WEAK_ID 0x76
#define CHARACTER_GENERIC_ASKR_STRONG_ID 0x77
#define CHARACTER_GENERIC_FLAME_ID 0x7c
#define CHARACTER_GENERIC_FLAME_WEAK_ID 0x7d
#define CHARACTER_GENERIC_FLAME_STRONG_ID 0x7e
#define CHARACTER_GENERIC_SUMMONED_DROP_ID 0x7f
#define CHARACTER_GENERIC_SUMMONED_DROP_WEAK_ID 0x80
#define CHARACTER_GENERIC_SUMMONED_DROP_STRONG_ID 0x81
#define CHARACTER_GENERIC_EMBLIAN_DROP_WEAK_ID 0x82
#define CHARACTER_GENERIC_EMBLIAN_SUPER_WEAK_ID 0x88

#endif //FE7_JP_STUNNING_TRIBBLE_CHARACTER_ID_H
