//
// Created by laqieer on 2020/3/24.
//

#ifndef FE7_JP_STUNNING_TRIBBLE_CHARACTER_ID_H
#define FE7_JP_STUNNING_TRIBBLE_CHARACTER_ID_H

#define CHARACTER_ALFONSE_ID 1
#define CHARACTER_ALFONS_ID CHARACTER_ALFONSE_ID
#define CHARACTER_ANNA_ID 2
#define CHARACTER_SHARENA_ID 3
#define CHARACTER_SHARON_ID CHARACTER_SHARENA_ID
#define CHARACTER_BRUNO_ID 0x51
#define CHARACTER_XANDER_ID 0x5A
#define CHARACTER_MARKS_ID CHARACTER_XANDER_ID
#define CHARACTER_VERONICA_ID 0x5B
#define CHARACTER_EIR_ID 0x1D
#define CHARACTER_FJORM_ID 0xF
#define CHARACTER_CERISE_ID 0x11
#define CHARACTER_GUNNTHRA_ID CHARACTER_CERISE_ID
#define CHARACTER_HELBINDI_ID 8
#define CHARACTER_FREEZE_ID 0x17
#define CHARACTER_HRID_ID CHARACTER_FREEZE_ID
#define CHARACTER_LAEGJARN_ID 6
#define CHARACTER_LAEVATEIN_ID 4
#define CHARACTER_LIF_ID 7
#define CHARACTER_LOKI_ID 0x1B
#define CHARACTER_PEONY_ID 0x25
#define CHARACTER_SURTR_ID 0x2C
#define CHARACTER_SRASIR_ID 0x13
#define CHARACTER_YURG_ID 0x14
#define CHARACTER_HELL_ID 0x44
#define CHARACTER_GUSTAF_ID 0x7B
#define CHARACTER_LUPINE_ID 0x31
#define CHARACTER_MIRABILIS_ID CHARACTER_LUPINE_ID
#define CHARACTER_SCABIOSA_ID 0x1E
#define CHARACTER_PLUMERIA_ID 0x1F

#define CHARACTER_GENERIC_EMBLIAN_ID 0x67
#define CHARACTER_GENERIC_EMBLIAN_WEAK_ID 0x68
#define CHARACTER_GENERIC_EMBLIAN_STRONG_ID 0x69
#define CHARACTER_GENERIC_SUMMONED_ID 0x72
#define CHARACTER_GENERIC_SUMMONED_WEAK_ID 0x73
#define CHARACTER_GENERIC_SUMMONED_STRONG_ID 0x74
#define CHARACTER_GENERIC_ASKR_ID 0x75
#define CHARACTER_GENERIC_ASKR_WEAK_ID 0x76
#define CHARACTER_GENERIC_ASKR_STRONG_ID 0x77
#define CHARACTER_GENERIC_FLAME_ID 0x7c
#define CHARACTER_GENERIC_FLAME_WEAK_ID 0x7d
#define CHARACTER_GENERIC_FLAME_STRONG_ID 0x7e
#define CHARACTER_GENERIC_SUMMONED_DROP_ID 0x7f
#define CHARACTER_GENERIC_SUMMONED_DROP_WEAK_ID 0x80
#define CHARACTER_GENERIC_SUMMONED_DROP_STRONG_ID 0x81
#define CHARACTER_GENERIC_EMBLIAN_DROP_WEAK_ID 0x82
#define CHARACTER_GENERIC_EMBLIAN_SUPER_WEAK_ID 0x88

#define CHARACTER_TACTICIAN_ID 0xcd

#endif //FE7_JP_STUNNING_TRIBBLE_CHARACTER_ID_H
