#define ITEM_EMBLEM_SEAL_ICON 157

#define PASSIVE_SKILL_A_ICON 0xAD
#define PASSIVE_SKILL_B_ICON 0xAE
#define PASSIVE_SKILL_C_ICON 0xAF
#define PASSIVE_SKILL_S_ICON 0xB0

#define ITEM_ICON_IRON_DAGGER 0xB1
#define ITEM_ICON_STEEL_DAGGER 0xB2
#define ITEM_ICON_SILVER_DAGGER 0xB3
#define ITEM_ICON_POISON_DAGGER 0xB4
#define ITEM_ICON_SMOKE_DAGGER 0xB5
#define ITEM_ICON_ROGUE_DAGGER 0xB6

#define ITEM_ICON_WRETCHED_AIR 0x79

#define ITEM_ICON_SHARP_CLAW 0xB7
#define ITEM_ICON_ROTTEN_CLAW 0xB8
#define ITEM_ICON_FETID_CLAW 0xB9
#define ITEM_ICON_POISON_CLAW 0xBA
#define ITEM_ICON_LETHAL_CLAW 0xBB

#define ITEM_ICON_FIERY_FANG 0xBC
#define ITEM_ICON_HELL_FANG 0xBD
#define ITEM_ICON_NIGHTMARE_FANG 0xBE

#define ITEM_ICON_DIVINE_DRAGONSTONE 0xBF

#define ITEM_ICON_LEIPTR 0xC0

#define STATE_ICON_TRIANGLE_ADEPT 0xC1
#define STATE_ICON_ISOLATION 0xC2
