//
// Created by laqieer on 2020/3/27.
//

#ifndef FE7_JP_STUNNING_TRIBBLE_ITEM_ID_H
#define FE7_JP_STUNNING_TRIBBLE_ITEM_ID_H

#define ITEM_WYRMSLAYER 0xf
#define ITEM_FORBLAZE 0x3c
#define ITEM_DURANDAL 0x84
#define ITEM_ARMADS 0x85
#define ITEM_SOL_KATTI 0x8c
#define ITEM_STAFF_HEAL 0x4a
#define ITEM_STAFF_MEND 0x4b
#define ITEM_STAFF_RECOVER 0x4c
#define ITEM_STAFF_PHYSIC 0x4d
#define ITEM_STAFF_FORTIFY 0x4e
#define ITEM_VULNERARY 0x6b
#define ITEM_ELIXIR 0x6c
#define ITEM_VULNERARY_2 0x9a
#define ITEM_HAND_AXE 0x28
#define ITEM_TOMAHAWK 0x29

#define ITEM_SACRED_SEAL_QUICKENED_PULSE 0x9b
#define ITEM_SACRED_SEAL_EMBLA_WARD 0x9c
#define ITEM_SACRED_SEAL_MUSPELL_FLAME 0x9d
#define ITEM_LEIPTR 0x9e
#define ITEM_IRON_DAGGER 0x9f
#define ITEM_STEEL_DAGGER 0xa0
#define ITEM_SILVER_DAGGER 0xa1
#define ITEM_POISON_DAGGER 0xa2
#define ITEM_SMOKE_DAGGER 0xa3
#define ITEM_ROGUE_DAGGER 0xa4

#define ITEM_SACRED_SEAL_DEFLECT_MELEE 0xa5
#define ITEM_SACRED_SEAL_DEFLECT_MISSILE 0xa6
#define ITEM_SACRED_SEAL_DEFLECT_MAGIC 0xa7

#endif //FE7_JP_STUNNING_TRIBBLE_ITEM_ID_H
