//
// Created by laqieer on 2020/3/27.
//

#ifndef FE7_JP_STUNNING_TRIBBLE_ITEM_ID_H
#define FE7_JP_STUNNING_TRIBBLE_ITEM_ID_H

#define ITEM_STAFF_HEAL 0x4a
#define ITEM_STAFF_MEND 0x4b
#define ITEM_STAFF_RECOVER 0x4c
#define ITEM_STAFF_PHYSIC 0x4d
#define ITEM_STAFF_FORTIFY 0x4e
#define ITEM_VULNERARY 0x6b
#define ITEM_ELIXIR 0x6c
#define ITEM_VULNERARY_2 0x9a

#endif //FE7_JP_STUNNING_TRIBBLE_ITEM_ID_H
