//
// Created by laqieer on 2020/3/27.
//

#ifndef FE7_JP_STUNNING_TRIBBLE_JOB_ID_H
#define FE7_JP_STUNNING_TRIBBLE_JOB_ID_H

#define JOB_ID_MAGE_KNIGHT 100

#endif //FE7_JP_STUNNING_TRIBBLE_JOB_ID_H
