//
// Created by laqieer on 2020/3/27.
//

#ifndef FE7_JP_STUNNING_TRIBBLE_JOB_ID_H
#define FE7_JP_STUNNING_TRIBBLE_JOB_ID_H

#define JOB_ID_BISHOP 0x1E
#define JOB_ID_BISHOP_F 0x1F
#define JOB_ID_MAGIC_ARMOUR 98
#define JOB_ID_MAGIC_FALCON 99
#define JOB_ID_MAGE_KNIGHT 100
#define JOB_ID_HALBERDIER 101
#define JOB_ID_BONEWALKER 102
#define JOB_ID_BONEWALKER_BOW 103
#define JOB_ID_GHOST_FIRE 104
#define JOB_ID_PHANTOM 105
#define JOB_ID_REVENANT 106
#define JOB_ID_SKELEMONK 107
#define JOB_ID_UNDEAD_MANAKETE 108

#endif //FE7_JP_STUNNING_TRIBBLE_JOB_ID_H
