//
// Created by laqieer on 2020/2/13.
//

// FEHで使用されている楽曲: https://wikiwiki.jp/adan/BGM

#ifndef FE7_JP_STUNNING_TRIBBLE_MUSIC_ID_H
#define FE7_JP_STUNNING_TRIBBLE_MUSIC_ID_H

#define MUSIC_WIND_ACROSS_THE_PLAIN 48
#define MUSIC_COMPANIONS 2
#define MUSIC_SHADOW_APPROACHES 7
#define MUSIC_TOGETHER_WE_RIDE 0x42

#define MUSIC_EVENT_SERIOUS_3 0x405

#define MUSIC_MAP_BRAVE_1 0x406
#define MUSIC_MAP_BRAVE_2 0x407
#define MUSIC_MAP_BRAVE_3 0x408

#define MUSIC_MAP_FES_1 0x409

#define MUSIC_MAP_FE03 0x40a
#define MUSIC_MAP_FE06 0x40b
#define MUSIC_MAP_FE07 0x40c
#define MUSIC_MAP_FE11 0x40d
#define MUSIC_MAP_FE12 0x40e
#define MUSIC_MAP_FE13_1 0x40f
#define MUSIC_MAP_FE13_2 0x410
#define MUSIC_MAP_FE14_1 0x411
#define MUSIC_MAP_FE14_2 0x412

#define MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE 0x413

#define MUSIC_FE_H_EVENT_1 0x414
#define MUSIC_FE_H_GEAR_UP 0x415
#define MUSIC_FE_H_MAP_BOOK_2 0x416
#define MUSIC_FE_H_SERIOUS_6 0x417
#define MUSIC_FE_H_SERIOUS_6B 0x418
#define MUSIC_FE_H_TEMPEST_TRIAL 0x419

#define MUSIC_FE_3_DIVINE_DRAGON_LEGEND 117
#define MUSIC_FE_IF_END_ALL 0x41b

#define SFX_REACTION 0xEF

#define FIRE_EMBLEM_THEME 0x5A
#define FIRE_EMBLEM_THEME_LOOPED 0x5B
#define FIRE_EMBLEM_THEME_WITH_INTRO 0x5F
#define MAIN_THEME_ARRANGE 0x45

#define MUSIC_FE_AWAKENING_ID_SERENITY 0x41c
#define MUSIC_FE_AWAKENING_ID_PURPOSE 0x41d

#define MUSIC_FE_3_DIVINE_DRAGON_LEGEND_B 0x41e
#define MUSIC_FE_3_HEROES_WAR 0x41f

#define MUSIC_FE_FATES_ROAD_TAKEN 0x420
#define MUSIC_FE_FATES_AS_ALL_STARS_FALL 0x421

#define MUSIC_FE_AWAKENING_MAIN_THEME_TITLE 0x422
#define MUSIC_FE_AWAKENING_YOU_CAN_CALL_ME_MARTH 0x423

#define MUSIC_FE_PATH_OF_RADIANCE_LIKE_FATHER_LIKE_SON 0x424
#define MUSIC_FE_PATH_OF_RADIANCE_POWER_HUNGRY_FOOL 0x425

#define MUSIC_FE_GAIDEN_CELICA_MAP_1 0x426
#define MUSIC_FE_GAIDEN_FINAL_MAP 0x427
#define MUSIC_FE_GAIDEN_SEPARATE_WAYS 0x428
#define MUSIC_FE_GAIDEN_ENCOUNTER 0x429

#define MUSIC_FE_PATH_OF_RADIANCE_BEAUTIFUL_PRINCESS_ELINCIA 0x42a
#define MUSIC_FE_PATH_OF_RADIANCE_LIFE_RETURNS 0x42b

#define MUSIC_FE_FATES_DESIRE_BELOW 0x42c
#define MUSIC_FE_FATES_DUSK_FALLS 0x42d
#define MUSIC_FE_FATES_JUSTICE_RIP 0x42e

#endif //FE7_JP_STUNNING_TRIBBLE_MUSIC_ID_H
