//
// Created by laqieer on 2020/2/12.
//

#ifndef FE7_JP_STUNNING_TRIBBLE_PORTRAIT_ID_H
#define FE7_JP_STUNNING_TRIBBLE_PORTRAIT_ID_H

#define PORTRAIT_TODO "\x1\x1"

#define PORTRAIT_CURRENT "\xff\xff"

#define PORTRAIT_ALFONSE "\x1\x2"
#define PORTRAIT_SHARENA "\x2\x2"
#define PORTRAIT_ANNA "\x3\x2"
#define PORTRAIT_BRUNO_MASKED "\x4\x2"
#define PORTRAIT_VERONICA "\x5\x2"
#define PORTRAIT_DEATH_KNIGHT "\x6\x2"
#define PORTRAIT_EIR_DEATH "\x7\x2"
#define PORTRAIT_EIR PORTRAIT_EIR_DEATH
#define PORTRAIT_EIR_LIFE "\x8\x2"
#define PORTRAIT_FJORM "\x9\x2"
#define PORTRAIT_GUNNTHRA "\xA\x2"
#define PORTRAIT_HELBINDI "\xB\x2"
#define PORTRAIT_HRID "\xC\x2"
#define PORTRAIT_KRONYA "\xD\x2"
#define PORTRAIT_LAEGJARN "\xE\x2"
#define PORTRAIT_LAEVATEIN "\xF\x2"
#define PORTRAIT_LIF "\x10\x2"
#define PORTRAIT_LOKI "\x11\x2"
#define PORTRAIT_PEONY "\x12\x2"
#define PORTRAIT_SURTR "\x13\x2"
#define PORTRAIT_THRASIR "\x14\x2"
#define PORTRAIT_YLGR "\x15\x2"
#define PORTRAIT_XANDER "\x16\x2"
#define PORTRAIT_HEL "\x17\x2"
#define PORTRAIT_FREYR "\x18\x2"
#define PORTRAIT_GUSTAV "\x19\x2"
#define PORTRAIT_HENRIETTE "\x1A\x2"
#define PORTRAIT_LUPINUS "\x1B\x2"
#define PORTRAIT_THORR "\x1C\x2"
#define PORTRAIT_TRIANDRA "\x1D\x2"
#define PORTRAIT_PLUMERIA "\x1E\x2"
#define PORTRAIT_HOOD "\x1F\x2"

#define PORTRAIT_GENERIC_SODIER_BLUE "\x20\x2"
#define PORTRAIT_GENERIC_SODIER_RED "\x21\x2"

#define CLASSCARD_LORD 0x130
#define CLASSCARD_MAGE_KNIGHT 0x131

#endif //FE7_JP_STUNNING_TRIBBLE_PORTRAIT_ID_H
