//
// Created by laqieer on 2020/2/12.
//

#ifndef FE7_JP_STUNNING_TRIBBLE_PORTRAIT_ID_H
#define FE7_JP_STUNNING_TRIBBLE_PORTRAIT_ID_H

#define PORTRAIT_TODO "\x1\x1"

#define PORTRAIT_CURRENT "\xff\xff"

#define PORTRAIT_ALFONSE "\x1\x2"
#define PORTRAIT_SHARENA "\x2\x2"
#define PORTRAIT_ANNA "\x3\x2"
#define PORTRAIT_BRUNO_MASKED "\x4\x2"
#define PORTRAIT_VERONICA "\x5\x2"
#define PORTRAIT_EIR_DEATH "\x7\x2"
#define PORTRAIT_EIR PORTRAIT_EIR_DEATH
#define PORTRAIT_EIR_LIFE "\x8\x2"
#define PORTRAIT_FJORM "\x9\x2"
#define PORTRAIT_GUNNTHRA "\xA\x2"
#define PORTRAIT_HELBINDI "\xB\x2"
#define PORTRAIT_HRID "\xC\x2"
#define PORTRAIT_FREYJA "\xD\x2"
#define PORTRAIT_LAEGJARN "\xE\x2"
#define PORTRAIT_LAEVATEIN "\xF\x2"
#define PORTRAIT_LAEVATAIN PORTRAIT_LAEVATEIN
#define PORTRAIT_LIF "\x10\x2"
#define PORTRAIT_LOKI "\x11\x2"
#define PORTRAIT_PEONY "\x12\x2"
#define PORTRAIT_SURTR "\x13\x2"
#define PORTRAIT_THRASIR "\x14\x2"
#define PORTRAIT_YLGR "\x15\x2"
#define PORTRAIT_XANDER "\x16\x2"
#define PORTRAIT_HEL "\x17\x2"
#define PORTRAIT_FREYR "\x18\x2"
#define PORTRAIT_GUSTAV "\x19\x2"
#define PORTRAIT_GUSTAF PORTRAIT_GUSTAV
#define PORTRAIT_HENRIETTE "\x1A\x2"
#define PORTRAIT_MIRABILIS "\x1B\x2"
#define PORTRAIT_THORR "\x1C\x2"
#define PORTRAIT_TRIANDRA "\x1D\x2"
#define PORTRAIT_PLUMERIA "\x1E\x2"
#define PORTRAIT_HOOD "\x1F\x2"
#define PORTRAIT_GENERIC_SOLDIER_BLUE "\x20\x2"
#define PORTRAIT_GENERIC_SOLDIER_RED "\x21\x2"
#define PORTRAIT_GENERIC_SOLDIER_GREEN "\x22\x2"
#define PORTRAIT_REGHIN "\x23\x2"
#define PORTRAIT_LETIZIA "\x24\x2"
#define PORTRAIT_OTR "\x25\x2"
#define PORTRAIT_FAFNIR "\x26\x2"
#define PORTRAIT_EITRI "\x27\x2"
#define PORTRAIT_DAGR "\x28\x2"
#define PORTRAIT_NOTT "\x29\x2"
#define PORTRAIT_ASH "\x2A\x2"
#define PORTRAIT_VERONICA_STAIN "\x2B\x2"
#define PORTRAIT_ELM "\x2C\x2"

#define PORTRAIT_ID_HOOD 0x11F

#define PORTRAIT_ID_REGHIN 0x123
#define PORTRAIT_ID_LETIZIA 0x124
#define PORTRAIT_ID_OTR 0x125
#define PORTRAIT_ID_FAFNIR 0x126
#define PORTRAIT_ID_EITRI 0x127
#define PORTRAIT_ID_DAGR 0x128
#define PORTRAIT_ID_NOTT 0x129
#define PORTRAIT_ID_ASH 0x12A
#define PORTRAIT_ID_VERONICA_STAIN 0x12B
#define PORTRAIT_ID_ELM 0x12C

#define CLASSCARD_LORD 0x130
#define CLASSCARD_MAGE_KNIGHT 0x131
#define CLASSCARD_HALBERDIER 0x132
#define CLASSCARD_BONEWALKER 0x133
#define CLASSCARD_DRACOZOMBIE 0x134
#define CLASSCARD_GHOST 0x135
#define CLASSCARD_PHANTOM 0x136
#define CLASSCARD_REVENANT 0x137
#define CLASSCARD_WOLF 0x138

#define PORTRAIT_ID_DAGR_BG 0x141
#define PORTRAIT_ID_NOTT_BG 0x142

#define PORTRAIT_ID_AVATAR_F_1 0x150
#define PORTRAIT_ID_AVATAR_F_2 0x151
#define PORTRAIT_ID_AVATAR_F_3 0x152
#define PORTRAIT_ID_AVATAR_F_4 0x153
#define PORTRAIT_ID_AVATAR_M_1 0x154
#define PORTRAIT_ID_AVATAR_M_2 0x155
#define PORTRAIT_ID_AVATAR_M_3 0x156
#define PORTRAIT_ID_AVATAR_M_4 0x157
#define PORTRAIT_ID_AVATAR 74

#define PORTRAIT_AVATAR_F_1 "\x50\x2"
#define PORTRAIT_AVATAR_F_2 "\x51\x2"
#define PORTRAIT_AVATAR_F_3 "\x52\x2"
#define PORTRAIT_AVATAR_F_4 "\x53\x2"
#define PORTRAIT_AVATAR_M_1 "\x54\x2"
#define PORTRAIT_AVATAR_M_2 "\x55\x2"
#define PORTRAIT_AVATAR_M_3 "\x56\x2"
#define PORTRAIT_AVATAR_M_4 "\x57\x2"
#define PORTRAIT_AVATAR "\x4A\x1"

#define CLASSCARD_FIREDRAGON 222

#endif //FE7_JP_STUNNING_TRIBBLE_PORTRAIT_ID_H
