//
// Created by laqieer on 2020/2/7.
//

#include <gba_types.h>
#include "text_id.h"
#include "music_id.h"
#include "chapter.h"

const int sizeofChapter = sizeof(struct Chapter);

// map animation id
#define MAP_ANIM_NONE 0
#define MAP_ANIM_WATER_FIELD 5
#define MAP_ANIM_WATER_TOWN 0x58
#define MAP_ANIM_WATER_SHIP 0x5F
#define MAP_ANIM_WATER_CASTLE 0xA1
#define MAP_ANIM_ICE 0x9800
#define MAP_ANIM_LAVA 0xAB00
#define MAP_ANIM_DRAGON_GATE 0xC5

#define DEFINE_SIMPLE_CHAPTER(index, name, tileSet, animation, mapChange, bgm) { name, (tileSet) >> 24, ((tileSet) >> 16) & 0xff, ((tileSet) >> 8) & 0xff, (tileSet) & 0xff, index, (animation) & 0xff, (animation) >> 8, mapChange, 0, 0, index, index, 1, 0, 0, 4, 3, 0, bgm, bgm, bgm, bgm, bgm, bgm, 0xffff, 0xffff, 0x25, 0xffff, 0xffff, 30, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 100, 100, 100, 100, 80, 80, 80, 80, 60, 60, 60, 60, 40, 40, 40, 40, 1060, 1060, 1060, 1060, TEXT_CHAP_##index##_TITLE, TEXT_CHAP_##index##_TITLE, (index) + 1, 0, 0, 0, 0, 0, 0, 0, index, index, 0xff, 0xff, 0, 0, 1, 0, TEXT_CHAP_STATUS_GOAL_DEFEAT_ALL, TEXT_CHAP_GOAL_DEFEAT_ALL, 1, 0, 0, 0xff, 0, 14},
#define DEFINE_SIMPLE_CHAPTER_NEW(index, name, bgm) { name, (index) + 1, 0, (index) + 1, (index) + 1, 18, 0, 0, 0, 0, 0, index, index, 1, 0, 0, 4, 3, 0, bgm, bgm, bgm, bgm, bgm, bgm, 0xffff, 0xffff, 0x25, 0xffff, 0xffff, 30, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 100, 100, 100, 100, 80, 80, 80, 80, 60, 60, 60, 60, 40, 40, 40, 40, 1060, 1060, 1060, 1060, TEXT_CHAP_##index##_TITLE, TEXT_CHAP_##index##_TITLE, (index) + 1, 0, 0, 0, 0, 0, 0, 0, index, index, 0xff, 0xff, 0, 0, 1, 0, TEXT_CHAP_STATUS_GOAL_DEFEAT_ALL, TEXT_CHAP_GOAL_DEFEAT_ALL, 1, 0, 0, 0xff, 0, 14},
#define DEFINE_SIMPLE_CHAPTER_WITH_MAP(index, name, bgm, map, mapChange) { name, (index) + 1, 0, (index) + 1, (index) + 1, map, 0, 0, mapChange, 0, 0, index, index, 1, 0, 0, 4, 3, 0, bgm, bgm, bgm, bgm, bgm, bgm, 0xffff, 0xffff, 0x25, 0xffff, 0xffff, 30, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 100, 100, 100, 100, 80, 80, 80, 80, 60, 60, 60, 60, 40, 40, 40, 40, 1060, 1060, 1060, 1060, TEXT_CHAP_##index##_TITLE, TEXT_CHAP_##index##_TITLE, (index) + 1, 0, 0, 0, 0, 0, 0, 0, index, index, 0xff, 0xff, 0, 0, 1, 0, TEXT_CHAP_STATUS_GOAL_DEFEAT_ALL, TEXT_CHAP_GOAL_DEFEAT_ALL, 1, 0, 0, 0xff, 0, 14},
#define DEFINE_SIMPLE_CHAPTER_WITH_MAP_FOG(index, name, bgm, map, mapChange) { name, (index) + 1, 0, (index) + 1, (index) + 1, map, 0, 0, mapChange, 2, 0, index, index, 1, 0, 0, 4, 3, 0, bgm, bgm, bgm, bgm, bgm, bgm, 0xffff, 0xffff, 0x25, 0xffff, 0xffff, 30, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 100, 100, 100, 100, 80, 80, 80, 80, 60, 60, 60, 60, 40, 40, 40, 40, 1060, 1060, 1060, 1060, TEXT_CHAP_##index##_TITLE, TEXT_CHAP_##index##_TITLE, (index) + 1, 0, 0, 0, 0, 0, 0, 0, index, index, 0xff, 0xff, 0, 0, 1, 0, TEXT_CHAP_STATUS_GOAL_DEFEAT_ALL, TEXT_CHAP_GOAL_DEFEAT_ALL, 1, 0, 0, 0xff, 0, 14},
#define DEFINE_SIMPLE_CHAPTER_WITH_WEATHER(index, name, bgm, weather) { name, (index) + 1, 0, (index) + 1, (index) + 1, 18, 0, 0, 0, 0, 0, index, index, 1, 0, weather, 4, 3, 0, bgm, bgm, bgm, bgm, bgm, bgm, 0xffff, 0xffff, 0x25, 0xffff, 0xffff, 30, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 100, 100, 100, 100, 80, 80, 80, 80, 60, 60, 60, 60, 40, 40, 40, 40, 1060, 1060, 1060, 1060, TEXT_CHAP_##index##_TITLE, TEXT_CHAP_##index##_TITLE, (index) + 1, 0, 0, 0, 0, 0, 0, 0, index, index, 0xff, 0xff, 0, 0, 1, 0, TEXT_CHAP_STATUS_GOAL_DEFEAT_ALL, TEXT_CHAP_GOAL_DEFEAT_ALL, 1, 0, 0, 0xff, 0, 14},
#define DEFINE_SIMPLE_CHAPTER_WITH_MAP_CHANGE(index, name, bgm, mapChange) { name, (index) + 1, 0, (index) + 1, (index) + 1, 18, 0, 0, mapChange, 0, 0, index, index, 1, 0, 0, 4, 3, 0, bgm, bgm, bgm, bgm, bgm, bgm, 0xffff, 0xffff, 0x25, 0xffff, 0xffff, 30, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 100, 100, 100, 100, 80, 80, 80, 80, 60, 60, 60, 60, 40, 40, 40, 40, 1060, 1060, 1060, 1060, TEXT_CHAP_##index##_TITLE, TEXT_CHAP_##index##_TITLE, (index) + 1, 0, 0, 0, 0, 0, 0, 0, index, index, 0xff, 0xff, 0, 0, 1, 0, TEXT_CHAP_STATUS_GOAL_DEFEAT_ALL, TEXT_CHAP_GOAL_DEFEAT_ALL, 1, 0, 0, 0xff, 0, 14},

const struct Chapter chapters[0xff] = {
            {
            "1.1.1)00",
            1,
            0,
            1,
            1,
            18,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            4,
            3,
            0,
            MUSIC_FE_H_TEMPEST_TRIAL,
            MUSIC_FE_H_TEMPEST_TRIAL,
            MUSIC_FE_H_TEMPEST_TRIAL,
            MUSIC_FE_H_TEMPEST_TRIAL,
            MUSIC_FE_H_TEMPEST_TRIAL,
            MUSIC_FE_H_TEMPEST_TRIAL,
            0xffff,
            0xffff,
            0x25,
            0xffff,
            0xffff,
            100,
            5,
            5,
            5,
            5,
            6,
            6,
            6,
            6,
            7,
            7,
            7,
            7,
            8,
            8,
            8,
            8,
            100,
            100,
            100,
            100,
            80,
            80,
            80,
            80,
            60,
            60,
            60,
            60,
            40,
            40,
            40,
            40,
            1060,
            1060,
            1060,
            1060,
            TEXT_CHAP_PRE_TITLE,
            TEXT_CHAP_PRE_TITLE,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0xff,
            0xff,
            0,
            0,
            1,
            0,
            TEXT_CHAP_STATUS_GOAL_DEFEAT_ALL,
            TEXT_CHAP_GOAL_DEFEAT_ALL,
            1,
            0,
            0,
            0xff,
            0,
            14,
            },
            {
                    "1.1.2)01",
                    2,
                    0,
                    2,
                    2,
                    19,
                    0,
                    0,
                    3,
                    0,
                    0,
                    1,
                    1,
                    1,
                    0,
                    0,
                    4,
                    3,
                    0,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    0xffff,
                    0xffff,
                    0x25,
                    0xffff,
                    0xffff,
                    30,
                    5,
                    5,
                    5,
                    5,
                    6,
                    6,
                    6,
                    6,
                    7,
                    7,
                    7,
                    7,
                    8,
                    8,
                    8,
                    8,
                    100,
                    100,
                    100,
                    100,
                    80,
                    80,
                    80,
                    80,
                    60,
                    60,
                    60,
                    60,
                    40,
                    40,
                    40,
                    40,
                    1060,
                    1060,
                    1060,
                    1060,
                    TEXT_CHAP_1_TITLE,
                    TEXT_CHAP_1_TITLE,
                    2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    0xff,
                    0xff,
                    0,
                    0,
                    1,
                    0,
                    TEXT_CHAP_STATUS_GOAL_DEFEAT_ALL,
                    TEXT_CHAP_GOAL_DEFEAT_ALL,
                    1,
                    0,
                    0,
                    0xff,
                    0,
                    14,
            },
            {
                    "1.1.3)02",
                    3,
                    0,
                    3,
                    3,
                    18,
                    0,
                    0,
                    0,
                    0,
                    0,
                    2,
                    2,
                    1,
                    0,
                    0,
                    4,
                    3,
                    0,
                    MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE,
                    MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE,
                    MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE,
                    MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE,
                    MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE,
                    MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE,
                    0xffff,
                    0xffff,
                    0x25,
                    0xffff,
                    0xffff,
                    30,
                    5,
                    5,
                    5,
                    5,
                    6,
                    6,
                    6,
                    6,
                    7,
                    7,
                    7,
                    7,
                    8,
                    8,
                    8,
                    8,
                    100,
                    100,
                    100,
                    100,
                    80,
                    80,
                    80,
                    80,
                    60,
                    60,
                    60,
                    60,
                    40,
                    40,
                    40,
                    40,
                    1060,
                    1060,
                    1060,
                    1060,
                    TEXT_CHAP_2_TITLE,
                    TEXT_CHAP_2_TITLE,
                    3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    2,
                    2,
                    0xff,
                    0xff,
                    0,
                    0,
                    1,
                    0,
                    TEXT_CHAP_STATUS_GOAL_DEFEAT_BOSS_XANDER,
                    TEXT_CHAP_GOAL_DEFEAT_BOSS,
                    3,
                    0,
                    0,
                    0xff,
                    0,
                    14,
            },
            {
                    "1.2.1)03",
                    4,
                    0,
                    4,
                    4,
                    20,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    3,
                    1,
                    0,
                    0,
                    4,
                    3,
                    0,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    0xffff,
                    0xffff,
                    0x25,
                    0xffff,
                    0xffff,
                    30,
                    5,
                    5,
                    5,
                    5,
                    6,
                    6,
                    6,
                    6,
                    7,
                    7,
                    7,
                    7,
                    8,
                    8,
                    8,
                    8,
                    100,
                    100,
                    100,
                    100,
                    80,
                    80,
                    80,
                    80,
                    60,
                    60,
                    60,
                    60,
                    40,
                    40,
                    40,
                    40,
                    1060,
                    1060,
                    1060,
                    1060,
                    TEXT_CHAP_3_TITLE,
                    TEXT_CHAP_3_TITLE,
                    4,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    3,
                    0xff,
                    0xff,
                    0,
                    0,
                    1,
                    0,
                    TEXT_CHAP_STATUS_GOAL_DEFEAT_ALL,
                    TEXT_CHAP_GOAL_DEFEAT_ALL,
                    1,
                    0,
                    0,
                    0xff,
                    0,
                    14,
            },
            {
                    "1.2.2)04",
                    5,
                    0,
                    5,
                    5,
                    18,
                    0,
                    0,
                    0,
                    0,
                    0,
                    4,
                    4,
                    1,
                    0,
                    0,
                    4,
                    3,
                    0,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    MUSIC_MAP_FE03,
                    0xffff,
                    0xffff,
                    0x25,
                    0xffff,
                    0xffff,
                    30,
                    5,
                    5,
                    5,
                    5,
                    6,
                    6,
                    6,
                    6,
                    7,
                    7,
                    7,
                    7,
                    8,
                    8,
                    8,
                    8,
                    100,
                    100,
                    100,
                    100,
                    80,
                    80,
                    80,
                    80,
                    60,
                    60,
                    60,
                    60,
                    40,
                    40,
                    40,
                    40,
                    1060,
                    1060,
                    1060,
                    1060,
                    TEXT_CHAP_4_TITLE,
                    TEXT_CHAP_4_TITLE,
                    5,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    4,
                    4,
                    0xff,
                    0xff,
                    0,
                    0,
                    1,
                    0,
                    TEXT_CHAP_STATUS_GOAL_DEFEAT_ALL,
                    TEXT_CHAP_GOAL_DEFEAT_ALL,
                    1,
                    0,
                    0,
                    0xff,
                    0,
                    14,
            },
            //DEFINE_SIMPLE_CHAPTER(5, "1.2.3)05", 0x7b007c7d, 0, 0, MUSIC_MAP_FE03)
            DEFINE_SIMPLE_CHAPTER_NEW(5, "1.2.3)05", MUSIC_MAP_FE03)
            //DEFINE_SIMPLE_CHAPTER(6, "1.2.4)06", 0x1c1d1e1f, MAP_ANIM_WATER_FIELD, 0, MUSIC_MAP_FE03)
            DEFINE_SIMPLE_CHAPTER_NEW(6, "1.2.4)06", MUSIC_MAP_FE03)
            //DEFINE_SIMPLE_CHAPTER(7, "1.2.5)07", 0x1c1d1e1f, MAP_ANIM_WATER_FIELD, 0, MUSIC_FE_3_DIVINE_DRAGON_LEGEND)
            DEFINE_SIMPLE_CHAPTER_NEW(7, "1.2.5)07", MUSIC_FE_3_DIVINE_DRAGON_LEGEND)
            //DEFINE_SIMPLE_CHAPTER(8, "1.3.1)08", 0x1c1d1e1f, MAP_ANIM_WATER_FIELD, 0, MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE)
            DEFINE_SIMPLE_CHAPTER_NEW(8, "1.3.1)08", MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE)
            //DEFINE_SIMPLE_CHAPTER(9, "1.3.2)09", 0x6a006b6c, MAP_ANIM_NONE, 2, MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE)
            DEFINE_SIMPLE_CHAPTER_WITH_MAP(9, "1.3.2)09", MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE, 21, 4)
            //DEFINE_SIMPLE_CHAPTER(10, "1.3.3)10", 0x6a006b6c, MAP_ANIM_NONE, 0, MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE)
            DEFINE_SIMPLE_CHAPTER_NEW(10, "1.3.3)10", MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE)
            //DEFINE_SIMPLE_CHAPTER(11, "1.3.4)11", 0xa700a8a9, MAP_ANIM_LAVA, 0, MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE)
            //DEFINE_SIMPLE_CHAPTER_WITH_WEATHER(11, "1.3.4)11", MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE, WEATHER_FIERY_GLOW)
            DEFINE_SIMPLE_CHAPTER_NEW(11, "1.3.4)11", MUSIC_FE_IF_LOST_IN_THOUGHTS_ALL_ALONE)
            //DEFINE_SIMPLE_CHAPTER(12, "1.3.5)12", 0x6a006b6c, MAP_ANIM_NONE, 0, MUSIC_FE_IF_END_ALL)
            DEFINE_SIMPLE_CHAPTER_NEW(12, "1.3.5)12", MUSIC_FE_IF_END_ALL)
            //DEFINE_SIMPLE_CHAPTER(13, "1.4.1)13", 0x6a006b6c, MAP_ANIM_NONE, 0, 112)
            DEFINE_SIMPLE_CHAPTER_NEW(13, "1.4.1)13", 112)
            //DEFINE_SIMPLE_CHAPTER(14, "1.4.2)14", 0x6a006b6c, MAP_ANIM_NONE, 0, 112)
            DEFINE_SIMPLE_CHAPTER_NEW(14, "1.4.2)14", 112)
            //DEFINE_SIMPLE_CHAPTER(15, "1.4.3)15", 0x7b007c7d, MAP_ANIM_NONE, 0, 112)
            DEFINE_SIMPLE_CHAPTER_NEW(15, "1.4.3)15", 112)
            //DEFINE_SIMPLE_CHAPTER(16, "1.4.4)16", 0x91009293, MAP_ANIM_ICE, 0, 112)
            DEFINE_SIMPLE_CHAPTER_NEW(16, "1.4.4)16", 112)
            //DEFINE_SIMPLE_CHAPTER(17, "1.4.5)17", 0xa700a8a9, MAP_ANIM_LAVA, 0, 113)
            DEFINE_SIMPLE_CHAPTER_NEW(17, "1.4.5)17", 113)
            DEFINE_SIMPLE_CHAPTER_NEW(18, "1.5.1)18", MUSIC_FE_AWAKENING_ID_SERENITY)
            DEFINE_SIMPLE_CHAPTER_NEW(19, "1.5.2)19", MUSIC_FE_AWAKENING_ID_SERENITY)
            DEFINE_SIMPLE_CHAPTER_NEW(20, "1.5.3)20", MUSIC_FE_AWAKENING_ID_SERENITY)
            DEFINE_SIMPLE_CHAPTER_WITH_MAP(21, "1.5.4)21", MUSIC_FE_AWAKENING_ID_SERENITY, 22, 5)
            DEFINE_SIMPLE_CHAPTER_NEW(22, "1.5.5)22", MUSIC_FE_AWAKENING_ID_PURPOSE)
            DEFINE_SIMPLE_CHAPTER_NEW(23, "1.6.1)23", MUSIC_FE_3_HEROES_WAR)
            DEFINE_SIMPLE_CHAPTER_WITH_MAP(24, "1.6.2)24", MUSIC_FE_3_HEROES_WAR, 23, 6)
            DEFINE_SIMPLE_CHAPTER_NEW(25, "1.6.3)25", MUSIC_FE_3_HEROES_WAR)
            DEFINE_SIMPLE_CHAPTER_NEW(26, "1.6.4)26", MUSIC_FE_3_HEROES_WAR)
            DEFINE_SIMPLE_CHAPTER_NEW(27, "1.6.5)27", MUSIC_FE_3_DIVINE_DRAGON_LEGEND_B)
            DEFINE_SIMPLE_CHAPTER_NEW(28, "1.7.1)28", MUSIC_FE_FATES_ROAD_TAKEN)
            DEFINE_SIMPLE_CHAPTER_WITH_MAP_CHANGE(29, "1.7.2)29", MUSIC_FE_FATES_ROAD_TAKEN, 7)
            DEFINE_SIMPLE_CHAPTER_NEW(30, "1.7.3)30", MUSIC_FE_FATES_ROAD_TAKEN)
            DEFINE_SIMPLE_CHAPTER_WITH_MAP_CHANGE(31, "1.7.4)31", MUSIC_FE_FATES_ROAD_TAKEN, 8)
            DEFINE_SIMPLE_CHAPTER_WITH_MAP_CHANGE(32, "1.7.5)32", MUSIC_FE_FATES_AS_ALL_STARS_FALL, 9)
            DEFINE_SIMPLE_CHAPTER_NEW(33, "1.8.1)33", MUSIC_WIND_ACROSS_THE_PLAIN)
            DEFINE_SIMPLE_CHAPTER_NEW(34, "1.8.2)34", MUSIC_WIND_ACROSS_THE_PLAIN)
            DEFINE_SIMPLE_CHAPTER_WITH_MAP_FOG(35, "1.8.3)35", MUSIC_SHADOW_APPROACHES, 24, 10)
            DEFINE_SIMPLE_CHAPTER_NEW(36, "1.8.4)36", MUSIC_WIND_ACROSS_THE_PLAIN)
            DEFINE_SIMPLE_CHAPTER_NEW(37, "1.8.5)37", MUSIC_COMPANIONS)
            DEFINE_SIMPLE_CHAPTER_NEW(38, "1.9.1)38", MUSIC_FE_AWAKENING_MAIN_THEME_TITLE)
            DEFINE_SIMPLE_CHAPTER_NEW(39, "1.9.2)39", MUSIC_FE_AWAKENING_MAIN_THEME_TITLE)
            DEFINE_SIMPLE_CHAPTER_NEW(40, "1.9.3)40", MUSIC_FE_AWAKENING_MAIN_THEME_TITLE)
            DEFINE_SIMPLE_CHAPTER_NEW(41, "1.9.4)41", MUSIC_FE_3_DIVINE_DRAGON_LEGEND_B)
            DEFINE_SIMPLE_CHAPTER_WITH_MAP(42, "1.9.5)42", MUSIC_FE_AWAKENING_YOU_CAN_CALL_ME_MARTH, 25, 11)
            DEFINE_SIMPLE_CHAPTER_NEW(43, "1.10.1)43", MUSIC_FE_H_TEMPEST_TRIAL)
            DEFINE_SIMPLE_CHAPTER_NEW(44, "1.10.2)44", MUSIC_FE_H_TEMPEST_TRIAL)
            DEFINE_SIMPLE_CHAPTER_NEW(45, "1.10.3)45", MUSIC_FE_H_TEMPEST_TRIAL)
            DEFINE_SIMPLE_CHAPTER_WITH_MAP(46, "1.10.4)46", MUSIC_FE_H_TEMPEST_TRIAL, 26, 12)
            DEFINE_SIMPLE_CHAPTER_NEW(47, "1.10.5)47", MUSIC_FE_H_TEMPEST_TRIAL)
};

const struct Chapter * const pChapters1 = chapters;
const struct Chapter * const pChapters2 = chapters;
const struct Chapter * const pChapters3 = chapters;
const struct Chapter * const pChapters4 = chapters;
const struct Chapter * const pChapters5 = chapters;
const struct Chapter * const pChapters6 = chapters;

const u8 chapterNumber = 0xff;
