name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate fake ROM
      run: head -c 16MB /dev/urandom > rom/fe7-jp.gba
    - name: Install DevkitARM
      run: |
        wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
        sudo dpkg -i devkitpro-pacman.deb
        rm devkitpro-pacman.deb
        sudo dkp-pacman --noconfirm -S gba-dev
    - name: Build
      run: |
        export DEVKITPRO=/opt/devkitpro
        export DEVKITARM=${DEVKITPRO}/devkitARM
        ./configure
        cd build/
        make
